# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
__send__(:define_generated_method,
    :accept_drag_drop_payload,
    :igAcceptDragDropPayload,
    [["type", "const char*"], ["flags", "ImGuiDragDropFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :align_text_to_frame_padding,
    :igAlignTextToFramePadding,
    [],
    {}
  )
__send__(:define_generated_method,
    :arrow_button,
    :igArrowButton,
    [["str_id", "const char*"], ["dir", "ImGuiDir"]],
    {}
  )
__send__(:define_generated_method,
    :bullet,
    :igBullet,
    [],
    {}
  )
__send__(:define_generated_method,
    :calc_item_width,
    :igCalcItemWidth,
    [],
    {}
  )
__send__(:define_generated_method,
    :calc_text_size,
    :igCalcTextSize,
    [["pOut", "ImVec2*"], ["text", "const char*"], ["text_end", "const char*"], ["hide_text_after_double_hash", "bool"], ["wrap_width", "float"]],
    {"hide_text_after_double_hash" => false, "text_end" => nil, "wrap_width" => -1.0}
  )
__send__(:define_generated_method,
    :checkbox_flags,
    :igCheckboxFlags_IntPtr,
    [["label", "const char*"], ["flags", "int*"], ["flags_value", "int"]],
    {}
  )
__send__(:define_generated_method,
    :close_current_popup,
    :igCloseCurrentPopup,
    [],
    {}
  )
__send__(:define_generated_method,
    :collapsing_header,
    :igCollapsingHeader_TreeNodeFlags,
    [["label", "const char*"], ["flags", "ImGuiTreeNodeFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :color_button,
    :igColorButton,
    [["desc_id", "const char*"], ["col", "const ImVec4"], ["flags", "ImGuiColorEditFlags"], ["size", "const ImVec2"]],
    {"flags" => 0, "size" => [0, 0]}
  )
__send__(:define_generated_method,
    :color_convert_float4_to_u32,
    :igColorConvertFloat4ToU32,
    [["in", "const ImVec4"]],
    {}
  )
__send__(:define_generated_method,
    :color_convert_hs_vto_rgb,
    :igColorConvertHSVtoRGB,
    [["h", "float"], ["s", "float"], ["v", "float"], ["out_r", "float*"], ["out_g", "float*"], ["out_b", "float*"]],
    {}
  )
__send__(:define_generated_method,
    :color_convert_rg_bto_hsv,
    :igColorConvertRGBtoHSV,
    [["r", "float"], ["g", "float"], ["b", "float"], ["out_h", "float*"], ["out_s", "float*"], ["out_v", "float*"]],
    {}
  )
__send__(:define_generated_method,
    :color_convert_u32_to_float4,
    :igColorConvertU32ToFloat4,
    [["pOut", "ImVec4*"], ["in", "ImU32"]],
    {}
  )
__send__(:define_generated_method,
    :color_picker3,
    :igColorPicker3,
    [["label", "const char*"], ["col", "float[3]"], ["flags", "ImGuiColorEditFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :color_picker4,
    :igColorPicker4,
    [["label", "const char*"], ["col", "float[4]"], ["flags", "ImGuiColorEditFlags"], ["ref_col", "const float*"]],
    {"flags" => 0, "ref_col" => nil}
  )
__send__(:define_generated_method,
    :columns,
    :igColumns,
    [["count", "int"], ["id", "const char*"], ["borders", "bool"]],
    {"borders" => true, "count" => 1, "id" => nil}
  )
__send__(:define_generated_method,
    :combo,
    :igCombo_Str,
    [["label", "const char*"], ["current_item", "int*"], ["items_separated_by_zeros", "const char*"], ["popup_max_height_in_items", "int"]],
    {"popup_max_height_in_items" => -1}
  )
__send__(:define_generated_method,
    :debug_check_version_and_data_layout,
    :igDebugCheckVersionAndDataLayout,
    [["version_str", "const char*"], ["sz_io", "size_t"], ["sz_style", "size_t"], ["sz_vec2", "size_t"], ["sz_vec4", "size_t"], ["sz_drawvert", "size_t"], ["sz_drawidx", "size_t"]],
    {}
  )
__send__(:define_generated_method,
    :debug_flash_style_color,
    :igDebugFlashStyleColor,
    [["idx", "ImGuiCol"]],
    {}
  )
__send__(:define_generated_method,
    :debug_start_item_picker,
    :igDebugStartItemPicker,
    [],
    {}
  )
__send__(:define_generated_method,
    :debug_text_encoding,
    :igDebugTextEncoding,
    [["text", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :destroy_platform_windows,
    :igDestroyPlatformWindows,
    [],
    {}
  )
__send__(:define_generated_method,
    :dock_space,
    :igDockSpace,
    [["dockspace_id", "ImGuiID"], ["size", "const ImVec2"], ["flags", "ImGuiDockNodeFlags"], ["window_class", "const ImGuiWindowClass*"]],
    {"flags" => 0, "size" => [0, 0], "window_class" => nil}
  )
__send__(:define_generated_method,
    :dock_space_over_viewport,
    :igDockSpaceOverViewport,
    [["dockspace_id", "ImGuiID"], ["viewport", "const ImGuiViewport*"], ["flags", "ImGuiDockNodeFlags"], ["window_class", "const ImGuiWindowClass*"]],
    {"dockspace_id" => 0, "flags" => 0, "viewport" => nil, "window_class" => nil}
  )
__send__(:define_generated_method,
    :drag_float2,
    :igDragFloat2,
    [["label", "const char*"], ["v", "float[2]"], ["v_speed", "float"], ["v_min", "float"], ["v_max", "float"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%.3f", "v_max" => 0.0, "v_min" => 0.0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_float3,
    :igDragFloat3,
    [["label", "const char*"], ["v", "float[3]"], ["v_speed", "float"], ["v_min", "float"], ["v_max", "float"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%.3f", "v_max" => 0.0, "v_min" => 0.0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_float4,
    :igDragFloat4,
    [["label", "const char*"], ["v", "float[4]"], ["v_speed", "float"], ["v_min", "float"], ["v_max", "float"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%.3f", "v_max" => 0.0, "v_min" => 0.0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_float_range2,
    :igDragFloatRange2,
    [["label", "const char*"], ["v_current_min", "float*"], ["v_current_max", "float*"], ["v_speed", "float"], ["v_min", "float"], ["v_max", "float"], ["format", "const char*"], ["format_max", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%.3f", "format_max" => nil, "v_max" => 0.0, "v_min" => 0.0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_int2,
    :igDragInt2,
    [["label", "const char*"], ["v", "int[2]"], ["v_speed", "float"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d", "v_max" => 0, "v_min" => 0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_int3,
    :igDragInt3,
    [["label", "const char*"], ["v", "int[3]"], ["v_speed", "float"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d", "v_max" => 0, "v_min" => 0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_int4,
    :igDragInt4,
    [["label", "const char*"], ["v", "int[4]"], ["v_speed", "float"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d", "v_max" => 0, "v_min" => 0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_int_range2,
    :igDragIntRange2,
    [["label", "const char*"], ["v_current_min", "int*"], ["v_current_max", "int*"], ["v_speed", "float"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["format_max", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d", "format_max" => nil, "v_max" => 0, "v_min" => 0, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_scalar,
    :igDragScalar,
    [["label", "const char*"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["v_speed", "float"], ["p_min", "const void*"], ["p_max", "const void*"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => nil, "p_max" => nil, "p_min" => nil, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :drag_scalar_n,
    :igDragScalarN,
    [["label", "const char*"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["components", "int"], ["v_speed", "float"], ["p_min", "const void*"], ["p_max", "const void*"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => nil, "p_max" => nil, "p_min" => nil, "v_speed" => 1.0}
  )
__send__(:define_generated_method,
    :find_viewport_by_id,
    :igFindViewportByID,
    [["id", "ImGuiID"]],
    {}
  )
__send__(:define_generated_method,
    :find_viewport_by_platform_handle,
    :igFindViewportByPlatformHandle,
    [["platform_handle", "void*"]],
    {}
  )
__send__(:define_generated_method,
    :get_allocator_functions,
    :igGetAllocatorFunctions,
    [["p_alloc_func", "ImGuiMemAllocFunc*"], ["p_free_func", "ImGuiMemFreeFunc*"], ["p_user_data", "void**"]],
    {}
  )
__send__(:define_generated_method,
    :get_background_draw_list,
    :igGetBackgroundDrawList,
    [["viewport", "ImGuiViewport*"]],
    {"viewport" => nil}
  )
__send__(:define_generated_method,
    :get_clipboard_text,
    :igGetClipboardText,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_color_u32,
    :igGetColorU32_Vec4,
    [["col", "const ImVec4"]],
    {}
  )
__send__(:define_generated_method,
    :get_column_index,
    :igGetColumnIndex,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_column_offset,
    :igGetColumnOffset,
    [["column_index", "int"]],
    {"column_index" => -1}
  )
__send__(:define_generated_method,
    :get_column_width,
    :igGetColumnWidth,
    [["column_index", "int"]],
    {"column_index" => -1}
  )
__send__(:define_generated_method,
    :get_columns_count,
    :igGetColumnsCount,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_content_region_avail,
    :igGetContentRegionAvail,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_cursor_pos,
    :igGetCursorPos,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_cursor_pos_x,
    :igGetCursorPosX,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_cursor_pos_y,
    :igGetCursorPosY,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_cursor_screen_pos,
    :igGetCursorScreenPos,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_cursor_start_pos,
    :igGetCursorStartPos,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_drag_drop_payload,
    :igGetDragDropPayload,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_draw_list_shared_data,
    :igGetDrawListSharedData,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_font,
    :igGetFont,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_font_size,
    :igGetFontSize,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_font_tex_uv_white_pixel,
    :igGetFontTexUvWhitePixel,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_foreground_draw_list,
    :igGetForegroundDrawList_ViewportPtr,
    [["viewport", "ImGuiViewport*"]],
    {"viewport" => nil}
  )
__send__(:define_generated_method,
    :get_frame_count,
    :igGetFrameCount,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_frame_height,
    :igGetFrameHeight,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_frame_height_with_spacing,
    :igGetFrameHeightWithSpacing,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_id,
    :igGetID_Str,
    [["str_id", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :get_item_id,
    :igGetItemID,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_item_rect_max,
    :igGetItemRectMax,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_item_rect_min,
    :igGetItemRectMin,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_item_rect_size,
    :igGetItemRectSize,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_key_name,
    :igGetKeyName,
    [["key", "ImGuiKey"]],
    {}
  )
__send__(:define_generated_method,
    :get_key_pressed_amount,
    :igGetKeyPressedAmount,
    [["key", "ImGuiKey"], ["repeat_delay", "float"], ["rate", "float"]],
    {}
  )
__send__(:define_generated_method,
    :get_main_viewport,
    :igGetMainViewport,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_mouse_clicked_count,
    :igGetMouseClickedCount,
    [["button", "ImGuiMouseButton"]],
    {}
  )
__send__(:define_generated_method,
    :get_mouse_cursor,
    :igGetMouseCursor,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_mouse_drag_delta,
    :igGetMouseDragDelta,
    [["pOut", "ImVec2*"], ["button", "ImGuiMouseButton"], ["lock_threshold", "float"]],
    {"button" => 0, "lock_threshold" => -1.0}
  )
__send__(:define_generated_method,
    :get_mouse_pos,
    :igGetMousePos,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_mouse_pos_on_opening_current_popup,
    :igGetMousePosOnOpeningCurrentPopup,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_platform_io,
    :igGetPlatformIO_Nil,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_scroll_max_x,
    :igGetScrollMaxX,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_scroll_max_y,
    :igGetScrollMaxY,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_scroll_x,
    :igGetScrollX,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_scroll_y,
    :igGetScrollY,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_state_storage,
    :igGetStateStorage,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_style_color_name,
    :igGetStyleColorName,
    [["idx", "ImGuiCol"]],
    {}
  )
__send__(:define_generated_method,
    :get_style_color_vec4,
    :igGetStyleColorVec4,
    [["idx", "ImGuiCol"]],
    {}
  )
__send__(:define_generated_method,
    :get_text_line_height,
    :igGetTextLineHeight,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_text_line_height_with_spacing,
    :igGetTextLineHeightWithSpacing,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_time,
    :igGetTime,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_tree_node_to_label_spacing,
    :igGetTreeNodeToLabelSpacing,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_window_dock_id,
    :igGetWindowDockID,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_window_dpi_scale,
    :igGetWindowDpiScale,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_window_draw_list,
    :igGetWindowDrawList,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_window_height,
    :igGetWindowHeight,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_window_pos,
    :igGetWindowPos,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_window_size,
    :igGetWindowSize,
    [["pOut", "ImVec2*"]],
    {}
  )
__send__(:define_generated_method,
    :get_window_viewport,
    :igGetWindowViewport,
    [],
    {}
  )
__send__(:define_generated_method,
    :get_window_width,
    :igGetWindowWidth,
    [],
    {}
  )
__send__(:define_generated_method,
    :image,
    :igImage,
    [["user_texture_id", "ImTextureID"], ["image_size", "const ImVec2"], ["uv0", "const ImVec2"], ["uv1", "const ImVec2"]],
    {"uv0" => [0, 0], "uv1" => [1, 1]}
  )
__send__(:define_generated_method,
    :image_button,
    :igImageButton,
    [["str_id", "const char*"], ["user_texture_id", "ImTextureID"], ["image_size", "const ImVec2"], ["uv0", "const ImVec2"], ["uv1", "const ImVec2"], ["bg_col", "const ImVec4"], ["tint_col", "const ImVec4"]],
    {"bg_col" => [0, 0, 0, 0], "tint_col" => [1, 1, 1, 1], "uv0" => [0, 0], "uv1" => [1, 1]}
  )
__send__(:define_generated_method,
    :image_with_bg,
    :igImageWithBg,
    [["user_texture_id", "ImTextureID"], ["image_size", "const ImVec2"], ["uv0", "const ImVec2"], ["uv1", "const ImVec2"], ["bg_col", "const ImVec4"], ["tint_col", "const ImVec4"]],
    {"bg_col" => [0, 0, 0, 0], "tint_col" => [1, 1, 1, 1], "uv0" => [0, 0], "uv1" => [1, 1]}
  )
__send__(:define_generated_method,
    :input_double,
    :igInputDouble,
    [["label", "const char*"], ["v", "double*"], ["step", "double"], ["step_fast", "double"], ["format", "const char*"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0, "format" => "%.6f", "step" => 0.0, "step_fast" => 0.0}
  )
__send__(:define_generated_method,
    :input_float2,
    :igInputFloat2,
    [["label", "const char*"], ["v", "float[2]"], ["format", "const char*"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0, "format" => "%.3f"}
  )
__send__(:define_generated_method,
    :input_float3,
    :igInputFloat3,
    [["label", "const char*"], ["v", "float[3]"], ["format", "const char*"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0, "format" => "%.3f"}
  )
__send__(:define_generated_method,
    :input_float4,
    :igInputFloat4,
    [["label", "const char*"], ["v", "float[4]"], ["format", "const char*"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0, "format" => "%.3f"}
  )
__send__(:define_generated_method,
    :input_int2,
    :igInputInt2,
    [["label", "const char*"], ["v", "int[2]"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :input_int3,
    :igInputInt3,
    [["label", "const char*"], ["v", "int[3]"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :input_int4,
    :igInputInt4,
    [["label", "const char*"], ["v", "int[4]"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :input_scalar,
    :igInputScalar,
    [["label", "const char*"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["p_step", "const void*"], ["p_step_fast", "const void*"], ["format", "const char*"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0, "format" => nil, "p_step" => nil, "p_step_fast" => nil}
  )
__send__(:define_generated_method,
    :input_scalar_n,
    :igInputScalarN,
    [["label", "const char*"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["components", "int"], ["p_step", "const void*"], ["p_step_fast", "const void*"], ["format", "const char*"], ["flags", "ImGuiInputTextFlags"]],
    {"flags" => 0, "format" => nil, "p_step" => nil, "p_step_fast" => nil}
  )
__send__(:define_generated_method,
    :input_text_multiline,
    :igInputTextMultiline,
    [["label", "const char*"], ["buf", "char*"], ["buf_size", "size_t"], ["size", "const ImVec2"], ["flags", "ImGuiInputTextFlags"], ["callback", "ImGuiInputTextCallback"], ["user_data", "void*"]],
    {"callback" => nil, "flags" => 0, "size" => [0, 0], "user_data" => nil}
  )
__send__(:define_generated_method,
    :input_text_with_hint,
    :igInputTextWithHint,
    [["label", "const char*"], ["hint", "const char*"], ["buf", "char*"], ["buf_size", "size_t"], ["flags", "ImGuiInputTextFlags"], ["callback", "ImGuiInputTextCallback"], ["user_data", "void*"]],
    {"callback" => nil, "flags" => 0, "user_data" => nil}
  )
__send__(:define_generated_method,
    :is_any_item_active,
    :igIsAnyItemActive,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_any_item_focused,
    :igIsAnyItemFocused,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_any_item_hovered,
    :igIsAnyItemHovered,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_any_mouse_down,
    :igIsAnyMouseDown,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_activated,
    :igIsItemActivated,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_active,
    :igIsItemActive,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_clicked,
    :igIsItemClicked,
    [["mouse_button", "ImGuiMouseButton"]],
    {"mouse_button" => 0}
  )
__send__(:define_generated_method,
    :is_item_deactivated,
    :igIsItemDeactivated,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_deactivated_after_edit,
    :igIsItemDeactivatedAfterEdit,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_edited,
    :igIsItemEdited,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_focused,
    :igIsItemFocused,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_hovered,
    :igIsItemHovered,
    [["flags", "ImGuiHoveredFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :is_item_toggled_open,
    :igIsItemToggledOpen,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_toggled_selection,
    :igIsItemToggledSelection,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_item_visible,
    :igIsItemVisible,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_key_chord_pressed,
    :igIsKeyChordPressed_Nil,
    [["key_chord", "ImGuiKeyChord"]],
    {}
  )
__send__(:define_generated_method,
    :is_key_down,
    :igIsKeyDown_Nil,
    [["key", "ImGuiKey"]],
    {}
  )
__send__(:define_generated_method,
    :is_key_pressed,
    :igIsKeyPressed_Bool,
    [["key", "ImGuiKey"], ["repeat", "bool"]],
    {"repeat" => true}
  )
__send__(:define_generated_method,
    :is_key_released,
    :igIsKeyReleased_Nil,
    [["key", "ImGuiKey"]],
    {}
  )
__send__(:define_generated_method,
    :is_mouse_clicked,
    :igIsMouseClicked_Bool,
    [["button", "ImGuiMouseButton"], ["repeat", "bool"]],
    {"repeat" => false}
  )
__send__(:define_generated_method,
    :is_mouse_double_clicked,
    :igIsMouseDoubleClicked_Nil,
    [["button", "ImGuiMouseButton"]],
    {}
  )
__send__(:define_generated_method,
    :is_mouse_down,
    :igIsMouseDown_Nil,
    [["button", "ImGuiMouseButton"]],
    {}
  )
__send__(:define_generated_method,
    :is_mouse_dragging,
    :igIsMouseDragging,
    [["button", "ImGuiMouseButton"], ["lock_threshold", "float"]],
    {"lock_threshold" => -1.0}
  )
__send__(:define_generated_method,
    :is_mouse_hovering_rect,
    :igIsMouseHoveringRect,
    [["r_min", "const ImVec2"], ["r_max", "const ImVec2"], ["clip", "bool"]],
    {"clip" => true}
  )
__send__(:define_generated_method,
    :is_mouse_pos_valid,
    :igIsMousePosValid,
    [["mouse_pos", "const ImVec2*"]],
    {"mouse_pos" => nil}
  )
__send__(:define_generated_method,
    :is_mouse_released,
    :igIsMouseReleased_Nil,
    [["button", "ImGuiMouseButton"]],
    {}
  )
__send__(:define_generated_method,
    :is_mouse_released_with_delay,
    :igIsMouseReleasedWithDelay,
    [["button", "ImGuiMouseButton"], ["delay", "float"]],
    {}
  )
__send__(:define_generated_method,
    :is_popup_open,
    :igIsPopupOpen_Str,
    [["str_id", "const char*"], ["flags", "ImGuiPopupFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :is_rect_visible,
    :igIsRectVisible_Nil,
    [["size", "const ImVec2"]],
    {}
  )
__send__(:define_generated_method,
    :is_window_appearing,
    :igIsWindowAppearing,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_window_collapsed,
    :igIsWindowCollapsed,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_window_docked,
    :igIsWindowDocked,
    [],
    {}
  )
__send__(:define_generated_method,
    :is_window_focused,
    :igIsWindowFocused,
    [["flags", "ImGuiFocusedFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :is_window_hovered,
    :igIsWindowHovered,
    [["flags", "ImGuiHoveredFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :list_box,
    :igListBox_Str_arr,
    [["label", "const char*"], ["current_item", "int*"], ["items", "const char* const[]"], ["items_count", "int"], ["height_in_items", "int"]],
    {"height_in_items" => -1}
  )
__send__(:define_generated_method,
    :load_ini_settings_from_disk,
    :igLoadIniSettingsFromDisk,
    [["ini_filename", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :load_ini_settings_from_memory,
    :igLoadIniSettingsFromMemory,
    [["ini_data", "const char*"], ["ini_size", "size_t"]],
    {"ini_size" => 0}
  )
__send__(:define_generated_method,
    :log_buttons,
    :igLogButtons,
    [],
    {}
  )
__send__(:define_generated_method,
    :log_finish,
    :igLogFinish,
    [],
    {}
  )
__send__(:define_generated_method,
    :log_to_clipboard,
    :igLogToClipboard,
    [["auto_open_depth", "int"]],
    {"auto_open_depth" => -1}
  )
__send__(:define_generated_method,
    :log_to_file,
    :igLogToFile,
    [["auto_open_depth", "int"], ["filename", "const char*"]],
    {"auto_open_depth" => -1, "filename" => nil}
  )
__send__(:define_generated_method,
    :log_to_tty,
    :igLogToTTY,
    [["auto_open_depth", "int"]],
    {"auto_open_depth" => -1}
  )
__send__(:define_generated_method,
    :mem_alloc,
    :igMemAlloc,
    [["size", "size_t"]],
    {}
  )
__send__(:define_generated_method,
    :mem_free,
    :igMemFree,
    [["ptr", "void*"]],
    {}
  )
__send__(:define_generated_method,
    :next_column,
    :igNextColumn,
    [],
    {}
  )
__send__(:define_generated_method,
    :open_popup,
    :igOpenPopup_Str,
    [["str_id", "const char*"], ["popup_flags", "ImGuiPopupFlags"]],
    {"popup_flags" => 0}
  )
__send__(:define_generated_method,
    :open_popup_on_item_click,
    :igOpenPopupOnItemClick,
    [["str_id", "const char*"], ["popup_flags", "ImGuiPopupFlags"]],
    {"popup_flags" => 1, "str_id" => nil}
  )
__send__(:define_generated_method,
    :plot_histogram,
    :igPlotHistogram_FloatPtr,
    [["label", "const char*"], ["values", "const float*"], ["values_count", "int"], ["values_offset", "int"], ["overlay_text", "const char*"], ["scale_min", "float"], ["scale_max", "float"], ["graph_size", "ImVec2"], ["stride", "int"]],
    {"graph_size" => [0, 0], "overlay_text" => nil, "scale_max" => 1.7976931348623157e+308, "scale_min" => 1.7976931348623157e+308, "values_offset" => 0}
  )
__send__(:define_generated_method,
    :plot_lines,
    :igPlotLines_FloatPtr,
    [["label", "const char*"], ["values", "const float*"], ["values_count", "int"], ["values_offset", "int"], ["overlay_text", "const char*"], ["scale_min", "float"], ["scale_max", "float"], ["graph_size", "ImVec2"], ["stride", "int"]],
    {"graph_size" => [0, 0], "overlay_text" => nil, "scale_max" => 1.7976931348623157e+308, "scale_min" => 1.7976931348623157e+308, "values_offset" => 0}
  )
__send__(:define_generated_method,
    :pop_clip_rect,
    :igPopClipRect,
    [],
    {}
  )
__send__(:define_generated_method,
    :pop_font,
    :igPopFont,
    [],
    {}
  )
__send__(:define_generated_method,
    :pop_id,
    :igPopID,
    [],
    {}
  )
__send__(:define_generated_method,
    :pop_item_flag,
    :igPopItemFlag,
    [],
    {}
  )
__send__(:define_generated_method,
    :pop_item_width,
    :igPopItemWidth,
    [],
    {}
  )
__send__(:define_generated_method,
    :pop_style_color,
    :igPopStyleColor,
    [["count", "int"]],
    {"count" => 1}
  )
__send__(:define_generated_method,
    :pop_style_var,
    :igPopStyleVar,
    [["count", "int"]],
    {"count" => 1}
  )
__send__(:define_generated_method,
    :pop_text_wrap_pos,
    :igPopTextWrapPos,
    [],
    {}
  )
__send__(:define_generated_method,
    :push_clip_rect,
    :igPushClipRect,
    [["clip_rect_min", "const ImVec2"], ["clip_rect_max", "const ImVec2"], ["intersect_with_current_clip_rect", "bool"]],
    {}
  )
__send__(:define_generated_method,
    :push_font,
    :igPushFont,
    [["font", "ImFont*"]],
    {}
  )
__send__(:define_generated_method,
    :push_id,
    :igPushID_Str,
    [["str_id", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :push_item_flag,
    :igPushItemFlag,
    [["option", "ImGuiItemFlags"], ["enabled", "bool"]],
    {}
  )
__send__(:define_generated_method,
    :push_item_width,
    :igPushItemWidth,
    [["item_width", "float"]],
    {}
  )
__send__(:define_generated_method,
    :push_style_color,
    :igPushStyleColor_U32,
    [["idx", "ImGuiCol"], ["col", "ImU32"]],
    {}
  )
__send__(:define_generated_method,
    :push_style_var,
    :igPushStyleVar_Float,
    [["idx", "ImGuiStyleVar"], ["val", "float"]],
    {}
  )
__send__(:define_generated_method,
    :push_style_var_x,
    :igPushStyleVarX,
    [["idx", "ImGuiStyleVar"], ["val_x", "float"]],
    {}
  )
__send__(:define_generated_method,
    :push_style_var_y,
    :igPushStyleVarY,
    [["idx", "ImGuiStyleVar"], ["val_y", "float"]],
    {}
  )
__send__(:define_generated_method,
    :push_text_wrap_pos,
    :igPushTextWrapPos,
    [["wrap_local_pos_x", "float"]],
    {"wrap_local_pos_x" => 0.0}
  )
__send__(:define_generated_method,
    :render_platform_windows_default,
    :igRenderPlatformWindowsDefault,
    [["platform_render_arg", "void*"], ["renderer_render_arg", "void*"]],
    {"platform_render_arg" => nil, "renderer_render_arg" => nil}
  )
__send__(:define_generated_method,
    :reset_mouse_drag_delta,
    :igResetMouseDragDelta,
    [["button", "ImGuiMouseButton"]],
    {"button" => 0}
  )
__send__(:define_generated_method,
    :save_ini_settings_to_disk,
    :igSaveIniSettingsToDisk,
    [["ini_filename", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :save_ini_settings_to_memory,
    :igSaveIniSettingsToMemory,
    [["out_ini_size", "size_t*"]],
    {"out_ini_size" => nil}
  )
__send__(:define_generated_method,
    :separator_text,
    :igSeparatorText,
    [["label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :set_allocator_functions,
    :igSetAllocatorFunctions,
    [["alloc_func", "ImGuiMemAllocFunc"], ["free_func", "ImGuiMemFreeFunc"], ["user_data", "void*"]],
    {"user_data" => nil}
  )
__send__(:define_generated_method,
    :set_clipboard_text,
    :igSetClipboardText,
    [["text", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :set_color_edit_options,
    :igSetColorEditOptions,
    [["flags", "ImGuiColorEditFlags"]],
    {}
  )
__send__(:define_generated_method,
    :set_column_offset,
    :igSetColumnOffset,
    [["column_index", "int"], ["offset_x", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_column_width,
    :igSetColumnWidth,
    [["column_index", "int"], ["width", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_cursor_pos,
    :igSetCursorPos,
    [["local_pos", "const ImVec2"]],
    {}
  )
__send__(:define_generated_method,
    :set_cursor_pos_x,
    :igSetCursorPosX,
    [["local_x", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_cursor_pos_y,
    :igSetCursorPosY,
    [["local_y", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_cursor_screen_pos,
    :igSetCursorScreenPos,
    [["pos", "const ImVec2"]],
    {}
  )
__send__(:define_generated_method,
    :set_drag_drop_payload,
    :igSetDragDropPayload,
    [["type", "const char*"], ["data", "const void*"], ["sz", "size_t"], ["cond", "ImGuiCond"]],
    {"cond" => 0}
  )
__send__(:define_generated_method,
    :set_item_default_focus,
    :igSetItemDefaultFocus,
    [],
    {}
  )
__send__(:define_generated_method,
    :set_item_key_owner,
    :igSetItemKeyOwner_Nil,
    [["key", "ImGuiKey"]],
    {}
  )
__send__(:define_generated_method,
    :set_keyboard_focus_here,
    :igSetKeyboardFocusHere,
    [["offset", "int"]],
    {"offset" => 0}
  )
__send__(:define_generated_method,
    :set_mouse_cursor,
    :igSetMouseCursor,
    [["cursor_type", "ImGuiMouseCursor"]],
    {}
  )
__send__(:define_generated_method,
    :set_nav_cursor_visible,
    :igSetNavCursorVisible,
    [["visible", "bool"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_frame_want_capture_keyboard,
    :igSetNextFrameWantCaptureKeyboard,
    [["want_capture_keyboard", "bool"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_frame_want_capture_mouse,
    :igSetNextFrameWantCaptureMouse,
    [["want_capture_mouse", "bool"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_item_allow_overlap,
    :igSetNextItemAllowOverlap,
    [],
    {}
  )
__send__(:define_generated_method,
    :set_next_item_open,
    :igSetNextItemOpen,
    [["is_open", "bool"], ["cond", "ImGuiCond"]],
    {"cond" => 0}
  )
__send__(:define_generated_method,
    :set_next_item_selection_user_data,
    :igSetNextItemSelectionUserData,
    [["selection_user_data", "ImGuiSelectionUserData"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_item_shortcut,
    :igSetNextItemShortcut,
    [["key_chord", "ImGuiKeyChord"], ["flags", "ImGuiInputFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :set_next_item_storage_id,
    :igSetNextItemStorageID,
    [["storage_id", "ImGuiID"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_item_width,
    :igSetNextItemWidth,
    [["item_width", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_window_bg_alpha,
    :igSetNextWindowBgAlpha,
    [["alpha", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_window_class,
    :igSetNextWindowClass,
    [["window_class", "const ImGuiWindowClass*"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_window_content_size,
    :igSetNextWindowContentSize,
    [["size", "const ImVec2"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_window_dock_id,
    :igSetNextWindowDockID,
    [["dock_id", "ImGuiID"], ["cond", "ImGuiCond"]],
    {"cond" => 0}
  )
__send__(:define_generated_method,
    :set_next_window_scroll,
    :igSetNextWindowScroll,
    [["scroll", "const ImVec2"]],
    {}
  )
__send__(:define_generated_method,
    :set_next_window_size_constraints,
    :igSetNextWindowSizeConstraints,
    [["size_min", "const ImVec2"], ["size_max", "const ImVec2"], ["custom_callback", "ImGuiSizeCallback"], ["custom_callback_data", "void*"]],
    {"custom_callback" => nil, "custom_callback_data" => nil}
  )
__send__(:define_generated_method,
    :set_next_window_viewport,
    :igSetNextWindowViewport,
    [["viewport_id", "ImGuiID"]],
    {}
  )
__send__(:define_generated_method,
    :set_scroll_from_pos_x,
    :igSetScrollFromPosX_Float,
    [["local_x", "float"], ["center_x_ratio", "float"]],
    {"center_x_ratio" => 0.5}
  )
__send__(:define_generated_method,
    :set_scroll_from_pos_y,
    :igSetScrollFromPosY_Float,
    [["local_y", "float"], ["center_y_ratio", "float"]],
    {"center_y_ratio" => 0.5}
  )
__send__(:define_generated_method,
    :set_scroll_here_x,
    :igSetScrollHereX,
    [["center_x_ratio", "float"]],
    {"center_x_ratio" => 0.5}
  )
__send__(:define_generated_method,
    :set_scroll_here_y,
    :igSetScrollHereY,
    [["center_y_ratio", "float"]],
    {"center_y_ratio" => 0.5}
  )
__send__(:define_generated_method,
    :set_scroll_x,
    :igSetScrollX_Float,
    [["scroll_x", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_scroll_y,
    :igSetScrollY_Float,
    [["scroll_y", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_state_storage,
    :igSetStateStorage,
    [["storage", "ImGuiStorage*"]],
    {}
  )
__send__(:define_generated_method,
    :set_tab_item_closed,
    :igSetTabItemClosed,
    [["tab_or_docked_window_label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :set_window_collapsed,
    :igSetWindowCollapsed_Bool,
    [["collapsed", "bool"], ["cond", "ImGuiCond"]],
    {"cond" => 0}
  )
__send__(:define_generated_method,
    :set_window_focus,
    :igSetWindowFocus_Nil,
    [],
    {}
  )
__send__(:define_generated_method,
    :set_window_font_scale,
    :igSetWindowFontScale,
    [["scale", "float"]],
    {}
  )
__send__(:define_generated_method,
    :set_window_pos,
    :igSetWindowPos_Str,
    [["name", "const char*"], ["pos", "const ImVec2"], ["cond", "ImGuiCond"]],
    {"cond" => 0}
  )
__send__(:define_generated_method,
    :set_window_size,
    :igSetWindowSize_Str,
    [["name", "const char*"], ["size", "const ImVec2"], ["cond", "ImGuiCond"]],
    {"cond" => 0}
  )
__send__(:define_generated_method,
    :shortcut,
    :igShortcut_Nil,
    [["key_chord", "ImGuiKeyChord"], ["flags", "ImGuiInputFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :show_about_window,
    :igShowAboutWindow,
    [["p_open", "bool*"]],
    {"p_open" => nil}
  )
__send__(:define_generated_method,
    :show_debug_log_window,
    :igShowDebugLogWindow,
    [["p_open", "bool*"]],
    {"p_open" => nil}
  )
__send__(:define_generated_method,
    :show_demo_window,
    :igShowDemoWindow,
    [["p_open", "bool*"]],
    {"p_open" => nil}
  )
__send__(:define_generated_method,
    :show_font_selector,
    :igShowFontSelector,
    [["label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :show_id_stack_tool_window,
    :igShowIDStackToolWindow,
    [["p_open", "bool*"]],
    {"p_open" => nil}
  )
__send__(:define_generated_method,
    :show_metrics_window,
    :igShowMetricsWindow,
    [["p_open", "bool*"]],
    {"p_open" => nil}
  )
__send__(:define_generated_method,
    :show_style_editor,
    :igShowStyleEditor,
    [["ref", "ImGuiStyle*"]],
    {"ref" => nil}
  )
__send__(:define_generated_method,
    :show_style_selector,
    :igShowStyleSelector,
    [["label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :show_user_guide,
    :igShowUserGuide,
    [],
    {}
  )
__send__(:define_generated_method,
    :slider_angle,
    :igSliderAngle,
    [["label", "const char*"], ["v_rad", "float*"], ["v_degrees_min", "float"], ["v_degrees_max", "float"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%.0f deg", "v_degrees_min" => -360.0}
  )
__send__(:define_generated_method,
    :slider_int2,
    :igSliderInt2,
    [["label", "const char*"], ["v", "int[2]"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d"}
  )
__send__(:define_generated_method,
    :slider_int3,
    :igSliderInt3,
    [["label", "const char*"], ["v", "int[3]"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d"}
  )
__send__(:define_generated_method,
    :slider_int4,
    :igSliderInt4,
    [["label", "const char*"], ["v", "int[4]"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d"}
  )
__send__(:define_generated_method,
    :slider_scalar,
    :igSliderScalar,
    [["label", "const char*"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["p_min", "const void*"], ["p_max", "const void*"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => nil}
  )
__send__(:define_generated_method,
    :slider_scalar_n,
    :igSliderScalarN,
    [["label", "const char*"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["components", "int"], ["p_min", "const void*"], ["p_max", "const void*"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => nil}
  )
__send__(:define_generated_method,
    :style_colors_classic,
    :igStyleColorsClassic,
    [["dst", "ImGuiStyle*"]],
    {"dst" => nil}
  )
__send__(:define_generated_method,
    :style_colors_dark,
    :igStyleColorsDark,
    [["dst", "ImGuiStyle*"]],
    {"dst" => nil}
  )
__send__(:define_generated_method,
    :style_colors_light,
    :igStyleColorsLight,
    [["dst", "ImGuiStyle*"]],
    {"dst" => nil}
  )
__send__(:define_generated_method,
    :tab_item_button,
    :igTabItemButton,
    [["label", "const char*"], ["flags", "ImGuiTabItemFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :table_angled_headers_row,
    :igTableAngledHeadersRow,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_get_column_count,
    :igTableGetColumnCount,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_get_column_flags,
    :igTableGetColumnFlags,
    [["column_n", "int"]],
    {"column_n" => -1}
  )
__send__(:define_generated_method,
    :table_get_column_index,
    :igTableGetColumnIndex,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_get_column_name,
    :igTableGetColumnName_Int,
    [["column_n", "int"]],
    {"column_n" => -1}
  )
__send__(:define_generated_method,
    :table_get_hovered_column,
    :igTableGetHoveredColumn,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_get_row_index,
    :igTableGetRowIndex,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_get_sort_specs,
    :igTableGetSortSpecs,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_header,
    :igTableHeader,
    [["label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :table_headers_row,
    :igTableHeadersRow,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_next_column,
    :igTableNextColumn,
    [],
    {}
  )
__send__(:define_generated_method,
    :table_next_row,
    :igTableNextRow,
    [["row_flags", "ImGuiTableRowFlags"], ["min_row_height", "float"]],
    {"min_row_height" => 0.0, "row_flags" => 0}
  )
__send__(:define_generated_method,
    :table_set_bg_color,
    :igTableSetBgColor,
    [["target", "ImGuiTableBgTarget"], ["color", "ImU32"], ["column_n", "int"]],
    {"column_n" => -1}
  )
__send__(:define_generated_method,
    :table_set_column_enabled,
    :igTableSetColumnEnabled,
    [["column_n", "int"], ["v", "bool"]],
    {}
  )
__send__(:define_generated_method,
    :table_set_column_index,
    :igTableSetColumnIndex,
    [["column_n", "int"]],
    {}
  )
__send__(:define_generated_method,
    :table_setup_column,
    :igTableSetupColumn,
    [["label", "const char*"], ["flags", "ImGuiTableColumnFlags"], ["init_width_or_weight", "float"], ["user_id", "ImGuiID"]],
    {"flags" => 0, "init_width_or_weight" => 0.0, "user_id" => 0}
  )
__send__(:define_generated_method,
    :table_setup_scroll_freeze,
    :igTableSetupScrollFreeze,
    [["cols", "int"], ["rows", "int"]],
    {}
  )
__send__(:define_generated_method,
    :text_link,
    :igTextLink,
    [["label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :text_link_open_url,
    :igTextLinkOpenURL,
    [["label", "const char*"], ["url", "const char*"]],
    {"url" => nil}
  )
__send__(:define_generated_method,
    :text_unformatted,
    :igTextUnformatted,
    [["text", "const char*"], ["text_end", "const char*"]],
    {"text_end" => nil}
  )
__send__(:define_generated_method,
    :tree_node,
    :igTreeNode_Str,
    [["label", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :tree_node_ex,
    :igTreeNodeEx_Str,
    [["label", "const char*"], ["flags", "ImGuiTreeNodeFlags"]],
    {"flags" => 0}
  )
__send__(:define_generated_method,
    :tree_pop,
    :igTreePop,
    [],
    {}
  )
__send__(:define_generated_method,
    :tree_push,
    :igTreePush_Str,
    [["str_id", "const char*"]],
    {}
  )
__send__(:define_generated_method,
    :update_platform_windows,
    :igUpdatePlatformWindows,
    [],
    {}
  )
__send__(:define_generated_method,
    :v_slider_float,
    :igVSliderFloat,
    [["label", "const char*"], ["size", "const ImVec2"], ["v", "float*"], ["v_min", "float"], ["v_max", "float"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%.3f"}
  )
__send__(:define_generated_method,
    :v_slider_int,
    :igVSliderInt,
    [["label", "const char*"], ["size", "const ImVec2"], ["v", "int*"], ["v_min", "int"], ["v_max", "int"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => "%d"}
  )
__send__(:define_generated_method,
    :v_slider_scalar,
    :igVSliderScalar,
    [["label", "const char*"], ["size", "const ImVec2"], ["data_type", "ImGuiDataType"], ["p_data", "void*"], ["p_min", "const void*"], ["p_max", "const void*"], ["format", "const char*"], ["flags", "ImGuiSliderFlags"]],
    {"flags" => 0, "format" => nil}
  )
__send__(:define_generated_method,
    :value,
    :igValue_Bool,
    [["prefix", "const char*"], ["b", "bool"]],
    {}
  )
end
