# frozen_string_literal: true

require "json"
require "yaml"

module ImGuiRuby
  module Generator
    class ApiEmitter
      UNPARSED = Object.new.freeze
      HAND_WRITTEN = %w[
        CreateContext DestroyContext GetCurrentContext SetCurrentContext GetIO GetStyle GetDrawData
        NewFrame EndFrame Render GetVersion Text TextColored Button SmallButton InvisibleButton
        Checkbox RadioButton SliderFloat SliderFloat2 SliderFloat3 SliderFloat4 SliderInt
        DragFloat DragInt InputFloat InputInt InputText ColorEdit3 ColorEdit4 Selectable MenuItem
        ProgressBar Separator Spacing NewLine SameLine Dummy Indent Unindent SetNextWindowPos
        SetNextWindowSize SetNextWindowCollapsed SetNextWindowFocus
      ].freeze

      GENERATED_HEADER = <<~RUBY.freeze
        # frozen_string_literal: true

        # This file is generated by `rake generate`. Do not edit it manually.
      RUBY

      def initialize(metadata_dir:, output_path:, overrides_path:)
        @definitions = JSON.parse(File.read(File.join(metadata_dir, "definitions.json")))
        types = JSON.parse(File.read(File.join(metadata_dir, "structs_and_enums.json")))
        @enum_values = types.fetch("enums").values.flatten.to_h do |value|
          [value.fetch("name"), value.fetch("calc_value")]
        end
        @output_path = output_path
        @overrides = YAML.safe_load_file(overrides_path, aliases: false) || {}
      end

      def generate!
        methods = selected_definitions.map do |definition|
          emit_method(definition)
        end
        File.write(@output_path, <<~RUBY)
          #{GENERATED_HEADER}

          module ImGui
          #{methods.join("\n")}
          end
        RUBY
      end

      private

      def selected_definitions
        candidates = @definitions.values.flatten.select do |definition|
          public_definition?(definition)
        end
        candidates.group_by { |definition| snake_case(definition.fetch("funcname")) }
          .values
          .map { |overloads| overloads.min_by { |definition| overload_score(definition) } }
          .sort_by { |definition| snake_case(definition.fetch("funcname")) }
      end

      def public_definition?(definition)
        return false unless definition.fetch("location", "").start_with?("imgui:")
        return false unless definition.fetch("stname", "").empty?
        return false if definition["isvararg"] || definition["skipped"]
        return false if Array(definition["argsT"]).any? { |argument| argument.fetch("type") == "va_list" }
        return false if HAND_WRITTEN.include?(definition["funcname"])
        return false if definition.fetch("funcname").start_with?("Begin", "End")

        !Array(@overrides["skip"]).include?(native_name(definition))
      end

      def overload_score(definition)
        name = native_name(definition)
        base = definition.fetch("cimguiname")
        preferred_suffix = name.end_with?("_Nil", "_Str", "_Bool") ? 0 : 1
        [name == base ? 0 : 1, preferred_suffix, Array(definition["argsT"]).length]
      end

      def emit_method(definition)
        ruby_name = snake_case(definition.fetch("funcname"))
        arguments = Array(definition["argsT"]).map do |argument|
          [argument.fetch("name"), argument.fetch("type")]
        end
        defaults = definition.fetch("defaults", {}).filter_map do |name, value|
          parsed = ruby_default(value)
          [name, parsed] unless parsed.equal?(UNPARSED)
        end.to_h

        <<~RUBY.chomp
            __send__(:define_generated_method,
                :#{ruby_name},
                :#{renamed_native_name(definition)},
                #{arguments.inspect},
                #{defaults.inspect}
              )
        RUBY
      end

      def renamed_native_name(definition)
        name = native_name(definition)
        @overrides.fetch("rename", {}).fetch(name, name)
      end

      def native_name(definition)
        definition["ov_cimguiname"] || definition.fetch("cimguiname")
      end

      def ruby_default(value)
        source = value.to_s.strip
        return nil if source.match?(/\A(?:NULL|nullptr|\(\(void\*\)0\))\z/)
        return true if source == "true"
        return false if source == "false"
        return source[1...-1] if source.match?(/\A".*"\z/)

        vector = source.match(/\AImVec([24])\((.*)\)\z/)
        if vector
          values = vector[2].split(",").map { |item| numeric_default(item.strip) }
          return UNPARSED if values.any? { |item| item.equal?(UNPARSED) }

          return values
        end

        numeric_default(source)
      end

      def numeric_default(source)
        normalized = source.delete_suffix("f")
        return Integer(normalized, 0) if normalized.match?(/\A-?(?:0x[\da-f]+|\d+)\z/i)
        return Float(normalized) if normalized.match?(/\A-?(?:\d+\.\d*|\.\d+)(?:e[+-]?\d+)?\z/i)
        return Float::MAX if source == "FLT_MAX"
        return -Float::MIN if source == "-FLT_MIN"
        return @enum_values.fetch(source) if @enum_values.key?(source)

        enum_parts = source.split("|").map(&:strip)
        if enum_parts.length > 1 && enum_parts.all? { |part| @enum_values.key?(part) }
          return enum_parts.reduce(0) { |value, part| value | @enum_values.fetch(part) }
        end

        UNPARSED
      end

      def snake_case(name)
        name.gsub(/([A-Z]+)([A-Z][a-z])/, '\\1_\\2')
          .gsub(/([a-z\d])([A-Z])/, '\\1_\\2')
          .downcase
      end
    end
  end
end
