# frozen_string_literal: true

require "json"
require "fileutils"
require "yaml"

require_relative "type_mapper"

module ImGuiRuby
  module Generator
    class Emitter
      GENERATED_HEADER = <<~RUBY.freeze
        # frozen_string_literal: true

        # This file is generated by `rake generate`. Do not edit it manually.
      RUBY

      def initialize(metadata_dir:, output_dir:, overrides_path:)
        @metadata_dir = metadata_dir
        @output_dir = output_dir
        @overrides = YAML.safe_load_file(overrides_path, aliases: false) || {}
        @definitions = read_json("definitions.json")
        @types = read_json("structs_and_enums.json")
        @typedefs = read_json("typedefs_dict.json")
        @structs = @types.fetch("structs")
        @enums = @types.fetch("enums")
        @mapper = TypeMapper.new(
          typedefs: @typedefs,
          structs: @structs,
          enum_types: @enums.keys.map { |name| name.delete_suffix("_") }
        )
      end

      def generate!
        FileUtils.mkdir_p(@output_dir)
        write("typedefs.rb", emit_typedefs)
        write("enums.rb", emit_enums)
        write("structs.rb", emit_structs)
        write("functions.rb", emit_functions)
      end

      private

      def emit_typedefs
        declarations = @typedefs.filter_map do |name, c_type|
          next if @structs.key?(name) || c_type.start_with?("struct ")

          "    typedef #{@mapper.typedef_type(c_type)}, :#{name}"
        end

        wrap_native(declarations.join("\n"))
      end

      def emit_enums
        native_constants = []
        public_modules = []

        @enums.sort.each do |enum_name, values|
          values.each do |value|
            native_constants << "    #{value.fetch("name")} = #{value.fetch("calc_value")}"
          end

          public_name = public_enum_name(enum_name)
          prefix = enum_name.end_with?("_") ? enum_name : "#{enum_name}_"
          constants = values.map do |value|
            name = ruby_constant_name(value.fetch("name").delete_prefix(prefix))
            "    #{name} = Native::#{value.fetch("name")}"
          end
          public_modules << "  module #{public_name}\n#{constants.join("\n")}\n  end"
        end

        <<~RUBY
          #{GENERATED_HEADER}

          module ImGui
            module Native
          #{native_constants.join("\n")}
            end

          #{public_modules.join("\n\n")}
          end
        RUBY
      end

      def emit_structs
        declarations = @structs.keys.sort.map { |name| "    class #{name} < FFI::Struct; end" }
        layouts = ordered_structs.filter_map do |name, members|
          fields = struct_fields(members)
          next if fields.empty?

          formatted = fields.each_slice(2).map { |field, type| "        #{field}, #{type}" }.join(",\n")
          "    #{name}.layout(\n#{formatted}\n    )"
        end

        wrap_native((declarations + [""] + layouts).join("\n"))
      end

      def emit_functions
        skipped = Array(@overrides["skip"])
        renames = @overrides.fetch("rename", {})
        declarations = @definitions.values.flatten.filter_map do |definition|
          name = definition["ov_cimguiname"] || definition.fetch("cimguiname")
          next if definition["skipped"] || definition["isvararg"] || skipped.include?(name)

          arguments = Array(definition["argsT"]).map do |argument|
            @mapper.ffi_type(argument.fetch("type"))
          end
          return_type = definition.fetch("ret") do
            definition["constructor"] ? "#{definition.fetch("stname")}*" : "void"
          end
          result = @mapper.ffi_type(return_type)
          ruby_name = renames.fetch(name, name)
          if ruby_name == name
            "    attach_function :#{name}, [#{arguments.join(", ")}], #{result}"
          else
            "    attach_function :#{ruby_name}, :#{name}, [#{arguments.join(", ")}], #{result}"
          end
        end

        wrap_native(declarations.sort.join("\n"))
      end

      def public_enum_name(enum_name)
        enum_name.delete_suffix("_").sub(/\AImGui/, "").sub(/\AIm/, "")
      end

      def ruby_constant_name(name)
        clean_name = name.sub(/\A_+/, "").gsub(/[^a-zA-Z0-9_]/, "_")
        clean_name = "Num#{clean_name}" if clean_name.match?(/\A\d/)
        clean_name.empty? ? "Value" : clean_name
      end

      def struct_fields(members)
        anonymous_index = 0
        previous_bitfield_type = nil

        members.flat_map do |member|
          if member["bitfield"]
            type = @mapper.ffi_type(member.fetch("type"))
            next [] if type == previous_bitfield_type

            previous_bitfield_type = type
            anonymous_index += 1
            next ["_bitfield_#{anonymous_index}".inspect, type]
          end

          previous_bitfield_type = nil
          name = member.fetch("name")
          if name.empty?
            anonymous_index += 1
            name = "_anonymous_#{anonymous_index}"
          end
          [name.inspect, @mapper.ffi_type(member.fetch("type"), member: member)]
        end
      end

      def ordered_structs
        ordered = []
        state = {}
        visit = lambda do |name|
          return if state[name] == :done
          return if state[name] == :visiting

          state[name] = :visiting
          @structs.fetch(name).each do |member|
            dependency = by_value_struct_name(member.fetch("type"))
            visit.call(dependency) if dependency
          end
          state[name] = :done
          ordered << [name, @structs.fetch(name)]
        end
        @structs.keys.sort.each { |name| visit.call(name) }
        ordered
      end

      def by_value_struct_name(c_type)
        type = c_type.gsub(/\bconst\b|\bstruct\b/, "").gsub(/\[[^\]]+\]/, "").strip
        return if type.include?("*") || type.include?("&")

        @structs.key?(type) ? type : nil
      end

      def wrap_native(body)
        <<~RUBY
          #{GENERATED_HEADER}

          module ImGui
            module Native
          #{body}
            end
          end
        RUBY
      end

      def read_json(filename)
        JSON.parse(File.read(File.join(@metadata_dir, filename)))
      end

      def write(filename, content)
        File.write(File.join(@output_dir, filename), content)
      end
    end
  end
end
