# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    ImAxis_X1 = 0
    ImAxis_X2 = 1
    ImAxis_X3 = 2
    ImAxis_Y1 = 3
    ImAxis_Y2 = 4
    ImAxis_Y3 = 5
    ImAxis_COUNT = 6
    ImPlotAxisFlags_None = 0
    ImPlotAxisFlags_NoLabel = 1
    ImPlotAxisFlags_NoGridLines = 2
    ImPlotAxisFlags_NoTickMarks = 4
    ImPlotAxisFlags_NoTickLabels = 8
    ImPlotAxisFlags_NoInitialFit = 16
    ImPlotAxisFlags_NoMenus = 32
    ImPlotAxisFlags_NoSideSwitch = 64
    ImPlotAxisFlags_NoHighlight = 128
    ImPlotAxisFlags_Opposite = 256
    ImPlotAxisFlags_Foreground = 512
    ImPlotAxisFlags_Invert = 1024
    ImPlotAxisFlags_AutoFit = 2048
    ImPlotAxisFlags_RangeFit = 4096
    ImPlotAxisFlags_PanStretch = 8192
    ImPlotAxisFlags_LockMin = 16384
    ImPlotAxisFlags_LockMax = 32768
    ImPlotAxisFlags_Lock = 49152
    ImPlotAxisFlags_NoDecorations = 15
    ImPlotAxisFlags_AuxDefault = 258
    ImPlotBarGroupsFlags_None = 0
    ImPlotBarGroupsFlags_Horizontal = 1024
    ImPlotBarGroupsFlags_Stacked = 2048
    ImPlotBarsFlags_None = 0
    ImPlotBarsFlags_Horizontal = 1024
    ImPlotBin_Sqrt = -1
    ImPlotBin_Sturges = -2
    ImPlotBin_Rice = -3
    ImPlotBin_Scott = -4
    ImPlotCol_Line = 0
    ImPlotCol_Fill = 1
    ImPlotCol_MarkerOutline = 2
    ImPlotCol_MarkerFill = 3
    ImPlotCol_ErrorBar = 4
    ImPlotCol_FrameBg = 5
    ImPlotCol_PlotBg = 6
    ImPlotCol_PlotBorder = 7
    ImPlotCol_LegendBg = 8
    ImPlotCol_LegendBorder = 9
    ImPlotCol_LegendText = 10
    ImPlotCol_TitleText = 11
    ImPlotCol_InlayText = 12
    ImPlotCol_AxisText = 13
    ImPlotCol_AxisGrid = 14
    ImPlotCol_AxisTick = 15
    ImPlotCol_AxisBg = 16
    ImPlotCol_AxisBgHovered = 17
    ImPlotCol_AxisBgActive = 18
    ImPlotCol_Selection = 19
    ImPlotCol_Crosshairs = 20
    ImPlotCol_COUNT = 21
    ImPlotColormapScaleFlags_None = 0
    ImPlotColormapScaleFlags_NoLabel = 1
    ImPlotColormapScaleFlags_Opposite = 2
    ImPlotColormapScaleFlags_Invert = 4
    ImPlotColormap_Deep = 0
    ImPlotColormap_Dark = 1
    ImPlotColormap_Pastel = 2
    ImPlotColormap_Paired = 3
    ImPlotColormap_Viridis = 4
    ImPlotColormap_Plasma = 5
    ImPlotColormap_Hot = 6
    ImPlotColormap_Cool = 7
    ImPlotColormap_Pink = 8
    ImPlotColormap_Jet = 9
    ImPlotColormap_Twilight = 10
    ImPlotColormap_RdBu = 11
    ImPlotColormap_BrBG = 12
    ImPlotColormap_PiYG = 13
    ImPlotColormap_Spectral = 14
    ImPlotColormap_Greys = 15
    ImPlotCond_None = 0
    ImPlotCond_Always = 1
    ImPlotCond_Once = 2
    ImPlotDateFmt_None = 0
    ImPlotDateFmt_DayMo = 1
    ImPlotDateFmt_DayMoYr = 2
    ImPlotDateFmt_MoYr = 3
    ImPlotDateFmt_Mo = 4
    ImPlotDateFmt_Yr = 5
    ImPlotDigitalFlags_None = 0
    ImPlotDragToolFlags_None = 0
    ImPlotDragToolFlags_NoCursors = 1
    ImPlotDragToolFlags_NoFit = 2
    ImPlotDragToolFlags_NoInputs = 4
    ImPlotDragToolFlags_Delayed = 8
    ImPlotDummyFlags_None = 0
    ImPlotErrorBarsFlags_None = 0
    ImPlotErrorBarsFlags_Horizontal = 1024
    ImPlotFlags_None = 0
    ImPlotFlags_NoTitle = 1
    ImPlotFlags_NoLegend = 2
    ImPlotFlags_NoMouseText = 4
    ImPlotFlags_NoInputs = 8
    ImPlotFlags_NoMenus = 16
    ImPlotFlags_NoBoxSelect = 32
    ImPlotFlags_NoFrame = 64
    ImPlotFlags_Equal = 128
    ImPlotFlags_Crosshairs = 256
    ImPlotFlags_CanvasOnly = 55
    ImPlotHeatmapFlags_None = 0
    ImPlotHeatmapFlags_ColMajor = 1024
    ImPlotHistogramFlags_None = 0
    ImPlotHistogramFlags_Horizontal = 1024
    ImPlotHistogramFlags_Cumulative = 2048
    ImPlotHistogramFlags_Density = 4096
    ImPlotHistogramFlags_NoOutliers = 8192
    ImPlotHistogramFlags_ColMajor = 16384
    ImPlotImageFlags_None = 0
    ImPlotInfLinesFlags_None = 0
    ImPlotInfLinesFlags_Horizontal = 1024
    ImPlotItemFlags_None = 0
    ImPlotItemFlags_NoLegend = 1
    ImPlotItemFlags_NoFit = 2
    ImPlotLegendFlags_None = 0
    ImPlotLegendFlags_NoButtons = 1
    ImPlotLegendFlags_NoHighlightItem = 2
    ImPlotLegendFlags_NoHighlightAxis = 4
    ImPlotLegendFlags_NoMenus = 8
    ImPlotLegendFlags_Outside = 16
    ImPlotLegendFlags_Horizontal = 32
    ImPlotLegendFlags_Sort = 64
    ImPlotLineFlags_None = 0
    ImPlotLineFlags_Segments = 1024
    ImPlotLineFlags_Loop = 2048
    ImPlotLineFlags_SkipNaN = 4096
    ImPlotLineFlags_NoClip = 8192
    ImPlotLineFlags_Shaded = 16384
    ImPlotLocation_Center = 0
    ImPlotLocation_North = 1
    ImPlotLocation_South = 2
    ImPlotLocation_West = 4
    ImPlotLocation_East = 8
    ImPlotLocation_NorthWest = 5
    ImPlotLocation_NorthEast = 9
    ImPlotLocation_SouthWest = 6
    ImPlotLocation_SouthEast = 10
    ImPlotMarker_None = -1
    ImPlotMarker_Circle = 0
    ImPlotMarker_Square = 1
    ImPlotMarker_Diamond = 2
    ImPlotMarker_Up = 3
    ImPlotMarker_Down = 4
    ImPlotMarker_Left = 5
    ImPlotMarker_Right = 6
    ImPlotMarker_Cross = 7
    ImPlotMarker_Plus = 8
    ImPlotMarker_Asterisk = 9
    ImPlotMarker_COUNT = 10
    ImPlotMouseTextFlags_None = 0
    ImPlotMouseTextFlags_NoAuxAxes = 1
    ImPlotMouseTextFlags_NoFormat = 2
    ImPlotMouseTextFlags_ShowAlways = 4
    ImPlotPieChartFlags_None = 0
    ImPlotPieChartFlags_Normalize = 1024
    ImPlotPieChartFlags_IgnoreHidden = 2048
    ImPlotPieChartFlags_Exploding = 4096
    ImPlotScale_Linear = 0
    ImPlotScale_Time = 1
    ImPlotScale_Log10 = 2
    ImPlotScale_SymLog = 3
    ImPlotScatterFlags_None = 0
    ImPlotScatterFlags_NoClip = 1024
    ImPlotShadedFlags_None = 0
    ImPlotStairsFlags_None = 0
    ImPlotStairsFlags_PreStep = 1024
    ImPlotStairsFlags_Shaded = 2048
    ImPlotStemsFlags_None = 0
    ImPlotStemsFlags_Horizontal = 1024
    ImPlotStyleVar_LineWeight = 0
    ImPlotStyleVar_Marker = 1
    ImPlotStyleVar_MarkerSize = 2
    ImPlotStyleVar_MarkerWeight = 3
    ImPlotStyleVar_FillAlpha = 4
    ImPlotStyleVar_ErrorBarSize = 5
    ImPlotStyleVar_ErrorBarWeight = 6
    ImPlotStyleVar_DigitalBitHeight = 7
    ImPlotStyleVar_DigitalBitGap = 8
    ImPlotStyleVar_PlotBorderSize = 9
    ImPlotStyleVar_MinorAlpha = 10
    ImPlotStyleVar_MajorTickLen = 11
    ImPlotStyleVar_MinorTickLen = 12
    ImPlotStyleVar_MajorTickSize = 13
    ImPlotStyleVar_MinorTickSize = 14
    ImPlotStyleVar_MajorGridSize = 15
    ImPlotStyleVar_MinorGridSize = 16
    ImPlotStyleVar_PlotPadding = 17
    ImPlotStyleVar_LabelPadding = 18
    ImPlotStyleVar_LegendPadding = 19
    ImPlotStyleVar_LegendInnerPadding = 20
    ImPlotStyleVar_LegendSpacing = 21
    ImPlotStyleVar_MousePosPadding = 22
    ImPlotStyleVar_AnnotationPadding = 23
    ImPlotStyleVar_FitPadding = 24
    ImPlotStyleVar_PlotDefaultSize = 25
    ImPlotStyleVar_PlotMinSize = 26
    ImPlotStyleVar_COUNT = 27
    ImPlotSubplotFlags_None = 0
    ImPlotSubplotFlags_NoTitle = 1
    ImPlotSubplotFlags_NoLegend = 2
    ImPlotSubplotFlags_NoMenus = 4
    ImPlotSubplotFlags_NoResize = 8
    ImPlotSubplotFlags_NoAlign = 16
    ImPlotSubplotFlags_ShareItems = 32
    ImPlotSubplotFlags_LinkRows = 64
    ImPlotSubplotFlags_LinkCols = 128
    ImPlotSubplotFlags_LinkAllX = 256
    ImPlotSubplotFlags_LinkAllY = 512
    ImPlotSubplotFlags_ColMajor = 1024
    ImPlotTextFlags_None = 0
    ImPlotTextFlags_Vertical = 1024
    ImPlotTimeFmt_None = 0
    ImPlotTimeFmt_Us = 1
    ImPlotTimeFmt_SUs = 2
    ImPlotTimeFmt_SMs = 3
    ImPlotTimeFmt_S = 4
    ImPlotTimeFmt_MinSMs = 5
    ImPlotTimeFmt_HrMinSMs = 6
    ImPlotTimeFmt_HrMinS = 7
    ImPlotTimeFmt_HrMin = 8
    ImPlotTimeFmt_Hr = 9
    ImPlotTimeUnit_Us = 0
    ImPlotTimeUnit_Ms = 1
    ImPlotTimeUnit_S = 2
    ImPlotTimeUnit_Min = 3
    ImPlotTimeUnit_Hr = 4
    ImPlotTimeUnit_Day = 5
    ImPlotTimeUnit_Mo = 6
    ImPlotTimeUnit_Yr = 7
    ImPlotTimeUnit_COUNT = 8
  end
end

module ImPlot
  module ImAxis
    X1 = ImGui::Native::ImAxis_X1
    X2 = ImGui::Native::ImAxis_X2
    X3 = ImGui::Native::ImAxis_X3
    Y1 = ImGui::Native::ImAxis_Y1
    Y2 = ImGui::Native::ImAxis_Y2
    Y3 = ImGui::Native::ImAxis_Y3
    COUNT = ImGui::Native::ImAxis_COUNT
  end

  module AxisFlags
    None = ImGui::Native::ImPlotAxisFlags_None
    NoLabel = ImGui::Native::ImPlotAxisFlags_NoLabel
    NoGridLines = ImGui::Native::ImPlotAxisFlags_NoGridLines
    NoTickMarks = ImGui::Native::ImPlotAxisFlags_NoTickMarks
    NoTickLabels = ImGui::Native::ImPlotAxisFlags_NoTickLabels
    NoInitialFit = ImGui::Native::ImPlotAxisFlags_NoInitialFit
    NoMenus = ImGui::Native::ImPlotAxisFlags_NoMenus
    NoSideSwitch = ImGui::Native::ImPlotAxisFlags_NoSideSwitch
    NoHighlight = ImGui::Native::ImPlotAxisFlags_NoHighlight
    Opposite = ImGui::Native::ImPlotAxisFlags_Opposite
    Foreground = ImGui::Native::ImPlotAxisFlags_Foreground
    Invert = ImGui::Native::ImPlotAxisFlags_Invert
    AutoFit = ImGui::Native::ImPlotAxisFlags_AutoFit
    RangeFit = ImGui::Native::ImPlotAxisFlags_RangeFit
    PanStretch = ImGui::Native::ImPlotAxisFlags_PanStretch
    LockMin = ImGui::Native::ImPlotAxisFlags_LockMin
    LockMax = ImGui::Native::ImPlotAxisFlags_LockMax
    Lock = ImGui::Native::ImPlotAxisFlags_Lock
    NoDecorations = ImGui::Native::ImPlotAxisFlags_NoDecorations
    AuxDefault = ImGui::Native::ImPlotAxisFlags_AuxDefault
  end

  module BarGroupsFlags
    None = ImGui::Native::ImPlotBarGroupsFlags_None
    Horizontal = ImGui::Native::ImPlotBarGroupsFlags_Horizontal
    Stacked = ImGui::Native::ImPlotBarGroupsFlags_Stacked
  end

  module BarsFlags
    None = ImGui::Native::ImPlotBarsFlags_None
    Horizontal = ImGui::Native::ImPlotBarsFlags_Horizontal
  end

  module Bin
    Sqrt = ImGui::Native::ImPlotBin_Sqrt
    Sturges = ImGui::Native::ImPlotBin_Sturges
    Rice = ImGui::Native::ImPlotBin_Rice
    Scott = ImGui::Native::ImPlotBin_Scott
  end

  module Col
    Line = ImGui::Native::ImPlotCol_Line
    Fill = ImGui::Native::ImPlotCol_Fill
    MarkerOutline = ImGui::Native::ImPlotCol_MarkerOutline
    MarkerFill = ImGui::Native::ImPlotCol_MarkerFill
    ErrorBar = ImGui::Native::ImPlotCol_ErrorBar
    FrameBg = ImGui::Native::ImPlotCol_FrameBg
    PlotBg = ImGui::Native::ImPlotCol_PlotBg
    PlotBorder = ImGui::Native::ImPlotCol_PlotBorder
    LegendBg = ImGui::Native::ImPlotCol_LegendBg
    LegendBorder = ImGui::Native::ImPlotCol_LegendBorder
    LegendText = ImGui::Native::ImPlotCol_LegendText
    TitleText = ImGui::Native::ImPlotCol_TitleText
    InlayText = ImGui::Native::ImPlotCol_InlayText
    AxisText = ImGui::Native::ImPlotCol_AxisText
    AxisGrid = ImGui::Native::ImPlotCol_AxisGrid
    AxisTick = ImGui::Native::ImPlotCol_AxisTick
    AxisBg = ImGui::Native::ImPlotCol_AxisBg
    AxisBgHovered = ImGui::Native::ImPlotCol_AxisBgHovered
    AxisBgActive = ImGui::Native::ImPlotCol_AxisBgActive
    Selection = ImGui::Native::ImPlotCol_Selection
    Crosshairs = ImGui::Native::ImPlotCol_Crosshairs
    COUNT = ImGui::Native::ImPlotCol_COUNT
  end

  module ColormapScaleFlags
    None = ImGui::Native::ImPlotColormapScaleFlags_None
    NoLabel = ImGui::Native::ImPlotColormapScaleFlags_NoLabel
    Opposite = ImGui::Native::ImPlotColormapScaleFlags_Opposite
    Invert = ImGui::Native::ImPlotColormapScaleFlags_Invert
  end

  module Colormap
    Deep = ImGui::Native::ImPlotColormap_Deep
    Dark = ImGui::Native::ImPlotColormap_Dark
    Pastel = ImGui::Native::ImPlotColormap_Pastel
    Paired = ImGui::Native::ImPlotColormap_Paired
    Viridis = ImGui::Native::ImPlotColormap_Viridis
    Plasma = ImGui::Native::ImPlotColormap_Plasma
    Hot = ImGui::Native::ImPlotColormap_Hot
    Cool = ImGui::Native::ImPlotColormap_Cool
    Pink = ImGui::Native::ImPlotColormap_Pink
    Jet = ImGui::Native::ImPlotColormap_Jet
    Twilight = ImGui::Native::ImPlotColormap_Twilight
    RdBu = ImGui::Native::ImPlotColormap_RdBu
    BrBG = ImGui::Native::ImPlotColormap_BrBG
    PiYG = ImGui::Native::ImPlotColormap_PiYG
    Spectral = ImGui::Native::ImPlotColormap_Spectral
    Greys = ImGui::Native::ImPlotColormap_Greys
  end

  module Cond
    None = ImGui::Native::ImPlotCond_None
    Always = ImGui::Native::ImPlotCond_Always
    Once = ImGui::Native::ImPlotCond_Once
  end

  module DateFmt
    None = ImGui::Native::ImPlotDateFmt_None
    DayMo = ImGui::Native::ImPlotDateFmt_DayMo
    DayMoYr = ImGui::Native::ImPlotDateFmt_DayMoYr
    MoYr = ImGui::Native::ImPlotDateFmt_MoYr
    Mo = ImGui::Native::ImPlotDateFmt_Mo
    Yr = ImGui::Native::ImPlotDateFmt_Yr
  end

  module DigitalFlags
    None = ImGui::Native::ImPlotDigitalFlags_None
  end

  module DragToolFlags
    None = ImGui::Native::ImPlotDragToolFlags_None
    NoCursors = ImGui::Native::ImPlotDragToolFlags_NoCursors
    NoFit = ImGui::Native::ImPlotDragToolFlags_NoFit
    NoInputs = ImGui::Native::ImPlotDragToolFlags_NoInputs
    Delayed = ImGui::Native::ImPlotDragToolFlags_Delayed
  end

  module DummyFlags
    None = ImGui::Native::ImPlotDummyFlags_None
  end

  module ErrorBarsFlags
    None = ImGui::Native::ImPlotErrorBarsFlags_None
    Horizontal = ImGui::Native::ImPlotErrorBarsFlags_Horizontal
  end

  module Flags
    None = ImGui::Native::ImPlotFlags_None
    NoTitle = ImGui::Native::ImPlotFlags_NoTitle
    NoLegend = ImGui::Native::ImPlotFlags_NoLegend
    NoMouseText = ImGui::Native::ImPlotFlags_NoMouseText
    NoInputs = ImGui::Native::ImPlotFlags_NoInputs
    NoMenus = ImGui::Native::ImPlotFlags_NoMenus
    NoBoxSelect = ImGui::Native::ImPlotFlags_NoBoxSelect
    NoFrame = ImGui::Native::ImPlotFlags_NoFrame
    Equal = ImGui::Native::ImPlotFlags_Equal
    Crosshairs = ImGui::Native::ImPlotFlags_Crosshairs
    CanvasOnly = ImGui::Native::ImPlotFlags_CanvasOnly
  end

  module HeatmapFlags
    None = ImGui::Native::ImPlotHeatmapFlags_None
    ColMajor = ImGui::Native::ImPlotHeatmapFlags_ColMajor
  end

  module HistogramFlags
    None = ImGui::Native::ImPlotHistogramFlags_None
    Horizontal = ImGui::Native::ImPlotHistogramFlags_Horizontal
    Cumulative = ImGui::Native::ImPlotHistogramFlags_Cumulative
    Density = ImGui::Native::ImPlotHistogramFlags_Density
    NoOutliers = ImGui::Native::ImPlotHistogramFlags_NoOutliers
    ColMajor = ImGui::Native::ImPlotHistogramFlags_ColMajor
  end

  module ImageFlags
    None = ImGui::Native::ImPlotImageFlags_None
  end

  module InfLinesFlags
    None = ImGui::Native::ImPlotInfLinesFlags_None
    Horizontal = ImGui::Native::ImPlotInfLinesFlags_Horizontal
  end

  module ItemFlags
    None = ImGui::Native::ImPlotItemFlags_None
    NoLegend = ImGui::Native::ImPlotItemFlags_NoLegend
    NoFit = ImGui::Native::ImPlotItemFlags_NoFit
  end

  module LegendFlags
    None = ImGui::Native::ImPlotLegendFlags_None
    NoButtons = ImGui::Native::ImPlotLegendFlags_NoButtons
    NoHighlightItem = ImGui::Native::ImPlotLegendFlags_NoHighlightItem
    NoHighlightAxis = ImGui::Native::ImPlotLegendFlags_NoHighlightAxis
    NoMenus = ImGui::Native::ImPlotLegendFlags_NoMenus
    Outside = ImGui::Native::ImPlotLegendFlags_Outside
    Horizontal = ImGui::Native::ImPlotLegendFlags_Horizontal
    Sort = ImGui::Native::ImPlotLegendFlags_Sort
  end

  module LineFlags
    None = ImGui::Native::ImPlotLineFlags_None
    Segments = ImGui::Native::ImPlotLineFlags_Segments
    Loop = ImGui::Native::ImPlotLineFlags_Loop
    SkipNaN = ImGui::Native::ImPlotLineFlags_SkipNaN
    NoClip = ImGui::Native::ImPlotLineFlags_NoClip
    Shaded = ImGui::Native::ImPlotLineFlags_Shaded
  end

  module Location
    Center = ImGui::Native::ImPlotLocation_Center
    North = ImGui::Native::ImPlotLocation_North
    South = ImGui::Native::ImPlotLocation_South
    West = ImGui::Native::ImPlotLocation_West
    East = ImGui::Native::ImPlotLocation_East
    NorthWest = ImGui::Native::ImPlotLocation_NorthWest
    NorthEast = ImGui::Native::ImPlotLocation_NorthEast
    SouthWest = ImGui::Native::ImPlotLocation_SouthWest
    SouthEast = ImGui::Native::ImPlotLocation_SouthEast
  end

  module Marker
    None = ImGui::Native::ImPlotMarker_None
    Circle = ImGui::Native::ImPlotMarker_Circle
    Square = ImGui::Native::ImPlotMarker_Square
    Diamond = ImGui::Native::ImPlotMarker_Diamond
    Up = ImGui::Native::ImPlotMarker_Up
    Down = ImGui::Native::ImPlotMarker_Down
    Left = ImGui::Native::ImPlotMarker_Left
    Right = ImGui::Native::ImPlotMarker_Right
    Cross = ImGui::Native::ImPlotMarker_Cross
    Plus = ImGui::Native::ImPlotMarker_Plus
    Asterisk = ImGui::Native::ImPlotMarker_Asterisk
    COUNT = ImGui::Native::ImPlotMarker_COUNT
  end

  module MouseTextFlags
    None = ImGui::Native::ImPlotMouseTextFlags_None
    NoAuxAxes = ImGui::Native::ImPlotMouseTextFlags_NoAuxAxes
    NoFormat = ImGui::Native::ImPlotMouseTextFlags_NoFormat
    ShowAlways = ImGui::Native::ImPlotMouseTextFlags_ShowAlways
  end

  module PieChartFlags
    None = ImGui::Native::ImPlotPieChartFlags_None
    Normalize = ImGui::Native::ImPlotPieChartFlags_Normalize
    IgnoreHidden = ImGui::Native::ImPlotPieChartFlags_IgnoreHidden
    Exploding = ImGui::Native::ImPlotPieChartFlags_Exploding
  end

  module Scale
    Linear = ImGui::Native::ImPlotScale_Linear
    Time = ImGui::Native::ImPlotScale_Time
    Log10 = ImGui::Native::ImPlotScale_Log10
    SymLog = ImGui::Native::ImPlotScale_SymLog
  end

  module ScatterFlags
    None = ImGui::Native::ImPlotScatterFlags_None
    NoClip = ImGui::Native::ImPlotScatterFlags_NoClip
  end

  module ShadedFlags
    None = ImGui::Native::ImPlotShadedFlags_None
  end

  module StairsFlags
    None = ImGui::Native::ImPlotStairsFlags_None
    PreStep = ImGui::Native::ImPlotStairsFlags_PreStep
    Shaded = ImGui::Native::ImPlotStairsFlags_Shaded
  end

  module StemsFlags
    None = ImGui::Native::ImPlotStemsFlags_None
    Horizontal = ImGui::Native::ImPlotStemsFlags_Horizontal
  end

  module StyleVar
    LineWeight = ImGui::Native::ImPlotStyleVar_LineWeight
    Marker = ImGui::Native::ImPlotStyleVar_Marker
    MarkerSize = ImGui::Native::ImPlotStyleVar_MarkerSize
    MarkerWeight = ImGui::Native::ImPlotStyleVar_MarkerWeight
    FillAlpha = ImGui::Native::ImPlotStyleVar_FillAlpha
    ErrorBarSize = ImGui::Native::ImPlotStyleVar_ErrorBarSize
    ErrorBarWeight = ImGui::Native::ImPlotStyleVar_ErrorBarWeight
    DigitalBitHeight = ImGui::Native::ImPlotStyleVar_DigitalBitHeight
    DigitalBitGap = ImGui::Native::ImPlotStyleVar_DigitalBitGap
    PlotBorderSize = ImGui::Native::ImPlotStyleVar_PlotBorderSize
    MinorAlpha = ImGui::Native::ImPlotStyleVar_MinorAlpha
    MajorTickLen = ImGui::Native::ImPlotStyleVar_MajorTickLen
    MinorTickLen = ImGui::Native::ImPlotStyleVar_MinorTickLen
    MajorTickSize = ImGui::Native::ImPlotStyleVar_MajorTickSize
    MinorTickSize = ImGui::Native::ImPlotStyleVar_MinorTickSize
    MajorGridSize = ImGui::Native::ImPlotStyleVar_MajorGridSize
    MinorGridSize = ImGui::Native::ImPlotStyleVar_MinorGridSize
    PlotPadding = ImGui::Native::ImPlotStyleVar_PlotPadding
    LabelPadding = ImGui::Native::ImPlotStyleVar_LabelPadding
    LegendPadding = ImGui::Native::ImPlotStyleVar_LegendPadding
    LegendInnerPadding = ImGui::Native::ImPlotStyleVar_LegendInnerPadding
    LegendSpacing = ImGui::Native::ImPlotStyleVar_LegendSpacing
    MousePosPadding = ImGui::Native::ImPlotStyleVar_MousePosPadding
    AnnotationPadding = ImGui::Native::ImPlotStyleVar_AnnotationPadding
    FitPadding = ImGui::Native::ImPlotStyleVar_FitPadding
    PlotDefaultSize = ImGui::Native::ImPlotStyleVar_PlotDefaultSize
    PlotMinSize = ImGui::Native::ImPlotStyleVar_PlotMinSize
    COUNT = ImGui::Native::ImPlotStyleVar_COUNT
  end

  module SubplotFlags
    None = ImGui::Native::ImPlotSubplotFlags_None
    NoTitle = ImGui::Native::ImPlotSubplotFlags_NoTitle
    NoLegend = ImGui::Native::ImPlotSubplotFlags_NoLegend
    NoMenus = ImGui::Native::ImPlotSubplotFlags_NoMenus
    NoResize = ImGui::Native::ImPlotSubplotFlags_NoResize
    NoAlign = ImGui::Native::ImPlotSubplotFlags_NoAlign
    ShareItems = ImGui::Native::ImPlotSubplotFlags_ShareItems
    LinkRows = ImGui::Native::ImPlotSubplotFlags_LinkRows
    LinkCols = ImGui::Native::ImPlotSubplotFlags_LinkCols
    LinkAllX = ImGui::Native::ImPlotSubplotFlags_LinkAllX
    LinkAllY = ImGui::Native::ImPlotSubplotFlags_LinkAllY
    ColMajor = ImGui::Native::ImPlotSubplotFlags_ColMajor
  end

  module TextFlags
    None = ImGui::Native::ImPlotTextFlags_None
    Vertical = ImGui::Native::ImPlotTextFlags_Vertical
  end

  module TimeFmt
    None = ImGui::Native::ImPlotTimeFmt_None
    Us = ImGui::Native::ImPlotTimeFmt_Us
    SUs = ImGui::Native::ImPlotTimeFmt_SUs
    SMs = ImGui::Native::ImPlotTimeFmt_SMs
    S = ImGui::Native::ImPlotTimeFmt_S
    MinSMs = ImGui::Native::ImPlotTimeFmt_MinSMs
    HrMinSMs = ImGui::Native::ImPlotTimeFmt_HrMinSMs
    HrMinS = ImGui::Native::ImPlotTimeFmt_HrMinS
    HrMin = ImGui::Native::ImPlotTimeFmt_HrMin
    Hr = ImGui::Native::ImPlotTimeFmt_Hr
  end

  module TimeUnit
    Us = ImGui::Native::ImPlotTimeUnit_Us
    Ms = ImGui::Native::ImPlotTimeUnit_Ms
    S = ImGui::Native::ImPlotTimeUnit_S
    Min = ImGui::Native::ImPlotTimeUnit_Min
    Hr = ImGui::Native::ImPlotTimeUnit_Hr
    Day = ImGui::Native::ImPlotTimeUnit_Day
    Mo = ImGui::Native::ImPlotTimeUnit_Mo
    Yr = ImGui::Native::ImPlotTimeUnit_Yr
    COUNT = ImGui::Native::ImPlotTimeUnit_COUNT
  end
end
