# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    attach_function :ImPlotAlignmentData_Begin, [:pointer], :void
    attach_function :ImPlotAlignmentData_End, [:pointer], :void
    attach_function :ImPlotAlignmentData_ImPlotAlignmentData, [], :pointer
    attach_function :ImPlotAlignmentData_Reset, [:pointer], :void
    attach_function :ImPlotAlignmentData_Update, [:pointer, :pointer, :pointer, :pointer, :pointer], :void
    attach_function :ImPlotAlignmentData_destroy, [:pointer], :void
    attach_function :ImPlotAnnotationCollection_AppendV, [:pointer, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, :uint, :uint, :bool, :string, :pointer], :void
    attach_function :ImPlotAnnotationCollection_GetText, [:pointer, :int], :string
    attach_function :ImPlotAnnotationCollection_ImPlotAnnotationCollection, [], :pointer
    attach_function :ImPlotAnnotationCollection_Reset, [:pointer], :void
    attach_function :ImPlotAnnotationCollection_destroy, [:pointer], :void
    attach_function :ImPlotAnnotation_ImPlotAnnotation, [], :pointer
    attach_function :ImPlotAnnotation_destroy, [:pointer], :void
    attach_function :ImPlotAxis_ApplyFit, [:pointer, :float], :void
    attach_function :ImPlotAxis_CanInitFit, [:pointer], :bool
    attach_function :ImPlotAxis_Constrain, [:pointer], :void
    attach_function :ImPlotAxis_ExtendFit, [:pointer, :double], :void
    attach_function :ImPlotAxis_ExtendFitWith, [:pointer, :pointer, :double, :double], :void
    attach_function :ImPlotAxis_GetAspect, [:pointer], :double
    attach_function :ImPlotAxis_HasGridLines, [:pointer], :bool
    attach_function :ImPlotAxis_HasLabel, [:pointer], :bool
    attach_function :ImPlotAxis_HasMenus, [:pointer], :bool
    attach_function :ImPlotAxis_HasTickLabels, [:pointer], :bool
    attach_function :ImPlotAxis_HasTickMarks, [:pointer], :bool
    attach_function :ImPlotAxis_ImPlotAxis, [], :pointer
    attach_function :ImPlotAxis_IsAutoFitting, [:pointer], :bool
    attach_function :ImPlotAxis_IsForeground, [:pointer], :bool
    attach_function :ImPlotAxis_IsInputLocked, [:pointer], :bool
    attach_function :ImPlotAxis_IsInputLockedMax, [:pointer], :bool
    attach_function :ImPlotAxis_IsInputLockedMin, [:pointer], :bool
    attach_function :ImPlotAxis_IsInverted, [:pointer], :bool
    attach_function :ImPlotAxis_IsLocked, [:pointer], :bool
    attach_function :ImPlotAxis_IsLockedMax, [:pointer], :bool
    attach_function :ImPlotAxis_IsLockedMin, [:pointer], :bool
    attach_function :ImPlotAxis_IsOpposite, [:pointer], :bool
    attach_function :ImPlotAxis_IsPanLocked, [:pointer, :bool], :bool
    attach_function :ImPlotAxis_IsRangeLocked, [:pointer], :bool
    attach_function :ImPlotAxis_PixelSize, [:pointer], :float
    attach_function :ImPlotAxis_PixelsToPlot, [:pointer, :float], :double
    attach_function :ImPlotAxis_PlotToPixels, [:pointer, :double], :float
    attach_function :ImPlotAxis_PullLinks, [:pointer], :void
    attach_function :ImPlotAxis_PushLinks, [:pointer], :void
    attach_function :ImPlotAxis_Reset, [:pointer], :void
    attach_function :ImPlotAxis_SetAspect, [:pointer, :double], :void
    attach_function :ImPlotAxis_SetMax, [:pointer, :double, :bool], :bool
    attach_function :ImPlotAxis_SetMin, [:pointer, :double, :bool], :bool
    attach_function :ImPlotAxis_SetRange_PlotRange, [:pointer, ImPlotRange.by_value], :void
    attach_function :ImPlotAxis_SetRange_double, [:pointer, :double, :double], :void
    attach_function :ImPlotAxis_UpdateTransformCache, [:pointer], :void
    attach_function :ImPlotAxis_WillRender, [:pointer], :bool
    attach_function :ImPlotAxis_destroy, [:pointer], :void
    attach_function :ImPlotColormapData_Append, [:pointer, :string, :pointer, :int, :bool], :int
    attach_function :ImPlotColormapData_GetIndex, [:pointer, :string], :int
    attach_function :ImPlotColormapData_GetKeyColor, [:pointer, :int, :int], :uint
    attach_function :ImPlotColormapData_GetKeyCount, [:pointer, :int], :int
    attach_function :ImPlotColormapData_GetKeys, [:pointer, :int], :pointer
    attach_function :ImPlotColormapData_GetName, [:pointer, :int], :string
    attach_function :ImPlotColormapData_GetTable, [:pointer, :int], :pointer
    attach_function :ImPlotColormapData_GetTableColor, [:pointer, :int, :int], :uint
    attach_function :ImPlotColormapData_GetTableSize, [:pointer, :int], :int
    attach_function :ImPlotColormapData_ImPlotColormapData, [], :pointer
    attach_function :ImPlotColormapData_IsQual, [:pointer, :int], :bool
    attach_function :ImPlotColormapData_LerpTable, [:pointer, :int, :float], :uint
    attach_function :ImPlotColormapData_RebuildTables, [:pointer], :void
    attach_function :ImPlotColormapData_SetKeyColor, [:pointer, :int, :int, :uint], :void
    attach_function :ImPlotColormapData__AppendTable, [:pointer, :int], :void
    attach_function :ImPlotColormapData_destroy, [:pointer], :void
    attach_function :ImPlotDateTimeSpec_ImPlotDateTimeSpec_Nil, [], :pointer
    attach_function :ImPlotDateTimeSpec_ImPlotDateTimeSpec_PlotDateFmt, [:int, :int, :bool, :bool], :pointer
    attach_function :ImPlotDateTimeSpec_destroy, [:pointer], :void
    attach_function :ImPlotInputMap_ImPlotInputMap, [], :pointer
    attach_function :ImPlotInputMap_destroy, [:pointer], :void
    attach_function :ImPlotItemGroup_GetItemByIndex, [:pointer, :int], :pointer
    attach_function :ImPlotItemGroup_GetItemCount, [:pointer], :int
    attach_function :ImPlotItemGroup_GetItemID, [:pointer, :string], :uint
    attach_function :ImPlotItemGroup_GetItemIndex, [:pointer, :pointer], :int
    attach_function :ImPlotItemGroup_GetItem_ID, [:pointer, :uint], :pointer
    attach_function :ImPlotItemGroup_GetItem_Str, [:pointer, :string], :pointer
    attach_function :ImPlotItemGroup_GetLegendCount, [:pointer], :int
    attach_function :ImPlotItemGroup_GetLegendItem, [:pointer, :int], :pointer
    attach_function :ImPlotItemGroup_GetLegendLabel, [:pointer, :int], :string
    attach_function :ImPlotItemGroup_GetOrAddItem, [:pointer, :uint], :pointer
    attach_function :ImPlotItemGroup_ImPlotItemGroup, [], :pointer
    attach_function :ImPlotItemGroup_Reset, [:pointer], :void
    attach_function :ImPlotItemGroup_destroy, [:pointer], :void
    attach_function :ImPlotItem_ImPlotItem, [], :pointer
    attach_function :ImPlotItem_destroy, [:pointer], :void
    attach_function :ImPlotLegend_ImPlotLegend, [], :pointer
    attach_function :ImPlotLegend_Reset, [:pointer], :void
    attach_function :ImPlotLegend_destroy, [:pointer], :void
    attach_function :ImPlotNextItemData_ImPlotNextItemData, [], :pointer
    attach_function :ImPlotNextItemData_Reset, [:pointer], :void
    attach_function :ImPlotNextItemData_destroy, [:pointer], :void
    attach_function :ImPlotNextPlotData_ImPlotNextPlotData, [], :pointer
    attach_function :ImPlotNextPlotData_Reset, [:pointer], :void
    attach_function :ImPlotNextPlotData_destroy, [:pointer], :void
    attach_function :ImPlotPlot_ClearTextBuffer, [:pointer], :void
    attach_function :ImPlotPlot_EnabledAxesX, [:pointer], :int
    attach_function :ImPlotPlot_EnabledAxesY, [:pointer], :int
    attach_function :ImPlotPlot_GetAxisLabel, [:pointer, ImPlotAxis.by_value], :string
    attach_function :ImPlotPlot_GetTitle, [:pointer], :string
    attach_function :ImPlotPlot_HasTitle, [:pointer], :bool
    attach_function :ImPlotPlot_ImPlotPlot, [], :pointer
    attach_function :ImPlotPlot_IsInputLocked, [:pointer], :bool
    attach_function :ImPlotPlot_SetAxisLabel, [:pointer, :pointer, :string], :void
    attach_function :ImPlotPlot_SetTitle, [:pointer, :string], :void
    attach_function :ImPlotPlot_XAxis_Nil, [:pointer, :int], :pointer
    attach_function :ImPlotPlot_XAxis__const, [:pointer, :int], :pointer
    attach_function :ImPlotPlot_YAxis_Nil, [:pointer, :int], :pointer
    attach_function :ImPlotPlot_YAxis__const, [:pointer, :int], :pointer
    attach_function :ImPlotPlot_destroy, [:pointer], :void
    attach_function :ImPlotPointError_ImPlotPointError, [:double, :double, :double, :double], :pointer
    attach_function :ImPlotPointError_destroy, [:pointer], :void
    attach_function :ImPlotPoint_ImPlotPoint_Nil, [], :pointer
    attach_function :ImPlotPoint_ImPlotPoint_Vec2, [ImGui::Native::ImVec2.by_value], :pointer
    attach_function :ImPlotPoint_ImPlotPoint_double, [:double, :double], :pointer
    attach_function :ImPlotPoint_destroy, [:pointer], :void
    attach_function :ImPlotRange_Clamp, [:pointer, :double], :double
    attach_function :ImPlotRange_Contains, [:pointer, :double], :bool
    attach_function :ImPlotRange_ImPlotRange_Nil, [], :pointer
    attach_function :ImPlotRange_ImPlotRange_double, [:double, :double], :pointer
    attach_function :ImPlotRange_Size, [:pointer], :double
    attach_function :ImPlotRange_destroy, [:pointer], :void
    attach_function :ImPlotRect_Clamp_PlotPoInt, [:pointer, :pointer, ImPlotPoint.by_value], :void
    attach_function :ImPlotRect_Clamp_double, [:pointer, :pointer, :double, :double], :void
    attach_function :ImPlotRect_Contains_PlotPoInt, [:pointer, ImPlotPoint.by_value], :bool
    attach_function :ImPlotRect_Contains_double, [:pointer, :double, :double], :bool
    attach_function :ImPlotRect_ImPlotRect_Nil, [], :pointer
    attach_function :ImPlotRect_ImPlotRect_double, [:double, :double, :double, :double], :pointer
    attach_function :ImPlotRect_Max, [:pointer, :pointer], :void
    attach_function :ImPlotRect_Min, [:pointer, :pointer], :void
    attach_function :ImPlotRect_Size, [:pointer, :pointer], :void
    attach_function :ImPlotRect_destroy, [:pointer], :void
    attach_function :ImPlotStyle_ImPlotStyle, [], :pointer
    attach_function :ImPlotStyle_destroy, [:pointer], :void
    attach_function :ImPlotSubplot_ImPlotSubplot, [], :pointer
    attach_function :ImPlotSubplot_destroy, [:pointer], :void
    attach_function :ImPlotTagCollection_AppendV, [:pointer, :int, :double, :uint, :uint, :string, :pointer], :void
    attach_function :ImPlotTagCollection_GetText, [:pointer, :int], :string
    attach_function :ImPlotTagCollection_ImPlotTagCollection, [], :pointer
    attach_function :ImPlotTagCollection_Reset, [:pointer], :void
    attach_function :ImPlotTagCollection_destroy, [:pointer], :void
    attach_function :ImPlotTick_ImPlotTick, [:double, :bool, :int, :bool], :pointer
    attach_function :ImPlotTick_destroy, [:pointer], :void
    attach_function :ImPlotTicker_AddTick_PlotTick, [:pointer, ImPlotTick.by_value], :pointer
    attach_function :ImPlotTicker_AddTick_doublePlotFormatter, [:pointer, :double, :bool, :int, :bool, :ImPlotFormatter, :pointer], :pointer
    attach_function :ImPlotTicker_AddTick_doubleStr, [:pointer, :double, :bool, :int, :bool, :string], :pointer
    attach_function :ImPlotTicker_GetText_Int, [:pointer, :int], :string
    attach_function :ImPlotTicker_GetText_PlotTick, [:pointer, ImPlotTick.by_value], :string
    attach_function :ImPlotTicker_ImPlotTicker, [], :pointer
    attach_function :ImPlotTicker_OverrideSizeLate, [:pointer, ImGui::Native::ImVec2.by_value], :void
    attach_function :ImPlotTicker_Reset, [:pointer], :void
    attach_function :ImPlotTicker_TickCount, [:pointer], :int
    attach_function :ImPlotTicker_destroy, [:pointer], :void
    attach_function :ImPlotTime_FromDouble, [:pointer, :double], :void
    attach_function :ImPlotTime_ImPlotTime_Nil, [], :pointer
    attach_function :ImPlotTime_ImPlotTime_time_t, [:pointer, :int], :pointer
    attach_function :ImPlotTime_RollOver, [:pointer], :void
    attach_function :ImPlotTime_ToDouble, [:pointer], :double
    attach_function :ImPlotTime_destroy, [:pointer], :void
    attach_function :ImPlot_AddColormap_U32Ptr, [:string, :pointer, :int, :bool], :int
    attach_function :ImPlot_AddColormap_Vec4Ptr, [:string, :pointer, :int, :bool], :int
    attach_function :ImPlot_AddTextCentered, [:pointer, ImGui::Native::ImVec2.by_value, :uint, :string, :string], :void
    attach_function :ImPlot_AddTextVertical, [:pointer, ImGui::Native::ImVec2.by_value, :uint, :string, :string], :void
    attach_function :ImPlot_AddTime, [:pointer, ImPlotTime.by_value, :int, :int], :void
    attach_function :ImPlot_AllAxesInputLocked, [:pointer, :int], :bool
    attach_function :ImPlot_AnnotationV, [:double, :double, ImGui::Native::ImVec4.by_value, ImGui::Native::ImVec2.by_value, :bool, :string, :pointer], :void
    attach_function :ImPlot_Annotation_Bool, [:double, :double, ImGui::Native::ImVec4.by_value, ImGui::Native::ImVec2.by_value, :bool, :bool], :void
    attach_function :ImPlot_AnyAxesHeld, [:pointer, :int], :bool
    attach_function :ImPlot_AnyAxesHovered, [:pointer, :int], :bool
    attach_function :ImPlot_AnyAxesInputLocked, [:pointer, :int], :bool
    attach_function :ImPlot_BeginAlignedPlots, [:string, :bool], :bool
    attach_function :ImPlot_BeginDragDropSourceAxis, [:int, :int], :bool
    attach_function :ImPlot_BeginDragDropSourceItem, [:string, :int], :bool
    attach_function :ImPlot_BeginDragDropSourcePlot, [:int], :bool
    attach_function :ImPlot_BeginDragDropTargetAxis, [:int], :bool
    attach_function :ImPlot_BeginDragDropTargetLegend, [], :bool
    attach_function :ImPlot_BeginDragDropTargetPlot, [], :bool
    attach_function :ImPlot_BeginItem, [:string, :int, :int], :bool
    attach_function :ImPlot_BeginLegendPopup, [:string, :int], :bool
    attach_function :ImPlot_BeginPlot, [:string, ImGui::Native::ImVec2.by_value, :int], :bool
    attach_function :ImPlot_BeginSubplots, [:string, :int, :int, ImGui::Native::ImVec2.by_value, :int, :pointer, :pointer], :bool
    attach_function :ImPlot_BustColorCache, [:string], :void
    attach_function :ImPlot_BustItemCache, [], :void
    attach_function :ImPlot_BustPlotCache, [], :void
    attach_function :ImPlot_CalcHoverColor, [:uint], :uint
    attach_function :ImPlot_CalcLegendSize, [:pointer, :pointer, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, :bool], :void
    attach_function :ImPlot_CalcTextColor_U32, [:uint], :uint
    attach_function :ImPlot_CalcTextColor_Vec4, [ImGui::Native::ImVec4.by_value], :uint
    attach_function :ImPlot_CalcTextSizeVertical, [:pointer, :string], :void
    attach_function :ImPlot_CalculateBins_FloatPtr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_S16Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_S32Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_S64Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_S8Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_U16Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_U32Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_U64Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_U8Ptr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CalculateBins_doublePtr, [:pointer, :int, :int, ImPlotRange.by_value, :pointer, :pointer], :void
    attach_function :ImPlot_CancelPlotSelection, [], :void
    attach_function :ImPlot_CeilTime, [:pointer, ImPlotTime.by_value, :int], :void
    attach_function :ImPlot_ClampLabelPos, [:pointer, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value], :void
    attach_function :ImPlot_ClampLegendRect, [:pointer, ImGui::Native::ImRect.by_value, ImGui::Native::ImVec2.by_value], :bool
    attach_function :ImPlot_ColormapButton, [:string, ImGui::Native::ImVec2.by_value, :int], :bool
    attach_function :ImPlot_ColormapIcon, [:int], :void
    attach_function :ImPlot_ColormapScale, [:string, :double, :double, ImGui::Native::ImVec2.by_value, :string, :int, :int], :void
    attach_function :ImPlot_ColormapSlider, [:string, :pointer, :pointer, :string, :int], :bool
    attach_function :ImPlot_CombineDateTime, [:pointer, ImPlotTime.by_value, ImPlotTime.by_value], :void
    attach_function :ImPlot_CreateContext, [], :pointer
    attach_function :ImPlot_DestroyContext, [:pointer], :void
    attach_function :ImPlot_DragLineX, [:int, :pointer, ImGui::Native::ImVec4.by_value, :float, :int, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_DragLineY, [:int, :pointer, ImGui::Native::ImVec4.by_value, :float, :int, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_DragPoint, [:int, :pointer, :pointer, ImGui::Native::ImVec4.by_value, :float, :int, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_DragRect, [:int, :pointer, :pointer, :pointer, :pointer, ImGui::Native::ImVec4.by_value, :int, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_EndAlignedPlots, [], :void
    attach_function :ImPlot_EndDragDropSource, [], :void
    attach_function :ImPlot_EndDragDropTarget, [], :void
    attach_function :ImPlot_EndItem, [], :void
    attach_function :ImPlot_EndLegendPopup, [], :void
    attach_function :ImPlot_EndPlot, [], :void
    attach_function :ImPlot_EndSubplots, [], :void
    attach_function :ImPlot_FillRange_Vector_Float_Ptr, [:pointer, :int, :float, :float], :void
    attach_function :ImPlot_FillRange_Vector_S16_Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_FillRange_Vector_S32_Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_FillRange_Vector_S64_Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_FillRange_Vector_S8_Ptr, [:pointer, :int, :char, :char], :void
    attach_function :ImPlot_FillRange_Vector_U16_Ptr, [:pointer, :int, :ushort, :ushort], :void
    attach_function :ImPlot_FillRange_Vector_U32_Ptr, [:pointer, :int, :uint, :uint], :void
    attach_function :ImPlot_FillRange_Vector_U64_Ptr, [:pointer, :int, :ulong_long, :ulong_long], :void
    attach_function :ImPlot_FillRange_Vector_U8_Ptr, [:pointer, :int, :uchar, :uchar], :void
    attach_function :ImPlot_FillRange_Vector_double_Ptr, [:pointer, :int, :double, :double], :void
    attach_function :ImPlot_FitPoint, [ImPlotPoint.by_value], :void
    attach_function :ImPlot_FitPointX, [:double], :void
    attach_function :ImPlot_FitPointY, [:double], :void
    attach_function :ImPlot_FitThisFrame, [], :bool
    attach_function :ImPlot_FloorTime, [:pointer, ImPlotTime.by_value, :int], :void
    attach_function :ImPlot_FormatDate, [ImPlotTime.by_value, :pointer, :int, :int, :bool], :int
    attach_function :ImPlot_FormatDateTime, [ImPlotTime.by_value, :pointer, :int, ImPlotDateTimeSpec.by_value], :int
    attach_function :ImPlot_FormatTime, [ImPlotTime.by_value, :pointer, :int, :int, :bool], :int
    attach_function :ImPlot_Formatter_Default, [:double, :pointer, :int, :pointer], :int
    attach_function :ImPlot_Formatter_Logit, [:double, :pointer, :int, :pointer], :int
    attach_function :ImPlot_Formatter_Time, [:double, :pointer, :int, :pointer], :int
    attach_function :ImPlot_GetAutoColor, [:pointer, :int], :void
    attach_function :ImPlot_GetColormapColor, [:pointer, :int, :int], :void
    attach_function :ImPlot_GetColormapColorU32, [:int, :int], :uint
    attach_function :ImPlot_GetColormapCount, [], :int
    attach_function :ImPlot_GetColormapIndex, [:string], :int
    attach_function :ImPlot_GetColormapName, [:int], :string
    attach_function :ImPlot_GetColormapSize, [:int], :int
    attach_function :ImPlot_GetCurrentContext, [], :pointer
    attach_function :ImPlot_GetCurrentItem, [], :pointer
    attach_function :ImPlot_GetCurrentPlot, [], :pointer
    attach_function :ImPlot_GetDaysInMonth, [:int, :int], :int
    attach_function :ImPlot_GetGmtTime, [ImPlotTime.by_value, :pointer], :pointer
    attach_function :ImPlot_GetInputMap, [], :pointer
    attach_function :ImPlot_GetItem, [:string], :pointer
    attach_function :ImPlot_GetItemData, [], :pointer
    attach_function :ImPlot_GetLastItemColor, [:pointer], :void
    attach_function :ImPlot_GetLocTime, [ImPlotTime.by_value, :pointer], :pointer
    attach_function :ImPlot_GetLocationPos, [:pointer, ImGui::Native::ImRect.by_value, ImGui::Native::ImVec2.by_value, :int, ImGui::Native::ImVec2.by_value], :void
    attach_function :ImPlot_GetMarkerName, [:int], :string
    attach_function :ImPlot_GetMonth, [ImPlotTime.by_value], :int
    attach_function :ImPlot_GetPlot, [:string], :pointer
    attach_function :ImPlot_GetPlotDrawList, [], :pointer
    attach_function :ImPlot_GetPlotLimits, [:pointer, :int, :int], :void
    attach_function :ImPlot_GetPlotMousePos, [:pointer, :int, :int], :void
    attach_function :ImPlot_GetPlotPos, [:pointer], :void
    attach_function :ImPlot_GetPlotSelection, [:pointer, :int, :int], :void
    attach_function :ImPlot_GetPlotSize, [:pointer], :void
    attach_function :ImPlot_GetStyle, [], :pointer
    attach_function :ImPlot_GetStyleColorName, [:int], :string
    attach_function :ImPlot_GetStyleColorU32, [:int], :uint
    attach_function :ImPlot_GetStyleColorVec4, [:pointer, :int], :void
    attach_function :ImPlot_GetTime, [ImPlotTime.by_value, :pointer], :pointer
    attach_function :ImPlot_GetYear, [ImPlotTime.by_value], :int
    attach_function :ImPlot_HideNextItem, [:bool, :int], :void
    attach_function :ImPlot_ImAlmostEqual, [:double, :double, :int], :bool
    attach_function :ImPlot_ImAlphaU32, [:uint, :float], :uint
    attach_function :ImPlot_ImAsinh_Float, [:float], :float
    attach_function :ImPlot_ImAsinh_double, [:double], :double
    attach_function :ImPlot_ImConstrainInf, [:double], :double
    attach_function :ImPlot_ImConstrainLog, [:double], :double
    attach_function :ImPlot_ImConstrainNan, [:double], :double
    attach_function :ImPlot_ImConstrainTime, [:double], :double
    attach_function :ImPlot_ImLerpU32, [:pointer, :int, :float], :uint
    attach_function :ImPlot_ImLog10_Float, [:float], :float
    attach_function :ImPlot_ImLog10_double, [:double], :double
    attach_function :ImPlot_ImMaxArray_FloatPtr, [:pointer, :int], :float
    attach_function :ImPlot_ImMaxArray_S16Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImMaxArray_S32Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImMaxArray_S64Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImMaxArray_S8Ptr, [:pointer, :int], :char
    attach_function :ImPlot_ImMaxArray_U16Ptr, [:pointer, :int], :ushort
    attach_function :ImPlot_ImMaxArray_U32Ptr, [:pointer, :int], :uint
    attach_function :ImPlot_ImMaxArray_U64Ptr, [:pointer, :int], :ulong_long
    attach_function :ImPlot_ImMaxArray_U8Ptr, [:pointer, :int], :uchar
    attach_function :ImPlot_ImMaxArray_doublePtr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_FloatPtr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_S16Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_S32Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_S64Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_S8Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_U16Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_U32Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_U64Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_U8Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImMean_doublePtr, [:pointer, :int], :double
    attach_function :ImPlot_ImMinArray_FloatPtr, [:pointer, :int], :float
    attach_function :ImPlot_ImMinArray_S16Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImMinArray_S32Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImMinArray_S64Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImMinArray_S8Ptr, [:pointer, :int], :char
    attach_function :ImPlot_ImMinArray_U16Ptr, [:pointer, :int], :ushort
    attach_function :ImPlot_ImMinArray_U32Ptr, [:pointer, :int], :uint
    attach_function :ImPlot_ImMinArray_U64Ptr, [:pointer, :int], :ulong_long
    attach_function :ImPlot_ImMinArray_U8Ptr, [:pointer, :int], :uchar
    attach_function :ImPlot_ImMinArray_doublePtr, [:pointer, :int], :double
    attach_function :ImPlot_ImMinMaxArray_FloatPtr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_S16Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_S32Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_S64Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_S8Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_U16Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_U32Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_U64Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_U8Ptr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMinMaxArray_doublePtr, [:pointer, :int, :pointer, :pointer], :void
    attach_function :ImPlot_ImMixU32, [:uint, :uint, :uint], :uint
    attach_function :ImPlot_ImNan, [:double], :bool
    attach_function :ImPlot_ImNanOrInf, [:double], :bool
    attach_function :ImPlot_ImOverlaps_Float, [:float, :float, :float, :float], :bool
    attach_function :ImPlot_ImOverlaps_S16, [:pointer, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_ImOverlaps_S32, [:pointer, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_ImOverlaps_S64, [:pointer, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_ImOverlaps_S8, [:char, :char, :char, :char], :bool
    attach_function :ImPlot_ImOverlaps_U16, [:ushort, :ushort, :ushort, :ushort], :bool
    attach_function :ImPlot_ImOverlaps_U32, [:uint, :uint, :uint, :uint], :bool
    attach_function :ImPlot_ImOverlaps_U64, [:ulong_long, :ulong_long, :ulong_long, :ulong_long], :bool
    attach_function :ImPlot_ImOverlaps_U8, [:uchar, :uchar, :uchar, :uchar], :bool
    attach_function :ImPlot_ImOverlaps_double, [:double, :double, :double, :double], :bool
    attach_function :ImPlot_ImPosMod, [:int, :int], :int
    attach_function :ImPlot_ImRemap01_Float, [:float, :float, :float], :float
    attach_function :ImPlot_ImRemap01_S16, [:pointer, :pointer, :pointer], :pointer
    attach_function :ImPlot_ImRemap01_S32, [:pointer, :pointer, :pointer], :pointer
    attach_function :ImPlot_ImRemap01_S64, [:pointer, :pointer, :pointer], :pointer
    attach_function :ImPlot_ImRemap01_S8, [:char, :char, :char], :char
    attach_function :ImPlot_ImRemap01_U16, [:ushort, :ushort, :ushort], :ushort
    attach_function :ImPlot_ImRemap01_U32, [:uint, :uint, :uint], :uint
    attach_function :ImPlot_ImRemap01_U64, [:ulong_long, :ulong_long, :ulong_long], :ulong_long
    attach_function :ImPlot_ImRemap01_U8, [:uchar, :uchar, :uchar], :uchar
    attach_function :ImPlot_ImRemap01_double, [:double, :double, :double], :double
    attach_function :ImPlot_ImRemap_Float, [:float, :float, :float, :float, :float], :float
    attach_function :ImPlot_ImRemap_S16, [:pointer, :pointer, :pointer, :pointer, :pointer], :pointer
    attach_function :ImPlot_ImRemap_S32, [:pointer, :pointer, :pointer, :pointer, :pointer], :pointer
    attach_function :ImPlot_ImRemap_S64, [:pointer, :pointer, :pointer, :pointer, :pointer], :pointer
    attach_function :ImPlot_ImRemap_S8, [:char, :char, :char, :char, :char], :char
    attach_function :ImPlot_ImRemap_U16, [:ushort, :ushort, :ushort, :ushort, :ushort], :ushort
    attach_function :ImPlot_ImRemap_U32, [:uint, :uint, :uint, :uint, :uint], :uint
    attach_function :ImPlot_ImRemap_U64, [:ulong_long, :ulong_long, :ulong_long, :ulong_long, :ulong_long], :ulong_long
    attach_function :ImPlot_ImRemap_U8, [:uchar, :uchar, :uchar, :uchar, :uchar], :uchar
    attach_function :ImPlot_ImRemap_double, [:double, :double, :double, :double, :double], :double
    attach_function :ImPlot_ImSinh_Float, [:float], :float
    attach_function :ImPlot_ImSinh_double, [:double], :double
    attach_function :ImPlot_ImStdDev_FloatPtr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_S16Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_S32Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_S64Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_S8Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_U16Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_U32Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_U64Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_U8Ptr, [:pointer, :int], :double
    attach_function :ImPlot_ImStdDev_doublePtr, [:pointer, :int], :double
    attach_function :ImPlot_ImSum_FloatPtr, [:pointer, :int], :float
    attach_function :ImPlot_ImSum_S16Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImSum_S32Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImSum_S64Ptr, [:pointer, :int], :pointer
    attach_function :ImPlot_ImSum_S8Ptr, [:pointer, :int], :char
    attach_function :ImPlot_ImSum_U16Ptr, [:pointer, :int], :ushort
    attach_function :ImPlot_ImSum_U32Ptr, [:pointer, :int], :uint
    attach_function :ImPlot_ImSum_U64Ptr, [:pointer, :int], :ulong_long
    attach_function :ImPlot_ImSum_U8Ptr, [:pointer, :int], :uchar
    attach_function :ImPlot_ImSum_doublePtr, [:pointer, :int], :double
    attach_function :ImPlot_Initialize, [:pointer], :void
    attach_function :ImPlot_Intersection, [:pointer, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value], :void
    attach_function :ImPlot_IsAxisHovered, [:int], :bool
    attach_function :ImPlot_IsColorAuto_PlotCol, [:int], :bool
    attach_function :ImPlot_IsColorAuto_Vec4, [ImGui::Native::ImVec4.by_value], :bool
    attach_function :ImPlot_IsLeapYear, [:int], :bool
    attach_function :ImPlot_IsLegendEntryHovered, [:string], :bool
    attach_function :ImPlot_IsPlotHovered, [], :bool
    attach_function :ImPlot_IsPlotSelected, [], :bool
    attach_function :ImPlot_IsSubplotsHovered, [], :bool
    attach_function :ImPlot_ItemIcon_U32, [:uint], :void
    attach_function :ImPlot_ItemIcon_Vec4, [ImGui::Native::ImVec4.by_value], :void
    attach_function :ImPlot_LabelAxisValue, [ImPlotAxis.by_value, :double, :pointer, :int, :bool], :void
    attach_function :ImPlot_Locator_Default, [:pointer, ImPlotRange.by_value, :float, :bool, :ImPlotFormatter, :pointer], :void
    attach_function :ImPlot_Locator_Log10, [:pointer, ImPlotRange.by_value, :float, :bool, :ImPlotFormatter, :pointer], :void
    attach_function :ImPlot_Locator_SymLog, [:pointer, ImPlotRange.by_value, :float, :bool, :ImPlotFormatter, :pointer], :void
    attach_function :ImPlot_Locator_Time, [:pointer, ImPlotRange.by_value, :float, :bool, :ImPlotFormatter, :pointer], :void
    attach_function :ImPlot_MakeTime, [:pointer, :int, :int, :int, :int, :int, :int, :int], :void
    attach_function :ImPlot_MapInputDefault, [:pointer], :void
    attach_function :ImPlot_MapInputReverse, [:pointer], :void
    attach_function :ImPlot_MkGmtTime, [:pointer, :pointer], :void
    attach_function :ImPlot_MkLocTime, [:pointer, :pointer], :void
    attach_function :ImPlot_MkTime, [:pointer, :pointer], :void
    attach_function :ImPlot_NextColormapColor, [:pointer], :void
    attach_function :ImPlot_NextColormapColorU32, [], :uint
    attach_function :ImPlot_NiceNum, [:double, :bool], :double
    attach_function :ImPlot_Now, [:pointer], :void
    attach_function :ImPlot_OrderOfMagnitude, [:double], :int
    attach_function :ImPlot_OrderToPrecision, [:int], :int
    attach_function :ImPlot_PixelsToPlot_Float, [:pointer, :float, :float, :int, :int], :void
    attach_function :ImPlot_PixelsToPlot_Vec2, [:pointer, ImGui::Native::ImVec2.by_value, :int, :int], :void
    attach_function :ImPlot_PlotBarGroups_FloatPtr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_S16Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_S32Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_S64Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_S8Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_U16Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_U32Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_U64Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_U8Ptr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarGroups_doublePtr, [:pointer, :pointer, :int, :int, :double, :double, :int], :void
    attach_function :ImPlot_PlotBarsG, [:string, :ImPlotGetter, :pointer, :int, :double, :int], :void
    attach_function :ImPlot_PlotBars_FloatPtrFloatPtr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_FloatPtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S16PtrS16Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S32PtrS32Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S64PtrS64Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_S8PtrS8Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U16PtrU16Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U32PtrU32Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U64PtrU64Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_U8PtrU8Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_doublePtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotBars_doublePtrdoublePtr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigitalG, [:string, :ImPlotGetter, :pointer, :int, :int], :void
    attach_function :ImPlot_PlotDigital_FloatPtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_S16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_S32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_S64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_S8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_U16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_U32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_U64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_U8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDigital_doublePtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotDummy, [:string, :int], :void
    attach_function :ImPlot_PlotErrorBars_FloatPtrFloatPtrFloatPtrFloatPtr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_FloatPtrFloatPtrFloatPtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S16PtrS16PtrS16PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S16PtrS16PtrS16PtrS16Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S32PtrS32PtrS32PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S32PtrS32PtrS32PtrS32Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S64PtrS64PtrS64PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S64PtrS64PtrS64PtrS64Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S8PtrS8PtrS8PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_S8PtrS8PtrS8PtrS8Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U16PtrU16PtrU16PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U16PtrU16PtrU16PtrU16Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U32PtrU32PtrU32PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U32PtrU32PtrU32PtrU32Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U64PtrU64PtrU64PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U64PtrU64PtrU64PtrU64Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U8PtrU8PtrU8PtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_U8PtrU8PtrU8PtrU8Ptr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_doublePtrdoublePtrdoublePtrInt, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotErrorBars_doublePtrdoublePtrdoublePtrdoublePtr, [:string, :pointer, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotHeatmap_FloatPtr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_S16Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_S32Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_S64Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_S8Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_U16Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_U32Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_U64Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_U8Ptr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHeatmap_doublePtr, [:string, :pointer, :int, :int, :double, :double, :string, ImPlotPoint.by_value, ImPlotPoint.by_value, :int], :void
    attach_function :ImPlot_PlotHistogram2D_FloatPtr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_S16Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_S32Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_S64Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_S8Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_U16Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_U32Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_U64Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_U8Ptr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram2D_doublePtr, [:string, :pointer, :pointer, :int, :int, :int, ImPlotRect.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_FloatPtr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_S16Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_S32Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_S64Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_S8Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_U16Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_U32Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_U64Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_U8Ptr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotHistogram_doublePtr, [:string, :pointer, :int, :int, :double, ImPlotRange.by_value, :int], :double
    attach_function :ImPlot_PlotImage, [:string, :ulong_long, ImPlotPoint.by_value, ImPlotPoint.by_value, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec4.by_value, :int], :void
    attach_function :ImPlot_PlotInfLines_FloatPtr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_S16Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_S32Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_S64Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_S8Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_U16Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_U32Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_U64Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_U8Ptr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotInfLines_doublePtr, [:string, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLineG, [:string, :ImPlotGetter, :pointer, :int, :int], :void
    attach_function :ImPlot_PlotLine_FloatPtrFloatPtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_FloatPtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S16PtrS16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S32PtrS32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S64PtrS64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_S8PtrS8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U16PtrU16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U32PtrU32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U64PtrU64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_U8PtrU8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_doublePtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotLine_doublePtrdoublePtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotPieChart_FloatPtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_FloatPtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S16PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S16PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S32PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S32PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S64PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S64PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S8PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_S8PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U16PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U16PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U32PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U32PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U64PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U64PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U8PtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_U8PtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_doublePtrPlotFormatter, [:pointer, :pointer, :int, :double, :double, :double, :ImPlotFormatter, :pointer, :double, :int], :void
    attach_function :ImPlot_PlotPieChart_doublePtrStr, [:pointer, :pointer, :int, :double, :double, :double, :string, :double, :int], :void
    attach_function :ImPlot_PlotScatterG, [:string, :ImPlotGetter, :pointer, :int, :int], :void
    attach_function :ImPlot_PlotScatter_FloatPtrFloatPtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_FloatPtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S16PtrS16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S32PtrS32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S64PtrS64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_S8PtrS8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U16PtrU16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U32PtrU32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U64PtrU64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_U8PtrU8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_doublePtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotScatter_doublePtrdoublePtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShadedG, [:string, :ImPlotGetter, :pointer, :ImPlotGetter, :pointer, :int, :int], :void
    attach_function :ImPlot_PlotShaded_FloatPtrFloatPtrFloatPtr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_FloatPtrFloatPtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_FloatPtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S16PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S16PtrS16PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S16PtrS16PtrS16Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S32PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S32PtrS32PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S32PtrS32PtrS32Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S64PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S64PtrS64PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S64PtrS64PtrS64Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S8PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S8PtrS8PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_S8PtrS8PtrS8Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U16PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U16PtrU16PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U16PtrU16PtrU16Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U32PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U32PtrU32PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U32PtrU32PtrU32Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U64PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U64PtrU64PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U64PtrU64PtrU64Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U8PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U8PtrU8PtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_U8PtrU8PtrU8Ptr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_doublePtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_doublePtrdoublePtrInt, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotShaded_doublePtrdoublePtrdoublePtr, [:string, :pointer, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairsG, [:string, :ImPlotGetter, :pointer, :int, :int], :void
    attach_function :ImPlot_PlotStairs_FloatPtrFloatPtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_FloatPtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S16PtrS16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S32PtrS32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S64PtrS64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_S8PtrS8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U16PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U16PtrU16Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U32PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U32PtrU32Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U64PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U64PtrU64Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U8PtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_U8PtrU8Ptr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_doublePtrInt, [:string, :pointer, :int, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStairs_doublePtrdoublePtr, [:string, :pointer, :pointer, :int, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_FloatPtrFloatPtr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_FloatPtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S16PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S16PtrS16Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S32PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S32PtrS32Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S64PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S64PtrS64Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S8PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_S8PtrS8Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U16PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U16PtrU16Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U32PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U32PtrU32Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U64PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U64PtrU64Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U8PtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_U8PtrU8Ptr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_doublePtrInt, [:string, :pointer, :int, :double, :double, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotStems_doublePtrdoublePtr, [:string, :pointer, :pointer, :int, :double, :int, :int, :int], :void
    attach_function :ImPlot_PlotText, [:string, :double, :double, ImGui::Native::ImVec2.by_value, :int], :void
    attach_function :ImPlot_PlotToPixels_PlotPoInt, [:pointer, ImPlotPoint.by_value, :int, :int], :void
    attach_function :ImPlot_PlotToPixels_double, [:pointer, :double, :double, :int, :int], :void
    attach_function :ImPlot_PopColormap, [:int], :void
    attach_function :ImPlot_PopPlotClipRect, [], :void
    attach_function :ImPlot_PopStyleColor, [:int], :void
    attach_function :ImPlot_PopStyleVar, [:int], :void
    attach_function :ImPlot_Precision, [:double], :int
    attach_function :ImPlot_PushColormap_PlotColormap, [:int], :void
    attach_function :ImPlot_PushColormap_Str, [:string], :void
    attach_function :ImPlot_PushPlotClipRect, [:float], :void
    attach_function :ImPlot_PushStyleColor_U32, [:int, :uint], :void
    attach_function :ImPlot_PushStyleColor_Vec4, [:int, ImGui::Native::ImVec4.by_value], :void
    attach_function :ImPlot_PushStyleVar_Float, [:int, :float], :void
    attach_function :ImPlot_PushStyleVar_Int, [:int, :int], :void
    attach_function :ImPlot_PushStyleVar_Vec2, [:int, ImGui::Native::ImVec2.by_value], :void
    attach_function :ImPlot_RangesOverlap, [ImPlotRange.by_value, ImPlotRange.by_value], :bool
    attach_function :ImPlot_RegisterOrGetItem, [:string, :int, :pointer], :pointer
    attach_function :ImPlot_RenderColorBar, [:pointer, :int, :pointer, ImGui::Native::ImRect.by_value, :bool, :bool, :bool], :void
    attach_function :ImPlot_ResetCtxForNextAlignedPlots, [:pointer], :void
    attach_function :ImPlot_ResetCtxForNextPlot, [:pointer], :void
    attach_function :ImPlot_ResetCtxForNextSubplot, [:pointer], :void
    attach_function :ImPlot_RoundTime, [:pointer, ImPlotTime.by_value, :int], :void
    attach_function :ImPlot_RoundTo, [:double, :int], :double
    attach_function :ImPlot_SampleColormap, [:pointer, :float, :int], :void
    attach_function :ImPlot_SampleColormapU32, [:float, :int], :uint
    attach_function :ImPlot_SetAxes, [:int, :int], :void
    attach_function :ImPlot_SetAxis, [:int], :void
    attach_function :ImPlot_SetCurrentContext, [:pointer], :void
    attach_function :ImPlot_SetImGuiContext, [:pointer], :void
    attach_function :ImPlot_SetNextAxesLimits, [:double, :double, :double, :double, :int], :void
    attach_function :ImPlot_SetNextAxesToFit, [], :void
    attach_function :ImPlot_SetNextAxisLimits, [:int, :double, :double, :int], :void
    attach_function :ImPlot_SetNextAxisLinks, [:int, :pointer, :pointer], :void
    attach_function :ImPlot_SetNextAxisToFit, [:int], :void
    attach_function :ImPlot_SetNextErrorBarStyle, [ImGui::Native::ImVec4.by_value, :float, :float], :void
    attach_function :ImPlot_SetNextFillStyle, [ImGui::Native::ImVec4.by_value, :float], :void
    attach_function :ImPlot_SetNextLineStyle, [ImGui::Native::ImVec4.by_value, :float], :void
    attach_function :ImPlot_SetNextMarkerStyle, [:int, :float, ImGui::Native::ImVec4.by_value, :float, ImGui::Native::ImVec4.by_value], :void
    attach_function :ImPlot_SetupAxes, [:string, :string, :int, :int], :void
    attach_function :ImPlot_SetupAxesLimits, [:double, :double, :double, :double, :int], :void
    attach_function :ImPlot_SetupAxis, [:int, :string, :int], :void
    attach_function :ImPlot_SetupAxisFormat_PlotFormatter, [:int, :ImPlotFormatter, :pointer], :void
    attach_function :ImPlot_SetupAxisFormat_Str, [:int, :string], :void
    attach_function :ImPlot_SetupAxisLimits, [:int, :double, :double, :int], :void
    attach_function :ImPlot_SetupAxisLimitsConstraints, [:int, :double, :double], :void
    attach_function :ImPlot_SetupAxisLinks, [:int, :pointer, :pointer], :void
    attach_function :ImPlot_SetupAxisScale_PlotScale, [:int, :int], :void
    attach_function :ImPlot_SetupAxisScale_PlotTransform, [:int, :ImPlotTransform, :ImPlotTransform, :pointer], :void
    attach_function :ImPlot_SetupAxisTicks_double, [:int, :double, :double, :int, :pointer, :bool], :void
    attach_function :ImPlot_SetupAxisTicks_doublePtr, [:int, :pointer, :int, :pointer, :bool], :void
    attach_function :ImPlot_SetupAxisZoomConstraints, [:int, :double, :double], :void
    attach_function :ImPlot_SetupFinish, [], :void
    attach_function :ImPlot_SetupLegend, [:int, :int], :void
    attach_function :ImPlot_SetupLock, [], :void
    attach_function :ImPlot_SetupMouseText, [:int, :int], :void
    attach_function :ImPlot_ShowAltLegend, [:string, :bool, ImGui::Native::ImVec2.by_value, :bool], :void
    attach_function :ImPlot_ShowAxisContextMenu, [:pointer, :pointer, :bool], :void
    attach_function :ImPlot_ShowColormapSelector, [:string], :bool
    attach_function :ImPlot_ShowDatePicker, [:string, :pointer, :pointer, :pointer, :pointer], :bool
    attach_function :ImPlot_ShowDemoWindow, [:pointer], :void
    attach_function :ImPlot_ShowInputMapSelector, [:string], :bool
    attach_function :ImPlot_ShowLegendContextMenu, [:pointer, :bool], :bool
    attach_function :ImPlot_ShowLegendEntries, [:pointer, ImGui::Native::ImRect.by_value, :bool, ImGui::Native::ImVec2.by_value, ImGui::Native::ImVec2.by_value, :bool, :pointer], :bool
    attach_function :ImPlot_ShowMetricsWindow, [:pointer], :void
    attach_function :ImPlot_ShowPlotContextMenu, [:pointer], :void
    attach_function :ImPlot_ShowStyleEditor, [:pointer], :void
    attach_function :ImPlot_ShowStyleSelector, [:string], :bool
    attach_function :ImPlot_ShowSubplotsContextMenu, [:pointer], :void
    attach_function :ImPlot_ShowTimePicker, [:string, :pointer], :bool
    attach_function :ImPlot_ShowUserGuide, [], :void
    attach_function :ImPlot_StyleColorsAuto, [:pointer], :void
    attach_function :ImPlot_StyleColorsClassic, [:pointer], :void
    attach_function :ImPlot_StyleColorsDark, [:pointer], :void
    attach_function :ImPlot_StyleColorsLight, [:pointer], :void
    attach_function :ImPlot_SubplotNextCell, [], :void
    attach_function :ImPlot_TagXV, [:double, ImGui::Native::ImVec4.by_value, :string, :pointer], :void
    attach_function :ImPlot_TagX_Bool, [:double, ImGui::Native::ImVec4.by_value, :bool], :void
    attach_function :ImPlot_TagYV, [:double, ImGui::Native::ImVec4.by_value, :string, :pointer], :void
    attach_function :ImPlot_TagY_Bool, [:double, ImGui::Native::ImVec4.by_value, :bool], :void
    attach_function :ImPlot_Today, [:pointer], :void
    attach_function :ImPlot_TransformForward_Log10, [:double, :pointer], :double
    attach_function :ImPlot_TransformForward_Logit, [:double, :pointer], :double
    attach_function :ImPlot_TransformForward_SymLog, [:double, :pointer], :double
    attach_function :ImPlot_TransformInverse_Log10, [:double, :pointer], :double
    attach_function :ImPlot_TransformInverse_Logit, [:double, :pointer], :double
    attach_function :ImPlot_TransformInverse_SymLog, [:double, :pointer], :double
  end
end
