# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    class Formatter_Time_Data < FFI::Struct; end
    class ImPlotAlignmentData < FFI::Struct; end
    class ImPlotAnnotation < FFI::Struct; end
    class ImPlotAnnotationCollection < FFI::Struct; end
    class ImPlotAxis < FFI::Struct; end
    class ImPlotColormapData < FFI::Struct; end
    class ImPlotContext < FFI::Struct; end
    class ImPlotDateTimeSpec < FFI::Struct; end
    class ImPlotInputMap < FFI::Struct; end
    class ImPlotItem < FFI::Struct; end
    class ImPlotItemGroup < FFI::Struct; end
    class ImPlotLegend < FFI::Struct; end
    class ImPlotNextItemData < FFI::Struct; end
    class ImPlotNextPlotData < FFI::Struct; end
    class ImPlotPlot < FFI::Struct; end
    class ImPlotPoint < FFI::Struct; end
    class ImPlotPointError < FFI::Struct; end
    class ImPlotRange < FFI::Struct; end
    class ImPlotRect < FFI::Struct; end
    class ImPlotStyle < FFI::Struct; end
    class ImPlotSubplot < FFI::Struct; end
    class ImPlotTag < FFI::Struct; end
    class ImPlotTagCollection < FFI::Struct; end
    class ImPlotTick < FFI::Struct; end
    class ImPlotTicker < FFI::Struct; end
    class ImPlotTime < FFI::Struct; end

    ImPlotTime.layout(
        "S", :pointer,
        "Us", :int
    )
    ImPlotDateTimeSpec.layout(
        "Date", :int,
        "Time", :int,
        "UseISO8601", :bool,
        "Use24HourClock", :bool
    )
    Formatter_Time_Data.layout(
        "Time", ImPlotTime.by_value,
        "Spec", ImPlotDateTimeSpec.by_value,
        "UserFormatter", :ImPlotFormatter,
        "UserFormatterData", :pointer
    )
    ImPlotAlignmentData.layout(
        "Vertical", :bool,
        "PadA", :float,
        "PadB", :float,
        "PadAMax", :float,
        "PadBMax", :float
    )
    ImPlotAnnotation.layout(
        "Pos", ImGui::Native::ImVec2.by_value,
        "Offset", ImGui::Native::ImVec2.by_value,
        "ColorBg", :uint,
        "ColorFg", :uint,
        "TextOffset", :int,
        "Clamp", :bool
    )
    ImPlotAnnotationCollection.layout(
        "Annotations", ImGui::Native::ImVector.by_value,
        "TextBuffer", ImGui::Native::ImGuiTextBuffer.by_value,
        "Size", :int
    )
    ImPlotRange.layout(
        "Min", :double,
        "Max", :double
    )
    ImPlotTicker.layout(
        "Ticks", ImGui::Native::ImVector.by_value,
        "TextBuffer", ImGui::Native::ImGuiTextBuffer.by_value,
        "MaxSize", ImGui::Native::ImVec2.by_value,
        "LateSize", ImGui::Native::ImVec2.by_value,
        "Levels", :int
    )
    ImPlotAxis.layout(
        "ID", :uint,
        "Flags", :int,
        "PreviousFlags", :int,
        "Range", ImPlotRange.by_value,
        "RangeCond", :int,
        "Scale", :int,
        "FitExtents", ImPlotRange.by_value,
        "OrthoAxis", :pointer,
        "ConstraintRange", ImPlotRange.by_value,
        "ConstraintZoom", ImPlotRange.by_value,
        "Ticker", ImPlotTicker.by_value,
        "Formatter", :ImPlotFormatter,
        "FormatterData", :pointer,
        "FormatSpec[16]", [:char, 16],
        "Locator", :ImPlotLocator,
        "LinkedMin", :pointer,
        "LinkedMax", :pointer,
        "PickerLevel", :int,
        "PickerTimeMin", ImPlotTime.by_value,
        "PickerTimeMax", ImPlotTime.by_value,
        "TransformForward", :ImPlotTransform,
        "TransformInverse", :ImPlotTransform,
        "TransformData", :pointer,
        "PixelMin", :float,
        "PixelMax", :float,
        "ScaleMin", :double,
        "ScaleMax", :double,
        "ScaleToPixel", :double,
        "Datum1", :float,
        "Datum2", :float,
        "HoverRect", ImGui::Native::ImRect.by_value,
        "LabelOffset", :int,
        "ColorMaj", :uint,
        "ColorMin", :uint,
        "ColorTick", :uint,
        "ColorTxt", :uint,
        "ColorBg", :uint,
        "ColorHov", :uint,
        "ColorAct", :uint,
        "ColorHiLi", :uint,
        "Enabled", :bool,
        "Vertical", :bool,
        "FitThisFrame", :bool,
        "HasRange", :bool,
        "HasFormatSpec", :bool,
        "ShowDefaultTicks", :bool,
        "Hovered", :bool,
        "Held", :bool
    )
    ImPlotColormapData.layout(
        "Keys", ImGui::Native::ImVector.by_value,
        "KeyCounts", ImGui::Native::ImVector.by_value,
        "KeyOffsets", ImGui::Native::ImVector.by_value,
        "Tables", ImGui::Native::ImVector.by_value,
        "TableSizes", ImGui::Native::ImVector.by_value,
        "TableOffsets", ImGui::Native::ImVector.by_value,
        "Text", ImGui::Native::ImGuiTextBuffer.by_value,
        "TextOffsets", ImGui::Native::ImVector.by_value,
        "Quals", ImGui::Native::ImVector.by_value,
        "Map", ImGui::Native::ImGuiStorage.by_value,
        "Count", :int
    )
    ImPlotTagCollection.layout(
        "Tags", ImGui::Native::ImVector.by_value,
        "TextBuffer", ImGui::Native::ImGuiTextBuffer.by_value,
        "Size", :int
    )
    ImPlotStyle.layout(
        "LineWeight", :float,
        "Marker", :int,
        "MarkerSize", :float,
        "MarkerWeight", :float,
        "FillAlpha", :float,
        "ErrorBarSize", :float,
        "ErrorBarWeight", :float,
        "DigitalBitHeight", :float,
        "DigitalBitGap", :float,
        "PlotBorderSize", :float,
        "MinorAlpha", :float,
        "MajorTickLen", ImGui::Native::ImVec2.by_value,
        "MinorTickLen", ImGui::Native::ImVec2.by_value,
        "MajorTickSize", ImGui::Native::ImVec2.by_value,
        "MinorTickSize", ImGui::Native::ImVec2.by_value,
        "MajorGridSize", ImGui::Native::ImVec2.by_value,
        "MinorGridSize", ImGui::Native::ImVec2.by_value,
        "PlotPadding", ImGui::Native::ImVec2.by_value,
        "LabelPadding", ImGui::Native::ImVec2.by_value,
        "LegendPadding", ImGui::Native::ImVec2.by_value,
        "LegendInnerPadding", ImGui::Native::ImVec2.by_value,
        "LegendSpacing", ImGui::Native::ImVec2.by_value,
        "MousePosPadding", ImGui::Native::ImVec2.by_value,
        "AnnotationPadding", ImGui::Native::ImVec2.by_value,
        "FitPadding", ImGui::Native::ImVec2.by_value,
        "PlotDefaultSize", ImGui::Native::ImVec2.by_value,
        "PlotMinSize", ImGui::Native::ImVec2.by_value,
        "Colors[ImPlotCol_COUNT]", [ImGui::Native::ImVec4.by_value, 21],
        "Colormap", :int,
        "UseLocalTime", :bool,
        "UseISO8601", :bool,
        "Use24HourClock", :bool
    )
    ImPlotNextPlotData.layout(
        "RangeCond[ImAxis_COUNT]", [:int, 6],
        "Range[ImAxis_COUNT]", [ImPlotRange.by_value, 6],
        "HasRange[ImAxis_COUNT]", [:bool, 6],
        "Fit[ImAxis_COUNT]", [:bool, 6],
        "LinkedMin[ImAxis_COUNT]", [:pointer, 6],
        "LinkedMax[ImAxis_COUNT]", [:pointer, 6]
    )
    ImPlotNextItemData.layout(
        "Colors[5]", [ImGui::Native::ImVec4.by_value, 5],
        "LineWeight", :float,
        "Marker", :int,
        "MarkerSize", :float,
        "MarkerWeight", :float,
        "FillAlpha", :float,
        "ErrorBarSize", :float,
        "ErrorBarWeight", :float,
        "DigitalBitHeight", :float,
        "DigitalBitGap", :float,
        "RenderLine", :bool,
        "RenderFill", :bool,
        "RenderMarkerLine", :bool,
        "RenderMarkerFill", :bool,
        "HasHidden", :bool,
        "Hidden", :bool,
        "HiddenCond", :int
    )
    ImPlotInputMap.layout(
        "Pan", :int,
        "PanMod", :int,
        "Fit", :int,
        "Select", :int,
        "SelectCancel", :int,
        "SelectMod", :int,
        "SelectHorzMod", :int,
        "SelectVertMod", :int,
        "Menu", :int,
        "OverrideMod", :int,
        "ZoomMod", :int,
        "ZoomRate", :float
    )
    ImPlotContext.layout(
        "Plots", :pointer,
        "Subplots", :pointer,
        "CurrentPlot", :pointer,
        "CurrentSubplot", :pointer,
        "CurrentItems", :pointer,
        "CurrentItem", :pointer,
        "PreviousItem", :pointer,
        "CTicker", ImPlotTicker.by_value,
        "Annotations", ImPlotAnnotationCollection.by_value,
        "Tags", ImPlotTagCollection.by_value,
        "Style", ImPlotStyle.by_value,
        "ColorModifiers", ImGui::Native::ImVector.by_value,
        "StyleModifiers", ImGui::Native::ImVector.by_value,
        "ColormapData", ImPlotColormapData.by_value,
        "ColormapModifiers", ImGui::Native::ImVector.by_value,
        "Tm", :pointer,
        "TempDouble1", ImGui::Native::ImVector.by_value,
        "TempDouble2", ImGui::Native::ImVector.by_value,
        "TempInt1", ImGui::Native::ImVector.by_value,
        "DigitalPlotItemCnt", :int,
        "DigitalPlotOffset", :int,
        "NextPlotData", ImPlotNextPlotData.by_value,
        "NextItemData", ImPlotNextItemData.by_value,
        "InputMap", ImPlotInputMap.by_value,
        "OpenContextThisFrame", :bool,
        "MousePosStringBuilder", ImGui::Native::ImGuiTextBuffer.by_value,
        "SortItems", :pointer,
        "AlignmentData", :pointer,
        "CurrentAlignmentH", :pointer,
        "CurrentAlignmentV", :pointer
    )
    ImPlotItem.layout(
        "ID", :uint,
        "Color", :uint,
        "LegendHoverRect", ImGui::Native::ImRect.by_value,
        "NameOffset", :int,
        "Show", :bool,
        "LegendHovered", :bool,
        "SeenThisFrame", :bool
    )
    ImPlotLegend.layout(
        "Flags", :int,
        "PreviousFlags", :int,
        "Location", :int,
        "PreviousLocation", :int,
        "Scroll", ImGui::Native::ImVec2.by_value,
        "Indices", ImGui::Native::ImVector.by_value,
        "Labels", ImGui::Native::ImGuiTextBuffer.by_value,
        "Rect", ImGui::Native::ImRect.by_value,
        "RectClamped", ImGui::Native::ImRect.by_value,
        "Hovered", :bool,
        "Held", :bool,
        "CanGoInside", :bool
    )
    ImPlotItemGroup.layout(
        "ID", :uint,
        "Legend", ImPlotLegend.by_value,
        "ItemPool", :pointer,
        "ColormapIdx", :int
    )
    ImPlotPlot.layout(
        "ID", :uint,
        "Flags", :int,
        "PreviousFlags", :int,
        "MouseTextLocation", :int,
        "MouseTextFlags", :int,
        "Axes[ImAxis_COUNT]", [ImPlotAxis.by_value, 6],
        "TextBuffer", ImGui::Native::ImGuiTextBuffer.by_value,
        "Items", ImPlotItemGroup.by_value,
        "CurrentX", :int,
        "CurrentY", :int,
        "FrameRect", ImGui::Native::ImRect.by_value,
        "CanvasRect", ImGui::Native::ImRect.by_value,
        "PlotRect", ImGui::Native::ImRect.by_value,
        "AxesRect", ImGui::Native::ImRect.by_value,
        "SelectRect", ImGui::Native::ImRect.by_value,
        "SelectStart", ImGui::Native::ImVec2.by_value,
        "TitleOffset", :int,
        "JustCreated", :bool,
        "Initialized", :bool,
        "SetupLocked", :bool,
        "FitThisFrame", :bool,
        "Hovered", :bool,
        "Held", :bool,
        "Selecting", :bool,
        "Selected", :bool,
        "ContextLocked", :bool
    )
    ImPlotPointError.layout(
        "X", :double,
        "Y", :double,
        "Neg", :double,
        "Pos", :double
    )
    ImPlotRect.layout(
        "X", ImPlotRange.by_value,
        "Y", ImPlotRange.by_value
    )
    ImPlotSubplot.layout(
        "ID", :uint,
        "Flags", :int,
        "PreviousFlags", :int,
        "Items", ImPlotItemGroup.by_value,
        "Rows", :int,
        "Cols", :int,
        "CurrentIdx", :int,
        "FrameRect", ImGui::Native::ImRect.by_value,
        "GridRect", ImGui::Native::ImRect.by_value,
        "CellSize", ImGui::Native::ImVec2.by_value,
        "RowAlignmentData", ImGui::Native::ImVector.by_value,
        "ColAlignmentData", ImGui::Native::ImVector.by_value,
        "RowRatios", ImGui::Native::ImVector.by_value,
        "ColRatios", ImGui::Native::ImVector.by_value,
        "RowLinkData", ImGui::Native::ImVector.by_value,
        "ColLinkData", ImGui::Native::ImVector.by_value,
        "TempSizes[2]", [:float, 2],
        "FrameHovered", :bool,
        "HasTitle", :bool
    )
    ImPlotTag.layout(
        "Axis", :int,
        "Value", :double,
        "ColorBg", :uint,
        "ColorFg", :uint,
        "TextOffset", :int
    )
    ImPlotTick.layout(
        "PlotPos", :double,
        "PixelPos", :float,
        "LabelSize", ImGui::Native::ImVec2.by_value,
        "TextOffset", :int,
        "Major", :bool,
        "ShowLabel", :bool,
        "Level", :int,
        "Idx", :int
    )
  end
end
