# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    class Formatter_Time_Data < FFI::Struct; end
    class ImPlotAlignmentData < FFI::Struct; end
    class ImPlotAnnotation < FFI::Struct; end
    class ImPlotAnnotationCollection < FFI::Struct; end
    class ImPlotAxis < FFI::Struct; end
    class ImPlotColormapData < FFI::Struct; end
    class ImPlotContext < FFI::Struct; end
    class ImPlotDateTimeSpec < FFI::Struct; end
    class ImPlotInputMap < FFI::Struct; end
    class ImPlotItem < FFI::Struct; end
    class ImPlotItemGroup < FFI::Struct; end
    class ImPlotLegend < FFI::Struct; end
    class ImPlotNextItemData < FFI::Struct; end
    class ImPlotNextPlotData < FFI::Struct; end
    class ImPlotPlot < FFI::Struct; end
    class ImPlotPoint < FFI::Struct; end
    class ImPlotPointError < FFI::Struct; end
    class ImPlotRange < FFI::Struct; end
    class ImPlotRect < FFI::Struct; end
    class ImPlotStyle < FFI::Struct; end
    class ImPlotSubplot < FFI::Struct; end
    class ImPlotTag < FFI::Struct; end
    class ImPlotTagCollection < FFI::Struct; end
    class ImPlotTick < FFI::Struct; end
    class ImPlotTicker < FFI::Struct; end
    class ImPlotTime < FFI::Struct; end
    ImPlotPoint.layout(
        "x", :double,
        "y", :double
    )
    typedef :int, :ImAxis
    typedef :int, :ImPlotAxisFlags
    typedef :int, :ImPlotBarGroupsFlags
    typedef :int, :ImPlotBarsFlags
    typedef :int, :ImPlotBin
    typedef :int, :ImPlotCol
    typedef :int, :ImPlotColormap
    typedef :int, :ImPlotColormapScaleFlags
    typedef :int, :ImPlotCond
    typedef :int, :ImPlotDateFmt
    typedef :int, :ImPlotDigitalFlags
    typedef :int, :ImPlotDragToolFlags
    typedef :int, :ImPlotDummyFlags
    typedef :int, :ImPlotErrorBarsFlags
    typedef :int, :ImPlotFlags
    callback :ImPlotFormatter, [:double, :pointer, :int, :pointer], :int
    callback :ImPlotGetter, [:int, :pointer], ImPlotPoint.by_value
    typedef :int, :ImPlotHeatmapFlags
    typedef :int, :ImPlotHistogramFlags
    typedef :int, :ImPlotImageFlags
    typedef :int, :ImPlotInfLinesFlags
    typedef :int, :ImPlotItemFlags
    typedef :int, :ImPlotLegendFlags
    typedef :int, :ImPlotLineFlags
    typedef :int, :ImPlotLocation
    callback :ImPlotLocator, [:pointer, :pointer, :float, :bool, :ImPlotFormatter, :pointer], :void
    typedef :int, :ImPlotMarker
    typedef :int, :ImPlotMouseTextFlags
    typedef :int, :ImPlotPieChartFlags
    typedef :int, :ImPlotScale
    typedef :int, :ImPlotScatterFlags
    typedef :int, :ImPlotShadedFlags
    typedef :int, :ImPlotStairsFlags
    typedef :int, :ImPlotStemsFlags
    typedef :int, :ImPlotStyleVar
    typedef :int, :ImPlotSubplotFlags
    typedef :int, :ImPlotTextFlags
    typedef :int, :ImPlotTimeFmt
    typedef :int, :ImPlotTimeUnit
    callback :ImPlotTransform, [:double, :pointer], :double
  end
end
