# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    ImDrawFlags_None = 0
    ImDrawFlags_Closed = 1
    ImDrawFlags_RoundCornersTopLeft = 16
    ImDrawFlags_RoundCornersTopRight = 32
    ImDrawFlags_RoundCornersBottomLeft = 64
    ImDrawFlags_RoundCornersBottomRight = 128
    ImDrawFlags_RoundCornersNone = 256
    ImDrawFlags_RoundCornersTop = 48
    ImDrawFlags_RoundCornersBottom = 192
    ImDrawFlags_RoundCornersLeft = 80
    ImDrawFlags_RoundCornersRight = 160
    ImDrawFlags_RoundCornersAll = 240
    ImDrawFlags_RoundCornersDefault_ = 240
    ImDrawFlags_RoundCornersMask_ = 496
    ImDrawListFlags_None = 0
    ImDrawListFlags_AntiAliasedLines = 1
    ImDrawListFlags_AntiAliasedLinesUseTex = 2
    ImDrawListFlags_AntiAliasedFill = 4
    ImDrawListFlags_AllowVtxOffset = 8
    ImFontAtlasFlags_None = 0
    ImFontAtlasFlags_NoPowerOfTwoHeight = 1
    ImFontAtlasFlags_NoMouseCursors = 2
    ImFontAtlasFlags_NoBakedLines = 4
    ImGuiActivateFlags_None = 0
    ImGuiActivateFlags_PreferInput = 1
    ImGuiActivateFlags_PreferTweak = 2
    ImGuiActivateFlags_TryToPreserveState = 4
    ImGuiActivateFlags_FromTabbing = 8
    ImGuiActivateFlags_FromShortcut = 16
    ImGuiAxis_None = -1
    ImGuiAxis_X = 0
    ImGuiAxis_Y = 1
    ImGuiBackendFlags_None = 0
    ImGuiBackendFlags_HasGamepad = 1
    ImGuiBackendFlags_HasMouseCursors = 2
    ImGuiBackendFlags_HasSetMousePos = 4
    ImGuiBackendFlags_RendererHasVtxOffset = 8
    ImGuiBackendFlags_PlatformHasViewports = 1024
    ImGuiBackendFlags_HasMouseHoveredViewport = 2048
    ImGuiBackendFlags_RendererHasViewports = 4096
    ImGuiButtonFlags_PressedOnClick = 16
    ImGuiButtonFlags_PressedOnClickRelease = 32
    ImGuiButtonFlags_PressedOnClickReleaseAnywhere = 64
    ImGuiButtonFlags_PressedOnRelease = 128
    ImGuiButtonFlags_PressedOnDoubleClick = 256
    ImGuiButtonFlags_PressedOnDragDropHold = 512
    ImGuiButtonFlags_FlattenChildren = 2048
    ImGuiButtonFlags_AllowOverlap = 4096
    ImGuiButtonFlags_AlignTextBaseLine = 32768
    ImGuiButtonFlags_NoKeyModsAllowed = 65536
    ImGuiButtonFlags_NoHoldingActiveId = 131072
    ImGuiButtonFlags_NoNavFocus = 262144
    ImGuiButtonFlags_NoHoveredOnFocus = 524288
    ImGuiButtonFlags_NoSetKeyOwner = 1048576
    ImGuiButtonFlags_NoTestKeyOwner = 2097152
    ImGuiButtonFlags_PressedOnMask_ = 1008
    ImGuiButtonFlags_PressedOnDefault_ = 32
    ImGuiButtonFlags_None = 0
    ImGuiButtonFlags_MouseButtonLeft = 1
    ImGuiButtonFlags_MouseButtonRight = 2
    ImGuiButtonFlags_MouseButtonMiddle = 4
    ImGuiButtonFlags_MouseButtonMask_ = 7
    ImGuiButtonFlags_EnableNav = 8
    ImGuiChildFlags_None = 0
    ImGuiChildFlags_Borders = 1
    ImGuiChildFlags_AlwaysUseWindowPadding = 2
    ImGuiChildFlags_ResizeX = 4
    ImGuiChildFlags_ResizeY = 8
    ImGuiChildFlags_AutoResizeX = 16
    ImGuiChildFlags_AutoResizeY = 32
    ImGuiChildFlags_AlwaysAutoResize = 64
    ImGuiChildFlags_FrameStyle = 128
    ImGuiChildFlags_NavFlattened = 256
    ImGuiCol_Text = 0
    ImGuiCol_TextDisabled = 1
    ImGuiCol_WindowBg = 2
    ImGuiCol_ChildBg = 3
    ImGuiCol_PopupBg = 4
    ImGuiCol_Border = 5
    ImGuiCol_BorderShadow = 6
    ImGuiCol_FrameBg = 7
    ImGuiCol_FrameBgHovered = 8
    ImGuiCol_FrameBgActive = 9
    ImGuiCol_TitleBg = 10
    ImGuiCol_TitleBgActive = 11
    ImGuiCol_TitleBgCollapsed = 12
    ImGuiCol_MenuBarBg = 13
    ImGuiCol_ScrollbarBg = 14
    ImGuiCol_ScrollbarGrab = 15
    ImGuiCol_ScrollbarGrabHovered = 16
    ImGuiCol_ScrollbarGrabActive = 17
    ImGuiCol_CheckMark = 18
    ImGuiCol_SliderGrab = 19
    ImGuiCol_SliderGrabActive = 20
    ImGuiCol_Button = 21
    ImGuiCol_ButtonHovered = 22
    ImGuiCol_ButtonActive = 23
    ImGuiCol_Header = 24
    ImGuiCol_HeaderHovered = 25
    ImGuiCol_HeaderActive = 26
    ImGuiCol_Separator = 27
    ImGuiCol_SeparatorHovered = 28
    ImGuiCol_SeparatorActive = 29
    ImGuiCol_ResizeGrip = 30
    ImGuiCol_ResizeGripHovered = 31
    ImGuiCol_ResizeGripActive = 32
    ImGuiCol_TabHovered = 33
    ImGuiCol_Tab = 34
    ImGuiCol_TabSelected = 35
    ImGuiCol_TabSelectedOverline = 36
    ImGuiCol_TabDimmed = 37
    ImGuiCol_TabDimmedSelected = 38
    ImGuiCol_TabDimmedSelectedOverline = 39
    ImGuiCol_DockingPreview = 40
    ImGuiCol_DockingEmptyBg = 41
    ImGuiCol_PlotLines = 42
    ImGuiCol_PlotLinesHovered = 43
    ImGuiCol_PlotHistogram = 44
    ImGuiCol_PlotHistogramHovered = 45
    ImGuiCol_TableHeaderBg = 46
    ImGuiCol_TableBorderStrong = 47
    ImGuiCol_TableBorderLight = 48
    ImGuiCol_TableRowBg = 49
    ImGuiCol_TableRowBgAlt = 50
    ImGuiCol_TextLink = 51
    ImGuiCol_TextSelectedBg = 52
    ImGuiCol_DragDropTarget = 53
    ImGuiCol_NavCursor = 54
    ImGuiCol_NavWindowingHighlight = 55
    ImGuiCol_NavWindowingDimBg = 56
    ImGuiCol_ModalWindowDimBg = 57
    ImGuiCol_COUNT = 58
    ImGuiColorEditFlags_None = 0
    ImGuiColorEditFlags_NoAlpha = 2
    ImGuiColorEditFlags_NoPicker = 4
    ImGuiColorEditFlags_NoOptions = 8
    ImGuiColorEditFlags_NoSmallPreview = 16
    ImGuiColorEditFlags_NoInputs = 32
    ImGuiColorEditFlags_NoTooltip = 64
    ImGuiColorEditFlags_NoLabel = 128
    ImGuiColorEditFlags_NoSidePreview = 256
    ImGuiColorEditFlags_NoDragDrop = 512
    ImGuiColorEditFlags_NoBorder = 1024
    ImGuiColorEditFlags_AlphaOpaque = 2048
    ImGuiColorEditFlags_AlphaNoBg = 4096
    ImGuiColorEditFlags_AlphaPreviewHalf = 8192
    ImGuiColorEditFlags_AlphaBar = 65536
    ImGuiColorEditFlags_HDR = 524288
    ImGuiColorEditFlags_DisplayRGB = 1048576
    ImGuiColorEditFlags_DisplayHSV = 2097152
    ImGuiColorEditFlags_DisplayHex = 4194304
    ImGuiColorEditFlags_Uint8 = 8388608
    ImGuiColorEditFlags_Float = 16777216
    ImGuiColorEditFlags_PickerHueBar = 33554432
    ImGuiColorEditFlags_PickerHueWheel = 67108864
    ImGuiColorEditFlags_InputRGB = 134217728
    ImGuiColorEditFlags_InputHSV = 268435456
    ImGuiColorEditFlags_DefaultOptions_ = 177209344
    ImGuiColorEditFlags_AlphaMask_ = 14338
    ImGuiColorEditFlags_DisplayMask_ = 7340032
    ImGuiColorEditFlags_DataTypeMask_ = 25165824
    ImGuiColorEditFlags_PickerMask_ = 100663296
    ImGuiColorEditFlags_InputMask_ = 402653184
    ImGuiComboFlags_CustomPreview = 1048576
    ImGuiComboFlags_None = 0
    ImGuiComboFlags_PopupAlignLeft = 1
    ImGuiComboFlags_HeightSmall = 2
    ImGuiComboFlags_HeightRegular = 4
    ImGuiComboFlags_HeightLarge = 8
    ImGuiComboFlags_HeightLargest = 16
    ImGuiComboFlags_NoArrowButton = 32
    ImGuiComboFlags_NoPreview = 64
    ImGuiComboFlags_WidthFitPreview = 128
    ImGuiComboFlags_HeightMask_ = 30
    ImGuiCond_None = 0
    ImGuiCond_Always = 1
    ImGuiCond_Once = 2
    ImGuiCond_FirstUseEver = 4
    ImGuiCond_Appearing = 8
    ImGuiConfigFlags_None = 0
    ImGuiConfigFlags_NavEnableKeyboard = 1
    ImGuiConfigFlags_NavEnableGamepad = 2
    ImGuiConfigFlags_NoMouse = 16
    ImGuiConfigFlags_NoMouseCursorChange = 32
    ImGuiConfigFlags_NoKeyboard = 64
    ImGuiConfigFlags_DockingEnable = 128
    ImGuiConfigFlags_ViewportsEnable = 1024
    ImGuiConfigFlags_DpiEnableScaleViewports = 16384
    ImGuiConfigFlags_DpiEnableScaleFonts = 32768
    ImGuiConfigFlags_IsSRGB = 1048576
    ImGuiConfigFlags_IsTouchScreen = 2097152
    ImGuiContextHookType_NewFramePre = 0
    ImGuiContextHookType_NewFramePost = 1
    ImGuiContextHookType_EndFramePre = 2
    ImGuiContextHookType_EndFramePost = 3
    ImGuiContextHookType_RenderPre = 4
    ImGuiContextHookType_RenderPost = 5
    ImGuiContextHookType_Shutdown = 6
    ImGuiContextHookType_PendingRemoval_ = 7
    ImGuiDataAuthority_Auto = 0
    ImGuiDataAuthority_DockNode = 1
    ImGuiDataAuthority_Window = 2
    ImGuiDataType_Pointer = 12
    ImGuiDataType_ID = 13
    ImGuiDataType_S8 = 0
    ImGuiDataType_U8 = 1
    ImGuiDataType_S16 = 2
    ImGuiDataType_U16 = 3
    ImGuiDataType_S32 = 4
    ImGuiDataType_U32 = 5
    ImGuiDataType_S64 = 6
    ImGuiDataType_U64 = 7
    ImGuiDataType_Float = 8
    ImGuiDataType_Double = 9
    ImGuiDataType_Bool = 10
    ImGuiDataType_String = 11
    ImGuiDataType_COUNT = 12
    ImGuiDebugLogFlags_None = 0
    ImGuiDebugLogFlags_EventError = 1
    ImGuiDebugLogFlags_EventActiveId = 2
    ImGuiDebugLogFlags_EventFocus = 4
    ImGuiDebugLogFlags_EventPopup = 8
    ImGuiDebugLogFlags_EventNav = 16
    ImGuiDebugLogFlags_EventClipper = 32
    ImGuiDebugLogFlags_EventSelection = 64
    ImGuiDebugLogFlags_EventIO = 128
    ImGuiDebugLogFlags_EventFont = 256
    ImGuiDebugLogFlags_EventInputRouting = 512
    ImGuiDebugLogFlags_EventDocking = 1024
    ImGuiDebugLogFlags_EventViewport = 2048
    ImGuiDebugLogFlags_EventMask_ = 4095
    ImGuiDebugLogFlags_OutputToTTY = 1048576
    ImGuiDebugLogFlags_OutputToTestEngine = 2097152
    ImGuiDir_None = -1
    ImGuiDir_Left = 0
    ImGuiDir_Right = 1
    ImGuiDir_Up = 2
    ImGuiDir_Down = 3
    ImGuiDir_COUNT = 4
    ImGuiDockNodeFlags_DockSpace = 1024
    ImGuiDockNodeFlags_CentralNode = 2048
    ImGuiDockNodeFlags_NoTabBar = 4096
    ImGuiDockNodeFlags_HiddenTabBar = 8192
    ImGuiDockNodeFlags_NoWindowMenuButton = 16384
    ImGuiDockNodeFlags_NoCloseButton = 32768
    ImGuiDockNodeFlags_NoResizeX = 65536
    ImGuiDockNodeFlags_NoResizeY = 131072
    ImGuiDockNodeFlags_DockedWindowsInFocusRoute = 262144
    ImGuiDockNodeFlags_NoDockingSplitOther = 524288
    ImGuiDockNodeFlags_NoDockingOverMe = 1048576
    ImGuiDockNodeFlags_NoDockingOverOther = 2097152
    ImGuiDockNodeFlags_NoDockingOverEmpty = 4194304
    ImGuiDockNodeFlags_NoDocking = 7864336
    ImGuiDockNodeFlags_SharedFlagsInheritMask_ = -1
    ImGuiDockNodeFlags_NoResizeFlagsMask_ = 196640
    ImGuiDockNodeFlags_LocalFlagsTransferMask_ = 260208
    ImGuiDockNodeFlags_SavedFlagsMask_ = 261152
    ImGuiDockNodeFlags_None = 0
    ImGuiDockNodeFlags_KeepAliveOnly = 1
    ImGuiDockNodeFlags_NoDockingOverCentralNode = 4
    ImGuiDockNodeFlags_PassthruCentralNode = 8
    ImGuiDockNodeFlags_NoDockingSplit = 16
    ImGuiDockNodeFlags_NoResize = 32
    ImGuiDockNodeFlags_AutoHideTabBar = 64
    ImGuiDockNodeFlags_NoUndocking = 128
    ImGuiDockNodeState_Unknown = 0
    ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow = 1
    ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing = 2
    ImGuiDockNodeState_HostWindowVisible = 3
    ImGuiDragDropFlags_None = 0
    ImGuiDragDropFlags_SourceNoPreviewTooltip = 1
    ImGuiDragDropFlags_SourceNoDisableHover = 2
    ImGuiDragDropFlags_SourceNoHoldToOpenOthers = 4
    ImGuiDragDropFlags_SourceAllowNullID = 8
    ImGuiDragDropFlags_SourceExtern = 16
    ImGuiDragDropFlags_PayloadAutoExpire = 32
    ImGuiDragDropFlags_PayloadNoCrossContext = 64
    ImGuiDragDropFlags_PayloadNoCrossProcess = 128
    ImGuiDragDropFlags_AcceptBeforeDelivery = 1024
    ImGuiDragDropFlags_AcceptNoDrawDefaultRect = 2048
    ImGuiDragDropFlags_AcceptNoPreviewTooltip = 4096
    ImGuiDragDropFlags_AcceptPeekOnly = 3072
    ImGuiFocusRequestFlags_None = 0
    ImGuiFocusRequestFlags_RestoreFocusedChild = 1
    ImGuiFocusRequestFlags_UnlessBelowModal = 2
    ImGuiFocusedFlags_None = 0
    ImGuiFocusedFlags_ChildWindows = 1
    ImGuiFocusedFlags_RootWindow = 2
    ImGuiFocusedFlags_AnyWindow = 4
    ImGuiFocusedFlags_NoPopupHierarchy = 8
    ImGuiFocusedFlags_DockHierarchy = 16
    ImGuiFocusedFlags_RootAndChildWindows = 3
    ImGuiFreeTypeBuilderFlags_NoHinting = 1
    ImGuiFreeTypeBuilderFlags_NoAutoHint = 2
    ImGuiFreeTypeBuilderFlags_ForceAutoHint = 4
    ImGuiFreeTypeBuilderFlags_LightHinting = 8
    ImGuiFreeTypeBuilderFlags_MonoHinting = 16
    ImGuiFreeTypeBuilderFlags_Bold = 32
    ImGuiFreeTypeBuilderFlags_Oblique = 64
    ImGuiFreeTypeBuilderFlags_Monochrome = 128
    ImGuiFreeTypeBuilderFlags_LoadColor = 256
    ImGuiFreeTypeBuilderFlags_Bitmap = 512
    ImGuiHoveredFlags_DelayMask_ = 245760
    ImGuiHoveredFlags_AllowedMaskForIsWindowHovered = 12479
    ImGuiHoveredFlags_AllowedMaskForIsItemHovered = 262048
    ImGuiHoveredFlags_None = 0
    ImGuiHoveredFlags_ChildWindows = 1
    ImGuiHoveredFlags_RootWindow = 2
    ImGuiHoveredFlags_AnyWindow = 4
    ImGuiHoveredFlags_NoPopupHierarchy = 8
    ImGuiHoveredFlags_DockHierarchy = 16
    ImGuiHoveredFlags_AllowWhenBlockedByPopup = 32
    ImGuiHoveredFlags_AllowWhenBlockedByActiveItem = 128
    ImGuiHoveredFlags_AllowWhenOverlappedByItem = 256
    ImGuiHoveredFlags_AllowWhenOverlappedByWindow = 512
    ImGuiHoveredFlags_AllowWhenDisabled = 1024
    ImGuiHoveredFlags_NoNavOverride = 2048
    ImGuiHoveredFlags_AllowWhenOverlapped = 768
    ImGuiHoveredFlags_RectOnly = 928
    ImGuiHoveredFlags_RootAndChildWindows = 3
    ImGuiHoveredFlags_ForTooltip = 4096
    ImGuiHoveredFlags_Stationary = 8192
    ImGuiHoveredFlags_DelayNone = 16384
    ImGuiHoveredFlags_DelayShort = 32768
    ImGuiHoveredFlags_DelayNormal = 65536
    ImGuiHoveredFlags_NoSharedDelay = 131072
    ImGuiInputEventType_None = 0
    ImGuiInputEventType_MousePos = 1
    ImGuiInputEventType_MouseWheel = 2
    ImGuiInputEventType_MouseButton = 3
    ImGuiInputEventType_MouseViewport = 4
    ImGuiInputEventType_Key = 5
    ImGuiInputEventType_Text = 6
    ImGuiInputEventType_Focus = 7
    ImGuiInputEventType_COUNT = 8
    ImGuiInputFlags_RepeatRateDefault = 2
    ImGuiInputFlags_RepeatRateNavMove = 4
    ImGuiInputFlags_RepeatRateNavTweak = 8
    ImGuiInputFlags_RepeatUntilRelease = 16
    ImGuiInputFlags_RepeatUntilKeyModsChange = 32
    ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone = 64
    ImGuiInputFlags_RepeatUntilOtherKeyPress = 128
    ImGuiInputFlags_LockThisFrame = 1048576
    ImGuiInputFlags_LockUntilRelease = 2097152
    ImGuiInputFlags_CondHovered = 4194304
    ImGuiInputFlags_CondActive = 8388608
    ImGuiInputFlags_CondDefault_ = 12582912
    ImGuiInputFlags_RepeatRateMask_ = 14
    ImGuiInputFlags_RepeatUntilMask_ = 240
    ImGuiInputFlags_RepeatMask_ = 255
    ImGuiInputFlags_CondMask_ = 12582912
    ImGuiInputFlags_RouteTypeMask_ = 15360
    ImGuiInputFlags_RouteOptionsMask_ = 245760
    ImGuiInputFlags_SupportedByIsKeyPressed = 255
    ImGuiInputFlags_SupportedByIsMouseClicked = 1
    ImGuiInputFlags_SupportedByShortcut = 261375
    ImGuiInputFlags_SupportedBySetNextItemShortcut = 523519
    ImGuiInputFlags_SupportedBySetKeyOwner = 3145728
    ImGuiInputFlags_SupportedBySetItemKeyOwner = 15728640
    ImGuiInputFlags_None = 0
    ImGuiInputFlags_Repeat = 1
    ImGuiInputFlags_RouteActive = 1024
    ImGuiInputFlags_RouteFocused = 2048
    ImGuiInputFlags_RouteGlobal = 4096
    ImGuiInputFlags_RouteAlways = 8192
    ImGuiInputFlags_RouteOverFocused = 16384
    ImGuiInputFlags_RouteOverActive = 32768
    ImGuiInputFlags_RouteUnlessBgFocused = 65536
    ImGuiInputFlags_RouteFromRootWindow = 131072
    ImGuiInputFlags_Tooltip = 262144
    ImGuiInputSource_None = 0
    ImGuiInputSource_Mouse = 1
    ImGuiInputSource_Keyboard = 2
    ImGuiInputSource_Gamepad = 3
    ImGuiInputSource_COUNT = 4
    ImGuiInputTextFlags_Multiline = 67108864
    ImGuiInputTextFlags_MergedItem = 134217728
    ImGuiInputTextFlags_LocalizeDecimalPoint = 268435456
    ImGuiInputTextFlags_None = 0
    ImGuiInputTextFlags_CharsDecimal = 1
    ImGuiInputTextFlags_CharsHexadecimal = 2
    ImGuiInputTextFlags_CharsScientific = 4
    ImGuiInputTextFlags_CharsUppercase = 8
    ImGuiInputTextFlags_CharsNoBlank = 16
    ImGuiInputTextFlags_AllowTabInput = 32
    ImGuiInputTextFlags_EnterReturnsTrue = 64
    ImGuiInputTextFlags_EscapeClearsAll = 128
    ImGuiInputTextFlags_CtrlEnterForNewLine = 256
    ImGuiInputTextFlags_ReadOnly = 512
    ImGuiInputTextFlags_Password = 1024
    ImGuiInputTextFlags_AlwaysOverwrite = 2048
    ImGuiInputTextFlags_AutoSelectAll = 4096
    ImGuiInputTextFlags_ParseEmptyRefVal = 8192
    ImGuiInputTextFlags_DisplayEmptyRefVal = 16384
    ImGuiInputTextFlags_NoHorizontalScroll = 32768
    ImGuiInputTextFlags_NoUndoRedo = 65536
    ImGuiInputTextFlags_ElideLeft = 131072
    ImGuiInputTextFlags_CallbackCompletion = 262144
    ImGuiInputTextFlags_CallbackHistory = 524288
    ImGuiInputTextFlags_CallbackAlways = 1048576
    ImGuiInputTextFlags_CallbackCharFilter = 2097152
    ImGuiInputTextFlags_CallbackResize = 4194304
    ImGuiInputTextFlags_CallbackEdit = 8388608
    ImGuiItemFlags_Disabled = 1024
    ImGuiItemFlags_ReadOnly = 2048
    ImGuiItemFlags_MixedValue = 4096
    ImGuiItemFlags_NoWindowHoverableCheck = 8192
    ImGuiItemFlags_AllowOverlap = 16384
    ImGuiItemFlags_NoNavDisableMouseHover = 32768
    ImGuiItemFlags_NoMarkEdited = 65536
    ImGuiItemFlags_Inputable = 1048576
    ImGuiItemFlags_HasSelectionUserData = 2097152
    ImGuiItemFlags_IsMultiSelect = 4194304
    ImGuiItemFlags_Default_ = 16
    ImGuiItemFlags_None = 0
    ImGuiItemFlags_NoTabStop = 1
    ImGuiItemFlags_NoNav = 2
    ImGuiItemFlags_NoNavDefaultFocus = 4
    ImGuiItemFlags_ButtonRepeat = 8
    ImGuiItemFlags_AutoClosePopups = 16
    ImGuiItemFlags_AllowDuplicateId = 32
    ImGuiItemStatusFlags_None = 0
    ImGuiItemStatusFlags_HoveredRect = 1
    ImGuiItemStatusFlags_HasDisplayRect = 2
    ImGuiItemStatusFlags_Edited = 4
    ImGuiItemStatusFlags_ToggledSelection = 8
    ImGuiItemStatusFlags_ToggledOpen = 16
    ImGuiItemStatusFlags_HasDeactivated = 32
    ImGuiItemStatusFlags_Deactivated = 64
    ImGuiItemStatusFlags_HoveredWindow = 128
    ImGuiItemStatusFlags_Visible = 256
    ImGuiItemStatusFlags_HasClipRect = 512
    ImGuiItemStatusFlags_HasShortcut = 1024
    ImGuiKey_None = 0
    ImGuiKey_NamedKey_BEGIN = 512
    ImGuiKey_Tab = 512
    ImGuiKey_LeftArrow = 513
    ImGuiKey_RightArrow = 514
    ImGuiKey_UpArrow = 515
    ImGuiKey_DownArrow = 516
    ImGuiKey_PageUp = 517
    ImGuiKey_PageDown = 518
    ImGuiKey_Home = 519
    ImGuiKey_End = 520
    ImGuiKey_Insert = 521
    ImGuiKey_Delete = 522
    ImGuiKey_Backspace = 523
    ImGuiKey_Space = 524
    ImGuiKey_Enter = 525
    ImGuiKey_Escape = 526
    ImGuiKey_LeftCtrl = 527
    ImGuiKey_LeftShift = 528
    ImGuiKey_LeftAlt = 529
    ImGuiKey_LeftSuper = 530
    ImGuiKey_RightCtrl = 531
    ImGuiKey_RightShift = 532
    ImGuiKey_RightAlt = 533
    ImGuiKey_RightSuper = 534
    ImGuiKey_Menu = 535
    ImGuiKey_0 = 536
    ImGuiKey_1 = 537
    ImGuiKey_2 = 538
    ImGuiKey_3 = 539
    ImGuiKey_4 = 540
    ImGuiKey_5 = 541
    ImGuiKey_6 = 542
    ImGuiKey_7 = 543
    ImGuiKey_8 = 544
    ImGuiKey_9 = 545
    ImGuiKey_A = 546
    ImGuiKey_B = 547
    ImGuiKey_C = 548
    ImGuiKey_D = 549
    ImGuiKey_E = 550
    ImGuiKey_F = 551
    ImGuiKey_G = 552
    ImGuiKey_H = 553
    ImGuiKey_I = 554
    ImGuiKey_J = 555
    ImGuiKey_K = 556
    ImGuiKey_L = 557
    ImGuiKey_M = 558
    ImGuiKey_N = 559
    ImGuiKey_O = 560
    ImGuiKey_P = 561
    ImGuiKey_Q = 562
    ImGuiKey_R = 563
    ImGuiKey_S = 564
    ImGuiKey_T = 565
    ImGuiKey_U = 566
    ImGuiKey_V = 567
    ImGuiKey_W = 568
    ImGuiKey_X = 569
    ImGuiKey_Y = 570
    ImGuiKey_Z = 571
    ImGuiKey_F1 = 572
    ImGuiKey_F2 = 573
    ImGuiKey_F3 = 574
    ImGuiKey_F4 = 575
    ImGuiKey_F5 = 576
    ImGuiKey_F6 = 577
    ImGuiKey_F7 = 578
    ImGuiKey_F8 = 579
    ImGuiKey_F9 = 580
    ImGuiKey_F10 = 581
    ImGuiKey_F11 = 582
    ImGuiKey_F12 = 583
    ImGuiKey_F13 = 584
    ImGuiKey_F14 = 585
    ImGuiKey_F15 = 586
    ImGuiKey_F16 = 587
    ImGuiKey_F17 = 588
    ImGuiKey_F18 = 589
    ImGuiKey_F19 = 590
    ImGuiKey_F20 = 591
    ImGuiKey_F21 = 592
    ImGuiKey_F22 = 593
    ImGuiKey_F23 = 594
    ImGuiKey_F24 = 595
    ImGuiKey_Apostrophe = 596
    ImGuiKey_Comma = 597
    ImGuiKey_Minus = 598
    ImGuiKey_Period = 599
    ImGuiKey_Slash = 600
    ImGuiKey_Semicolon = 601
    ImGuiKey_Equal = 602
    ImGuiKey_LeftBracket = 603
    ImGuiKey_Backslash = 604
    ImGuiKey_RightBracket = 605
    ImGuiKey_GraveAccent = 606
    ImGuiKey_CapsLock = 607
    ImGuiKey_ScrollLock = 608
    ImGuiKey_NumLock = 609
    ImGuiKey_PrintScreen = 610
    ImGuiKey_Pause = 611
    ImGuiKey_Keypad0 = 612
    ImGuiKey_Keypad1 = 613
    ImGuiKey_Keypad2 = 614
    ImGuiKey_Keypad3 = 615
    ImGuiKey_Keypad4 = 616
    ImGuiKey_Keypad5 = 617
    ImGuiKey_Keypad6 = 618
    ImGuiKey_Keypad7 = 619
    ImGuiKey_Keypad8 = 620
    ImGuiKey_Keypad9 = 621
    ImGuiKey_KeypadDecimal = 622
    ImGuiKey_KeypadDivide = 623
    ImGuiKey_KeypadMultiply = 624
    ImGuiKey_KeypadSubtract = 625
    ImGuiKey_KeypadAdd = 626
    ImGuiKey_KeypadEnter = 627
    ImGuiKey_KeypadEqual = 628
    ImGuiKey_AppBack = 629
    ImGuiKey_AppForward = 630
    ImGuiKey_Oem102 = 631
    ImGuiKey_GamepadStart = 632
    ImGuiKey_GamepadBack = 633
    ImGuiKey_GamepadFaceLeft = 634
    ImGuiKey_GamepadFaceRight = 635
    ImGuiKey_GamepadFaceUp = 636
    ImGuiKey_GamepadFaceDown = 637
    ImGuiKey_GamepadDpadLeft = 638
    ImGuiKey_GamepadDpadRight = 639
    ImGuiKey_GamepadDpadUp = 640
    ImGuiKey_GamepadDpadDown = 641
    ImGuiKey_GamepadL1 = 642
    ImGuiKey_GamepadR1 = 643
    ImGuiKey_GamepadL2 = 644
    ImGuiKey_GamepadR2 = 645
    ImGuiKey_GamepadL3 = 646
    ImGuiKey_GamepadR3 = 647
    ImGuiKey_GamepadLStickLeft = 648
    ImGuiKey_GamepadLStickRight = 649
    ImGuiKey_GamepadLStickUp = 650
    ImGuiKey_GamepadLStickDown = 651
    ImGuiKey_GamepadRStickLeft = 652
    ImGuiKey_GamepadRStickRight = 653
    ImGuiKey_GamepadRStickUp = 654
    ImGuiKey_GamepadRStickDown = 655
    ImGuiKey_MouseLeft = 656
    ImGuiKey_MouseRight = 657
    ImGuiKey_MouseMiddle = 658
    ImGuiKey_MouseX1 = 659
    ImGuiKey_MouseX2 = 660
    ImGuiKey_MouseWheelX = 661
    ImGuiKey_MouseWheelY = 662
    ImGuiKey_ReservedForModCtrl = 663
    ImGuiKey_ReservedForModShift = 664
    ImGuiKey_ReservedForModAlt = 665
    ImGuiKey_ReservedForModSuper = 666
    ImGuiKey_NamedKey_END = 667
    ImGuiMod_None = 0
    ImGuiMod_Ctrl = 4096
    ImGuiMod_Shift = 8192
    ImGuiMod_Alt = 16384
    ImGuiMod_Super = 32768
    ImGuiMod_Mask_ = 61440
    ImGuiKey_NamedKey_COUNT = 155
    ImGuiLayoutType_Horizontal = 0
    ImGuiLayoutType_Vertical = 1
    ImGuiLocKey_VersionStr = 0
    ImGuiLocKey_TableSizeOne = 1
    ImGuiLocKey_TableSizeAllFit = 2
    ImGuiLocKey_TableSizeAllDefault = 3
    ImGuiLocKey_TableResetOrder = 4
    ImGuiLocKey_WindowingMainMenuBar = 5
    ImGuiLocKey_WindowingPopup = 6
    ImGuiLocKey_WindowingUntitled = 7
    ImGuiLocKey_OpenLink_s = 8
    ImGuiLocKey_CopyLink = 9
    ImGuiLocKey_DockingHideTabBar = 10
    ImGuiLocKey_DockingHoldShiftToDock = 11
    ImGuiLocKey_DockingDragToUndockOrMoveNode = 12
    ImGuiLocKey_COUNT = 13
    ImGuiLogFlags_None = 0
    ImGuiLogFlags_OutputTTY = 1
    ImGuiLogFlags_OutputFile = 2
    ImGuiLogFlags_OutputBuffer = 4
    ImGuiLogFlags_OutputClipboard = 8
    ImGuiLogFlags_OutputMask_ = 15
    ImGuiMouseButton_Left = 0
    ImGuiMouseButton_Right = 1
    ImGuiMouseButton_Middle = 2
    ImGuiMouseButton_COUNT = 5
    ImGuiMouseCursor_None = -1
    ImGuiMouseCursor_Arrow = 0
    ImGuiMouseCursor_TextInput = 1
    ImGuiMouseCursor_ResizeAll = 2
    ImGuiMouseCursor_ResizeNS = 3
    ImGuiMouseCursor_ResizeEW = 4
    ImGuiMouseCursor_ResizeNESW = 5
    ImGuiMouseCursor_ResizeNWSE = 6
    ImGuiMouseCursor_Hand = 7
    ImGuiMouseCursor_Wait = 8
    ImGuiMouseCursor_Progress = 9
    ImGuiMouseCursor_NotAllowed = 10
    ImGuiMouseCursor_COUNT = 11
    ImGuiMouseSource_Mouse = 0
    ImGuiMouseSource_TouchScreen = 1
    ImGuiMouseSource_Pen = 2
    ImGuiMouseSource_COUNT = 3
    ImGuiMultiSelectFlags_None = 0
    ImGuiMultiSelectFlags_SingleSelect = 1
    ImGuiMultiSelectFlags_NoSelectAll = 2
    ImGuiMultiSelectFlags_NoRangeSelect = 4
    ImGuiMultiSelectFlags_NoAutoSelect = 8
    ImGuiMultiSelectFlags_NoAutoClear = 16
    ImGuiMultiSelectFlags_NoAutoClearOnReselect = 32
    ImGuiMultiSelectFlags_BoxSelect1d = 64
    ImGuiMultiSelectFlags_BoxSelect2d = 128
    ImGuiMultiSelectFlags_BoxSelectNoScroll = 256
    ImGuiMultiSelectFlags_ClearOnEscape = 512
    ImGuiMultiSelectFlags_ClearOnClickVoid = 1024
    ImGuiMultiSelectFlags_ScopeWindow = 2048
    ImGuiMultiSelectFlags_ScopeRect = 4096
    ImGuiMultiSelectFlags_SelectOnClick = 8192
    ImGuiMultiSelectFlags_SelectOnClickRelease = 16384
    ImGuiMultiSelectFlags_NavWrapX = 65536
    ImGuiNavLayer_Main = 0
    ImGuiNavLayer_Menu = 1
    ImGuiNavLayer_COUNT = 2
    ImGuiNavMoveFlags_None = 0
    ImGuiNavMoveFlags_LoopX = 1
    ImGuiNavMoveFlags_LoopY = 2
    ImGuiNavMoveFlags_WrapX = 4
    ImGuiNavMoveFlags_WrapY = 8
    ImGuiNavMoveFlags_WrapMask_ = 15
    ImGuiNavMoveFlags_AllowCurrentNavId = 16
    ImGuiNavMoveFlags_AlsoScoreVisibleSet = 32
    ImGuiNavMoveFlags_ScrollToEdgeY = 64
    ImGuiNavMoveFlags_Forwarded = 128
    ImGuiNavMoveFlags_DebugNoResult = 256
    ImGuiNavMoveFlags_FocusApi = 512
    ImGuiNavMoveFlags_IsTabbing = 1024
    ImGuiNavMoveFlags_IsPageMove = 2048
    ImGuiNavMoveFlags_Activate = 4096
    ImGuiNavMoveFlags_NoSelect = 8192
    ImGuiNavMoveFlags_NoSetNavCursorVisible = 16384
    ImGuiNavMoveFlags_NoClearActiveId = 32768
    ImGuiNavRenderCursorFlags_None = 0
    ImGuiNavRenderCursorFlags_Compact = 2
    ImGuiNavRenderCursorFlags_AlwaysDraw = 4
    ImGuiNavRenderCursorFlags_NoRounding = 8
    ImGuiNextItemDataFlags_None = 0
    ImGuiNextItemDataFlags_HasWidth = 1
    ImGuiNextItemDataFlags_HasOpen = 2
    ImGuiNextItemDataFlags_HasShortcut = 4
    ImGuiNextItemDataFlags_HasRefVal = 8
    ImGuiNextItemDataFlags_HasStorageID = 16
    ImGuiNextWindowDataFlags_None = 0
    ImGuiNextWindowDataFlags_HasPos = 1
    ImGuiNextWindowDataFlags_HasSize = 2
    ImGuiNextWindowDataFlags_HasContentSize = 4
    ImGuiNextWindowDataFlags_HasCollapsed = 8
    ImGuiNextWindowDataFlags_HasSizeConstraint = 16
    ImGuiNextWindowDataFlags_HasFocus = 32
    ImGuiNextWindowDataFlags_HasBgAlpha = 64
    ImGuiNextWindowDataFlags_HasScroll = 128
    ImGuiNextWindowDataFlags_HasWindowFlags = 256
    ImGuiNextWindowDataFlags_HasChildFlags = 512
    ImGuiNextWindowDataFlags_HasRefreshPolicy = 1024
    ImGuiNextWindowDataFlags_HasViewport = 2048
    ImGuiNextWindowDataFlags_HasDock = 4096
    ImGuiNextWindowDataFlags_HasWindowClass = 8192
    ImGuiOldColumnFlags_None = 0
    ImGuiOldColumnFlags_NoBorder = 1
    ImGuiOldColumnFlags_NoResize = 2
    ImGuiOldColumnFlags_NoPreserveWidths = 4
    ImGuiOldColumnFlags_NoForceWithinWindow = 8
    ImGuiOldColumnFlags_GrowParentContentsSize = 16
    ImGuiPlotType_Lines = 0
    ImGuiPlotType_Histogram = 1
    ImGuiPopupFlags_None = 0
    ImGuiPopupFlags_MouseButtonLeft = 0
    ImGuiPopupFlags_MouseButtonRight = 1
    ImGuiPopupFlags_MouseButtonMiddle = 2
    ImGuiPopupFlags_MouseButtonMask_ = 31
    ImGuiPopupFlags_MouseButtonDefault_ = 1
    ImGuiPopupFlags_NoReopen = 32
    ImGuiPopupFlags_NoOpenOverExistingPopup = 128
    ImGuiPopupFlags_NoOpenOverItems = 256
    ImGuiPopupFlags_AnyPopupId = 1024
    ImGuiPopupFlags_AnyPopupLevel = 2048
    ImGuiPopupFlags_AnyPopup = 3072
    ImGuiPopupPositionPolicy_Default = 0
    ImGuiPopupPositionPolicy_ComboBox = 1
    ImGuiPopupPositionPolicy_Tooltip = 2
    ImGuiScrollFlags_None = 0
    ImGuiScrollFlags_KeepVisibleEdgeX = 1
    ImGuiScrollFlags_KeepVisibleEdgeY = 2
    ImGuiScrollFlags_KeepVisibleCenterX = 4
    ImGuiScrollFlags_KeepVisibleCenterY = 8
    ImGuiScrollFlags_AlwaysCenterX = 16
    ImGuiScrollFlags_AlwaysCenterY = 32
    ImGuiScrollFlags_NoScrollParent = 64
    ImGuiScrollFlags_MaskX_ = 21
    ImGuiScrollFlags_MaskY_ = 42
    ImGuiSelectableFlags_NoHoldingActiveID = 1048576
    ImGuiSelectableFlags_SelectOnNav = 2097152
    ImGuiSelectableFlags_SelectOnClick = 4194304
    ImGuiSelectableFlags_SelectOnRelease = 8388608
    ImGuiSelectableFlags_SpanAvailWidth = 16777216
    ImGuiSelectableFlags_SetNavIdOnHover = 33554432
    ImGuiSelectableFlags_NoPadWithHalfSpacing = 67108864
    ImGuiSelectableFlags_NoSetKeyOwner = 134217728
    ImGuiSelectableFlags_None = 0
    ImGuiSelectableFlags_NoAutoClosePopups = 1
    ImGuiSelectableFlags_SpanAllColumns = 2
    ImGuiSelectableFlags_AllowDoubleClick = 4
    ImGuiSelectableFlags_Disabled = 8
    ImGuiSelectableFlags_AllowOverlap = 16
    ImGuiSelectableFlags_Highlight = 32
    ImGuiSelectionRequestType_None = 0
    ImGuiSelectionRequestType_SetAll = 1
    ImGuiSelectionRequestType_SetRange = 2
    ImGuiSeparatorFlags_None = 0
    ImGuiSeparatorFlags_Horizontal = 1
    ImGuiSeparatorFlags_Vertical = 2
    ImGuiSeparatorFlags_SpanAllColumns = 4
    ImGuiSliderFlags_Vertical = 1048576
    ImGuiSliderFlags_ReadOnly = 2097152
    ImGuiSliderFlags_None = 0
    ImGuiSliderFlags_Logarithmic = 32
    ImGuiSliderFlags_NoRoundToFormat = 64
    ImGuiSliderFlags_NoInput = 128
    ImGuiSliderFlags_WrapAround = 256
    ImGuiSliderFlags_ClampOnInput = 512
    ImGuiSliderFlags_ClampZeroRange = 1024
    ImGuiSliderFlags_NoSpeedTweaks = 2048
    ImGuiSliderFlags_AlwaysClamp = 1536
    ImGuiSliderFlags_InvalidMask_ = 1879048207
    ImGuiSortDirection_None = 0
    ImGuiSortDirection_Ascending = 1
    ImGuiSortDirection_Descending = 2
    ImGuiStyleVar_Alpha = 0
    ImGuiStyleVar_DisabledAlpha = 1
    ImGuiStyleVar_WindowPadding = 2
    ImGuiStyleVar_WindowRounding = 3
    ImGuiStyleVar_WindowBorderSize = 4
    ImGuiStyleVar_WindowMinSize = 5
    ImGuiStyleVar_WindowTitleAlign = 6
    ImGuiStyleVar_ChildRounding = 7
    ImGuiStyleVar_ChildBorderSize = 8
    ImGuiStyleVar_PopupRounding = 9
    ImGuiStyleVar_PopupBorderSize = 10
    ImGuiStyleVar_FramePadding = 11
    ImGuiStyleVar_FrameRounding = 12
    ImGuiStyleVar_FrameBorderSize = 13
    ImGuiStyleVar_ItemSpacing = 14
    ImGuiStyleVar_ItemInnerSpacing = 15
    ImGuiStyleVar_IndentSpacing = 16
    ImGuiStyleVar_CellPadding = 17
    ImGuiStyleVar_ScrollbarSize = 18
    ImGuiStyleVar_ScrollbarRounding = 19
    ImGuiStyleVar_GrabMinSize = 20
    ImGuiStyleVar_GrabRounding = 21
    ImGuiStyleVar_ImageBorderSize = 22
    ImGuiStyleVar_TabRounding = 23
    ImGuiStyleVar_TabBorderSize = 24
    ImGuiStyleVar_TabBarBorderSize = 25
    ImGuiStyleVar_TabBarOverlineSize = 26
    ImGuiStyleVar_TableAngledHeadersAngle = 27
    ImGuiStyleVar_TableAngledHeadersTextAlign = 28
    ImGuiStyleVar_ButtonTextAlign = 29
    ImGuiStyleVar_SelectableTextAlign = 30
    ImGuiStyleVar_SeparatorTextBorderSize = 31
    ImGuiStyleVar_SeparatorTextAlign = 32
    ImGuiStyleVar_SeparatorTextPadding = 33
    ImGuiStyleVar_DockingSeparatorSize = 34
    ImGuiStyleVar_COUNT = 35
    ImGuiTabBarFlags_DockNode = 1048576
    ImGuiTabBarFlags_IsFocused = 2097152
    ImGuiTabBarFlags_SaveSettings = 4194304
    ImGuiTabBarFlags_None = 0
    ImGuiTabBarFlags_Reorderable = 1
    ImGuiTabBarFlags_AutoSelectNewTabs = 2
    ImGuiTabBarFlags_TabListPopupButton = 4
    ImGuiTabBarFlags_NoCloseWithMiddleMouseButton = 8
    ImGuiTabBarFlags_NoTabListScrollingButtons = 16
    ImGuiTabBarFlags_NoTooltip = 32
    ImGuiTabBarFlags_DrawSelectedOverline = 64
    ImGuiTabBarFlags_FittingPolicyResizeDown = 128
    ImGuiTabBarFlags_FittingPolicyScroll = 256
    ImGuiTabBarFlags_FittingPolicyMask_ = 384
    ImGuiTabBarFlags_FittingPolicyDefault_ = 128
    ImGuiTabItemFlags_SectionMask_ = 192
    ImGuiTabItemFlags_NoCloseButton = 1048576
    ImGuiTabItemFlags_Button = 2097152
    ImGuiTabItemFlags_Invisible = 4194304
    ImGuiTabItemFlags_Unsorted = 8388608
    ImGuiTabItemFlags_None = 0
    ImGuiTabItemFlags_UnsavedDocument = 1
    ImGuiTabItemFlags_SetSelected = 2
    ImGuiTabItemFlags_NoCloseWithMiddleMouseButton = 4
    ImGuiTabItemFlags_NoPushId = 8
    ImGuiTabItemFlags_NoTooltip = 16
    ImGuiTabItemFlags_NoReorder = 32
    ImGuiTabItemFlags_Leading = 64
    ImGuiTabItemFlags_Trailing = 128
    ImGuiTabItemFlags_NoAssumedClosure = 256
    ImGuiTableBgTarget_None = 0
    ImGuiTableBgTarget_RowBg0 = 1
    ImGuiTableBgTarget_RowBg1 = 2
    ImGuiTableBgTarget_CellBg = 3
    ImGuiTableColumnFlags_None = 0
    ImGuiTableColumnFlags_Disabled = 1
    ImGuiTableColumnFlags_DefaultHide = 2
    ImGuiTableColumnFlags_DefaultSort = 4
    ImGuiTableColumnFlags_WidthStretch = 8
    ImGuiTableColumnFlags_WidthFixed = 16
    ImGuiTableColumnFlags_NoResize = 32
    ImGuiTableColumnFlags_NoReorder = 64
    ImGuiTableColumnFlags_NoHide = 128
    ImGuiTableColumnFlags_NoClip = 256
    ImGuiTableColumnFlags_NoSort = 512
    ImGuiTableColumnFlags_NoSortAscending = 1024
    ImGuiTableColumnFlags_NoSortDescending = 2048
    ImGuiTableColumnFlags_NoHeaderLabel = 4096
    ImGuiTableColumnFlags_NoHeaderWidth = 8192
    ImGuiTableColumnFlags_PreferSortAscending = 16384
    ImGuiTableColumnFlags_PreferSortDescending = 32768
    ImGuiTableColumnFlags_IndentEnable = 65536
    ImGuiTableColumnFlags_IndentDisable = 131072
    ImGuiTableColumnFlags_AngledHeader = 262144
    ImGuiTableColumnFlags_IsEnabled = 16777216
    ImGuiTableColumnFlags_IsVisible = 33554432
    ImGuiTableColumnFlags_IsSorted = 67108864
    ImGuiTableColumnFlags_IsHovered = 134217728
    ImGuiTableColumnFlags_WidthMask_ = 24
    ImGuiTableColumnFlags_IndentMask_ = 196608
    ImGuiTableColumnFlags_StatusMask_ = 251658240
    ImGuiTableColumnFlags_NoDirectResize_ = 1073741824
    ImGuiTableFlags_None = 0
    ImGuiTableFlags_Resizable = 1
    ImGuiTableFlags_Reorderable = 2
    ImGuiTableFlags_Hideable = 4
    ImGuiTableFlags_Sortable = 8
    ImGuiTableFlags_NoSavedSettings = 16
    ImGuiTableFlags_ContextMenuInBody = 32
    ImGuiTableFlags_RowBg = 64
    ImGuiTableFlags_BordersInnerH = 128
    ImGuiTableFlags_BordersOuterH = 256
    ImGuiTableFlags_BordersInnerV = 512
    ImGuiTableFlags_BordersOuterV = 1024
    ImGuiTableFlags_BordersH = 384
    ImGuiTableFlags_BordersV = 1536
    ImGuiTableFlags_BordersInner = 640
    ImGuiTableFlags_BordersOuter = 1280
    ImGuiTableFlags_Borders = 1920
    ImGuiTableFlags_NoBordersInBody = 2048
    ImGuiTableFlags_NoBordersInBodyUntilResize = 4096
    ImGuiTableFlags_SizingFixedFit = 8192
    ImGuiTableFlags_SizingFixedSame = 16384
    ImGuiTableFlags_SizingStretchProp = 24576
    ImGuiTableFlags_SizingStretchSame = 32768
    ImGuiTableFlags_NoHostExtendX = 65536
    ImGuiTableFlags_NoHostExtendY = 131072
    ImGuiTableFlags_NoKeepColumnsVisible = 262144
    ImGuiTableFlags_PreciseWidths = 524288
    ImGuiTableFlags_NoClip = 1048576
    ImGuiTableFlags_PadOuterX = 2097152
    ImGuiTableFlags_NoPadOuterX = 4194304
    ImGuiTableFlags_NoPadInnerX = 8388608
    ImGuiTableFlags_ScrollX = 16777216
    ImGuiTableFlags_ScrollY = 33554432
    ImGuiTableFlags_SortMulti = 67108864
    ImGuiTableFlags_SortTristate = 134217728
    ImGuiTableFlags_HighlightHoveredColumn = 268435456
    ImGuiTableFlags_SizingMask_ = 57344
    ImGuiTableRowFlags_None = 0
    ImGuiTableRowFlags_Headers = 1
    ImGuiTextFlags_None = 0
    ImGuiTextFlags_NoWidthForLargeClippedText = 1
    ImGuiTooltipFlags_None = 0
    ImGuiTooltipFlags_OverridePrevious = 2
    ImGuiTreeNodeFlags_ClipLabelForTrailingButton = 268435456
    ImGuiTreeNodeFlags_UpsideDownArrow = 536870912
    ImGuiTreeNodeFlags_OpenOnMask_ = 192
    ImGuiTreeNodeFlags_None = 0
    ImGuiTreeNodeFlags_Selected = 1
    ImGuiTreeNodeFlags_Framed = 2
    ImGuiTreeNodeFlags_AllowOverlap = 4
    ImGuiTreeNodeFlags_NoTreePushOnOpen = 8
    ImGuiTreeNodeFlags_NoAutoOpenOnLog = 16
    ImGuiTreeNodeFlags_DefaultOpen = 32
    ImGuiTreeNodeFlags_OpenOnDoubleClick = 64
    ImGuiTreeNodeFlags_OpenOnArrow = 128
    ImGuiTreeNodeFlags_Leaf = 256
    ImGuiTreeNodeFlags_Bullet = 512
    ImGuiTreeNodeFlags_FramePadding = 1024
    ImGuiTreeNodeFlags_SpanAvailWidth = 2048
    ImGuiTreeNodeFlags_SpanFullWidth = 4096
    ImGuiTreeNodeFlags_SpanLabelWidth = 8192
    ImGuiTreeNodeFlags_SpanAllColumns = 16384
    ImGuiTreeNodeFlags_LabelSpanAllColumns = 32768
    ImGuiTreeNodeFlags_NavLeftJumpsBackHere = 131072
    ImGuiTreeNodeFlags_CollapsingHeader = 26
    ImGuiTypingSelectFlags_None = 0
    ImGuiTypingSelectFlags_AllowBackspace = 1
    ImGuiTypingSelectFlags_AllowSingleCharMode = 2
    ImGuiViewportFlags_None = 0
    ImGuiViewportFlags_IsPlatformWindow = 1
    ImGuiViewportFlags_IsPlatformMonitor = 2
    ImGuiViewportFlags_OwnedByApp = 4
    ImGuiViewportFlags_NoDecoration = 8
    ImGuiViewportFlags_NoTaskBarIcon = 16
    ImGuiViewportFlags_NoFocusOnAppearing = 32
    ImGuiViewportFlags_NoFocusOnClick = 64
    ImGuiViewportFlags_NoInputs = 128
    ImGuiViewportFlags_NoRendererClear = 256
    ImGuiViewportFlags_NoAutoMerge = 512
    ImGuiViewportFlags_TopMost = 1024
    ImGuiViewportFlags_CanHostOtherWindows = 2048
    ImGuiViewportFlags_IsMinimized = 4096
    ImGuiViewportFlags_IsFocused = 8192
    ImGuiWindowDockStyleCol_Text = 0
    ImGuiWindowDockStyleCol_TabHovered = 1
    ImGuiWindowDockStyleCol_TabFocused = 2
    ImGuiWindowDockStyleCol_TabSelected = 3
    ImGuiWindowDockStyleCol_TabSelectedOverline = 4
    ImGuiWindowDockStyleCol_TabDimmed = 5
    ImGuiWindowDockStyleCol_TabDimmedSelected = 6
    ImGuiWindowDockStyleCol_TabDimmedSelectedOverline = 7
    ImGuiWindowDockStyleCol_COUNT = 8
    ImGuiWindowFlags_None = 0
    ImGuiWindowFlags_NoTitleBar = 1
    ImGuiWindowFlags_NoResize = 2
    ImGuiWindowFlags_NoMove = 4
    ImGuiWindowFlags_NoScrollbar = 8
    ImGuiWindowFlags_NoScrollWithMouse = 16
    ImGuiWindowFlags_NoCollapse = 32
    ImGuiWindowFlags_AlwaysAutoResize = 64
    ImGuiWindowFlags_NoBackground = 128
    ImGuiWindowFlags_NoSavedSettings = 256
    ImGuiWindowFlags_NoMouseInputs = 512
    ImGuiWindowFlags_MenuBar = 1024
    ImGuiWindowFlags_HorizontalScrollbar = 2048
    ImGuiWindowFlags_NoFocusOnAppearing = 4096
    ImGuiWindowFlags_NoBringToFrontOnFocus = 8192
    ImGuiWindowFlags_AlwaysVerticalScrollbar = 16384
    ImGuiWindowFlags_AlwaysHorizontalScrollbar = 32768
    ImGuiWindowFlags_NoNavInputs = 65536
    ImGuiWindowFlags_NoNavFocus = 131072
    ImGuiWindowFlags_UnsavedDocument = 262144
    ImGuiWindowFlags_NoDocking = 524288
    ImGuiWindowFlags_NoNav = 196608
    ImGuiWindowFlags_NoDecoration = 43
    ImGuiWindowFlags_NoInputs = 197120
    ImGuiWindowFlags_DockNodeHost = 8388608
    ImGuiWindowFlags_ChildWindow = 16777216
    ImGuiWindowFlags_Tooltip = 33554432
    ImGuiWindowFlags_Popup = 67108864
    ImGuiWindowFlags_Modal = 134217728
    ImGuiWindowFlags_ChildMenu = 268435456
    ImGuiWindowRefreshFlags_None = 0
    ImGuiWindowRefreshFlags_TryToAvoidRefresh = 1
    ImGuiWindowRefreshFlags_RefreshOnHover = 2
    ImGuiWindowRefreshFlags_RefreshOnFocus = 4
  end

  module DrawFlags
    None = Native::ImDrawFlags_None
    Closed = Native::ImDrawFlags_Closed
    RoundCornersTopLeft = Native::ImDrawFlags_RoundCornersTopLeft
    RoundCornersTopRight = Native::ImDrawFlags_RoundCornersTopRight
    RoundCornersBottomLeft = Native::ImDrawFlags_RoundCornersBottomLeft
    RoundCornersBottomRight = Native::ImDrawFlags_RoundCornersBottomRight
    RoundCornersNone = Native::ImDrawFlags_RoundCornersNone
    RoundCornersTop = Native::ImDrawFlags_RoundCornersTop
    RoundCornersBottom = Native::ImDrawFlags_RoundCornersBottom
    RoundCornersLeft = Native::ImDrawFlags_RoundCornersLeft
    RoundCornersRight = Native::ImDrawFlags_RoundCornersRight
    RoundCornersAll = Native::ImDrawFlags_RoundCornersAll
    RoundCornersDefault_ = Native::ImDrawFlags_RoundCornersDefault_
    RoundCornersMask_ = Native::ImDrawFlags_RoundCornersMask_
  end

  module DrawListFlags
    None = Native::ImDrawListFlags_None
    AntiAliasedLines = Native::ImDrawListFlags_AntiAliasedLines
    AntiAliasedLinesUseTex = Native::ImDrawListFlags_AntiAliasedLinesUseTex
    AntiAliasedFill = Native::ImDrawListFlags_AntiAliasedFill
    AllowVtxOffset = Native::ImDrawListFlags_AllowVtxOffset
  end

  module FontAtlasFlags
    None = Native::ImFontAtlasFlags_None
    NoPowerOfTwoHeight = Native::ImFontAtlasFlags_NoPowerOfTwoHeight
    NoMouseCursors = Native::ImFontAtlasFlags_NoMouseCursors
    NoBakedLines = Native::ImFontAtlasFlags_NoBakedLines
  end

  module ActivateFlags
    None = Native::ImGuiActivateFlags_None
    PreferInput = Native::ImGuiActivateFlags_PreferInput
    PreferTweak = Native::ImGuiActivateFlags_PreferTweak
    TryToPreserveState = Native::ImGuiActivateFlags_TryToPreserveState
    FromTabbing = Native::ImGuiActivateFlags_FromTabbing
    FromShortcut = Native::ImGuiActivateFlags_FromShortcut
  end

  module Axis
    None = Native::ImGuiAxis_None
    X = Native::ImGuiAxis_X
    Y = Native::ImGuiAxis_Y
  end

  module BackendFlags
    None = Native::ImGuiBackendFlags_None
    HasGamepad = Native::ImGuiBackendFlags_HasGamepad
    HasMouseCursors = Native::ImGuiBackendFlags_HasMouseCursors
    HasSetMousePos = Native::ImGuiBackendFlags_HasSetMousePos
    RendererHasVtxOffset = Native::ImGuiBackendFlags_RendererHasVtxOffset
    PlatformHasViewports = Native::ImGuiBackendFlags_PlatformHasViewports
    HasMouseHoveredViewport = Native::ImGuiBackendFlags_HasMouseHoveredViewport
    RendererHasViewports = Native::ImGuiBackendFlags_RendererHasViewports
  end

  module ButtonFlagsPrivate
    ImGuiButtonFlags_PressedOnClick = Native::ImGuiButtonFlags_PressedOnClick
    ImGuiButtonFlags_PressedOnClickRelease = Native::ImGuiButtonFlags_PressedOnClickRelease
    ImGuiButtonFlags_PressedOnClickReleaseAnywhere = Native::ImGuiButtonFlags_PressedOnClickReleaseAnywhere
    ImGuiButtonFlags_PressedOnRelease = Native::ImGuiButtonFlags_PressedOnRelease
    ImGuiButtonFlags_PressedOnDoubleClick = Native::ImGuiButtonFlags_PressedOnDoubleClick
    ImGuiButtonFlags_PressedOnDragDropHold = Native::ImGuiButtonFlags_PressedOnDragDropHold
    ImGuiButtonFlags_FlattenChildren = Native::ImGuiButtonFlags_FlattenChildren
    ImGuiButtonFlags_AllowOverlap = Native::ImGuiButtonFlags_AllowOverlap
    ImGuiButtonFlags_AlignTextBaseLine = Native::ImGuiButtonFlags_AlignTextBaseLine
    ImGuiButtonFlags_NoKeyModsAllowed = Native::ImGuiButtonFlags_NoKeyModsAllowed
    ImGuiButtonFlags_NoHoldingActiveId = Native::ImGuiButtonFlags_NoHoldingActiveId
    ImGuiButtonFlags_NoNavFocus = Native::ImGuiButtonFlags_NoNavFocus
    ImGuiButtonFlags_NoHoveredOnFocus = Native::ImGuiButtonFlags_NoHoveredOnFocus
    ImGuiButtonFlags_NoSetKeyOwner = Native::ImGuiButtonFlags_NoSetKeyOwner
    ImGuiButtonFlags_NoTestKeyOwner = Native::ImGuiButtonFlags_NoTestKeyOwner
    ImGuiButtonFlags_PressedOnMask_ = Native::ImGuiButtonFlags_PressedOnMask_
    ImGuiButtonFlags_PressedOnDefault_ = Native::ImGuiButtonFlags_PressedOnDefault_
  end

  module ButtonFlags
    None = Native::ImGuiButtonFlags_None
    MouseButtonLeft = Native::ImGuiButtonFlags_MouseButtonLeft
    MouseButtonRight = Native::ImGuiButtonFlags_MouseButtonRight
    MouseButtonMiddle = Native::ImGuiButtonFlags_MouseButtonMiddle
    MouseButtonMask_ = Native::ImGuiButtonFlags_MouseButtonMask_
    EnableNav = Native::ImGuiButtonFlags_EnableNav
  end

  module ChildFlags
    None = Native::ImGuiChildFlags_None
    Borders = Native::ImGuiChildFlags_Borders
    AlwaysUseWindowPadding = Native::ImGuiChildFlags_AlwaysUseWindowPadding
    ResizeX = Native::ImGuiChildFlags_ResizeX
    ResizeY = Native::ImGuiChildFlags_ResizeY
    AutoResizeX = Native::ImGuiChildFlags_AutoResizeX
    AutoResizeY = Native::ImGuiChildFlags_AutoResizeY
    AlwaysAutoResize = Native::ImGuiChildFlags_AlwaysAutoResize
    FrameStyle = Native::ImGuiChildFlags_FrameStyle
    NavFlattened = Native::ImGuiChildFlags_NavFlattened
  end

  module Col
    Text = Native::ImGuiCol_Text
    TextDisabled = Native::ImGuiCol_TextDisabled
    WindowBg = Native::ImGuiCol_WindowBg
    ChildBg = Native::ImGuiCol_ChildBg
    PopupBg = Native::ImGuiCol_PopupBg
    Border = Native::ImGuiCol_Border
    BorderShadow = Native::ImGuiCol_BorderShadow
    FrameBg = Native::ImGuiCol_FrameBg
    FrameBgHovered = Native::ImGuiCol_FrameBgHovered
    FrameBgActive = Native::ImGuiCol_FrameBgActive
    TitleBg = Native::ImGuiCol_TitleBg
    TitleBgActive = Native::ImGuiCol_TitleBgActive
    TitleBgCollapsed = Native::ImGuiCol_TitleBgCollapsed
    MenuBarBg = Native::ImGuiCol_MenuBarBg
    ScrollbarBg = Native::ImGuiCol_ScrollbarBg
    ScrollbarGrab = Native::ImGuiCol_ScrollbarGrab
    ScrollbarGrabHovered = Native::ImGuiCol_ScrollbarGrabHovered
    ScrollbarGrabActive = Native::ImGuiCol_ScrollbarGrabActive
    CheckMark = Native::ImGuiCol_CheckMark
    SliderGrab = Native::ImGuiCol_SliderGrab
    SliderGrabActive = Native::ImGuiCol_SliderGrabActive
    Button = Native::ImGuiCol_Button
    ButtonHovered = Native::ImGuiCol_ButtonHovered
    ButtonActive = Native::ImGuiCol_ButtonActive
    Header = Native::ImGuiCol_Header
    HeaderHovered = Native::ImGuiCol_HeaderHovered
    HeaderActive = Native::ImGuiCol_HeaderActive
    Separator = Native::ImGuiCol_Separator
    SeparatorHovered = Native::ImGuiCol_SeparatorHovered
    SeparatorActive = Native::ImGuiCol_SeparatorActive
    ResizeGrip = Native::ImGuiCol_ResizeGrip
    ResizeGripHovered = Native::ImGuiCol_ResizeGripHovered
    ResizeGripActive = Native::ImGuiCol_ResizeGripActive
    TabHovered = Native::ImGuiCol_TabHovered
    Tab = Native::ImGuiCol_Tab
    TabSelected = Native::ImGuiCol_TabSelected
    TabSelectedOverline = Native::ImGuiCol_TabSelectedOverline
    TabDimmed = Native::ImGuiCol_TabDimmed
    TabDimmedSelected = Native::ImGuiCol_TabDimmedSelected
    TabDimmedSelectedOverline = Native::ImGuiCol_TabDimmedSelectedOverline
    DockingPreview = Native::ImGuiCol_DockingPreview
    DockingEmptyBg = Native::ImGuiCol_DockingEmptyBg
    PlotLines = Native::ImGuiCol_PlotLines
    PlotLinesHovered = Native::ImGuiCol_PlotLinesHovered
    PlotHistogram = Native::ImGuiCol_PlotHistogram
    PlotHistogramHovered = Native::ImGuiCol_PlotHistogramHovered
    TableHeaderBg = Native::ImGuiCol_TableHeaderBg
    TableBorderStrong = Native::ImGuiCol_TableBorderStrong
    TableBorderLight = Native::ImGuiCol_TableBorderLight
    TableRowBg = Native::ImGuiCol_TableRowBg
    TableRowBgAlt = Native::ImGuiCol_TableRowBgAlt
    TextLink = Native::ImGuiCol_TextLink
    TextSelectedBg = Native::ImGuiCol_TextSelectedBg
    DragDropTarget = Native::ImGuiCol_DragDropTarget
    NavCursor = Native::ImGuiCol_NavCursor
    NavWindowingHighlight = Native::ImGuiCol_NavWindowingHighlight
    NavWindowingDimBg = Native::ImGuiCol_NavWindowingDimBg
    ModalWindowDimBg = Native::ImGuiCol_ModalWindowDimBg
    COUNT = Native::ImGuiCol_COUNT
  end

  module ColorEditFlags
    None = Native::ImGuiColorEditFlags_None
    NoAlpha = Native::ImGuiColorEditFlags_NoAlpha
    NoPicker = Native::ImGuiColorEditFlags_NoPicker
    NoOptions = Native::ImGuiColorEditFlags_NoOptions
    NoSmallPreview = Native::ImGuiColorEditFlags_NoSmallPreview
    NoInputs = Native::ImGuiColorEditFlags_NoInputs
    NoTooltip = Native::ImGuiColorEditFlags_NoTooltip
    NoLabel = Native::ImGuiColorEditFlags_NoLabel
    NoSidePreview = Native::ImGuiColorEditFlags_NoSidePreview
    NoDragDrop = Native::ImGuiColorEditFlags_NoDragDrop
    NoBorder = Native::ImGuiColorEditFlags_NoBorder
    AlphaOpaque = Native::ImGuiColorEditFlags_AlphaOpaque
    AlphaNoBg = Native::ImGuiColorEditFlags_AlphaNoBg
    AlphaPreviewHalf = Native::ImGuiColorEditFlags_AlphaPreviewHalf
    AlphaBar = Native::ImGuiColorEditFlags_AlphaBar
    HDR = Native::ImGuiColorEditFlags_HDR
    DisplayRGB = Native::ImGuiColorEditFlags_DisplayRGB
    DisplayHSV = Native::ImGuiColorEditFlags_DisplayHSV
    DisplayHex = Native::ImGuiColorEditFlags_DisplayHex
    Uint8 = Native::ImGuiColorEditFlags_Uint8
    Float = Native::ImGuiColorEditFlags_Float
    PickerHueBar = Native::ImGuiColorEditFlags_PickerHueBar
    PickerHueWheel = Native::ImGuiColorEditFlags_PickerHueWheel
    InputRGB = Native::ImGuiColorEditFlags_InputRGB
    InputHSV = Native::ImGuiColorEditFlags_InputHSV
    DefaultOptions_ = Native::ImGuiColorEditFlags_DefaultOptions_
    AlphaMask_ = Native::ImGuiColorEditFlags_AlphaMask_
    DisplayMask_ = Native::ImGuiColorEditFlags_DisplayMask_
    DataTypeMask_ = Native::ImGuiColorEditFlags_DataTypeMask_
    PickerMask_ = Native::ImGuiColorEditFlags_PickerMask_
    InputMask_ = Native::ImGuiColorEditFlags_InputMask_
  end

  module ComboFlagsPrivate
    ImGuiComboFlags_CustomPreview = Native::ImGuiComboFlags_CustomPreview
  end

  module ComboFlags
    None = Native::ImGuiComboFlags_None
    PopupAlignLeft = Native::ImGuiComboFlags_PopupAlignLeft
    HeightSmall = Native::ImGuiComboFlags_HeightSmall
    HeightRegular = Native::ImGuiComboFlags_HeightRegular
    HeightLarge = Native::ImGuiComboFlags_HeightLarge
    HeightLargest = Native::ImGuiComboFlags_HeightLargest
    NoArrowButton = Native::ImGuiComboFlags_NoArrowButton
    NoPreview = Native::ImGuiComboFlags_NoPreview
    WidthFitPreview = Native::ImGuiComboFlags_WidthFitPreview
    HeightMask_ = Native::ImGuiComboFlags_HeightMask_
  end

  module Cond
    None = Native::ImGuiCond_None
    Always = Native::ImGuiCond_Always
    Once = Native::ImGuiCond_Once
    FirstUseEver = Native::ImGuiCond_FirstUseEver
    Appearing = Native::ImGuiCond_Appearing
  end

  module ConfigFlags
    None = Native::ImGuiConfigFlags_None
    NavEnableKeyboard = Native::ImGuiConfigFlags_NavEnableKeyboard
    NavEnableGamepad = Native::ImGuiConfigFlags_NavEnableGamepad
    NoMouse = Native::ImGuiConfigFlags_NoMouse
    NoMouseCursorChange = Native::ImGuiConfigFlags_NoMouseCursorChange
    NoKeyboard = Native::ImGuiConfigFlags_NoKeyboard
    DockingEnable = Native::ImGuiConfigFlags_DockingEnable
    ViewportsEnable = Native::ImGuiConfigFlags_ViewportsEnable
    DpiEnableScaleViewports = Native::ImGuiConfigFlags_DpiEnableScaleViewports
    DpiEnableScaleFonts = Native::ImGuiConfigFlags_DpiEnableScaleFonts
    IsSRGB = Native::ImGuiConfigFlags_IsSRGB
    IsTouchScreen = Native::ImGuiConfigFlags_IsTouchScreen
  end

  module ContextHookType
    NewFramePre = Native::ImGuiContextHookType_NewFramePre
    NewFramePost = Native::ImGuiContextHookType_NewFramePost
    EndFramePre = Native::ImGuiContextHookType_EndFramePre
    EndFramePost = Native::ImGuiContextHookType_EndFramePost
    RenderPre = Native::ImGuiContextHookType_RenderPre
    RenderPost = Native::ImGuiContextHookType_RenderPost
    Shutdown = Native::ImGuiContextHookType_Shutdown
    PendingRemoval_ = Native::ImGuiContextHookType_PendingRemoval_
  end

  module DataAuthority
    Auto = Native::ImGuiDataAuthority_Auto
    DockNode = Native::ImGuiDataAuthority_DockNode
    Window = Native::ImGuiDataAuthority_Window
  end

  module DataTypePrivate
    ImGuiDataType_Pointer = Native::ImGuiDataType_Pointer
    ImGuiDataType_ID = Native::ImGuiDataType_ID
  end

  module DataType
    S8 = Native::ImGuiDataType_S8
    U8 = Native::ImGuiDataType_U8
    S16 = Native::ImGuiDataType_S16
    U16 = Native::ImGuiDataType_U16
    S32 = Native::ImGuiDataType_S32
    U32 = Native::ImGuiDataType_U32
    S64 = Native::ImGuiDataType_S64
    U64 = Native::ImGuiDataType_U64
    Float = Native::ImGuiDataType_Float
    Double = Native::ImGuiDataType_Double
    Bool = Native::ImGuiDataType_Bool
    String = Native::ImGuiDataType_String
    COUNT = Native::ImGuiDataType_COUNT
  end

  module DebugLogFlags
    None = Native::ImGuiDebugLogFlags_None
    EventError = Native::ImGuiDebugLogFlags_EventError
    EventActiveId = Native::ImGuiDebugLogFlags_EventActiveId
    EventFocus = Native::ImGuiDebugLogFlags_EventFocus
    EventPopup = Native::ImGuiDebugLogFlags_EventPopup
    EventNav = Native::ImGuiDebugLogFlags_EventNav
    EventClipper = Native::ImGuiDebugLogFlags_EventClipper
    EventSelection = Native::ImGuiDebugLogFlags_EventSelection
    EventIO = Native::ImGuiDebugLogFlags_EventIO
    EventFont = Native::ImGuiDebugLogFlags_EventFont
    EventInputRouting = Native::ImGuiDebugLogFlags_EventInputRouting
    EventDocking = Native::ImGuiDebugLogFlags_EventDocking
    EventViewport = Native::ImGuiDebugLogFlags_EventViewport
    EventMask_ = Native::ImGuiDebugLogFlags_EventMask_
    OutputToTTY = Native::ImGuiDebugLogFlags_OutputToTTY
    OutputToTestEngine = Native::ImGuiDebugLogFlags_OutputToTestEngine
  end

  module Dir
    None = Native::ImGuiDir_None
    Left = Native::ImGuiDir_Left
    Right = Native::ImGuiDir_Right
    Up = Native::ImGuiDir_Up
    Down = Native::ImGuiDir_Down
    COUNT = Native::ImGuiDir_COUNT
  end

  module DockNodeFlagsPrivate
    ImGuiDockNodeFlags_DockSpace = Native::ImGuiDockNodeFlags_DockSpace
    ImGuiDockNodeFlags_CentralNode = Native::ImGuiDockNodeFlags_CentralNode
    ImGuiDockNodeFlags_NoTabBar = Native::ImGuiDockNodeFlags_NoTabBar
    ImGuiDockNodeFlags_HiddenTabBar = Native::ImGuiDockNodeFlags_HiddenTabBar
    ImGuiDockNodeFlags_NoWindowMenuButton = Native::ImGuiDockNodeFlags_NoWindowMenuButton
    ImGuiDockNodeFlags_NoCloseButton = Native::ImGuiDockNodeFlags_NoCloseButton
    ImGuiDockNodeFlags_NoResizeX = Native::ImGuiDockNodeFlags_NoResizeX
    ImGuiDockNodeFlags_NoResizeY = Native::ImGuiDockNodeFlags_NoResizeY
    ImGuiDockNodeFlags_DockedWindowsInFocusRoute = Native::ImGuiDockNodeFlags_DockedWindowsInFocusRoute
    ImGuiDockNodeFlags_NoDockingSplitOther = Native::ImGuiDockNodeFlags_NoDockingSplitOther
    ImGuiDockNodeFlags_NoDockingOverMe = Native::ImGuiDockNodeFlags_NoDockingOverMe
    ImGuiDockNodeFlags_NoDockingOverOther = Native::ImGuiDockNodeFlags_NoDockingOverOther
    ImGuiDockNodeFlags_NoDockingOverEmpty = Native::ImGuiDockNodeFlags_NoDockingOverEmpty
    ImGuiDockNodeFlags_NoDocking = Native::ImGuiDockNodeFlags_NoDocking
    ImGuiDockNodeFlags_SharedFlagsInheritMask_ = Native::ImGuiDockNodeFlags_SharedFlagsInheritMask_
    ImGuiDockNodeFlags_NoResizeFlagsMask_ = Native::ImGuiDockNodeFlags_NoResizeFlagsMask_
    ImGuiDockNodeFlags_LocalFlagsTransferMask_ = Native::ImGuiDockNodeFlags_LocalFlagsTransferMask_
    ImGuiDockNodeFlags_SavedFlagsMask_ = Native::ImGuiDockNodeFlags_SavedFlagsMask_
  end

  module DockNodeFlags
    None = Native::ImGuiDockNodeFlags_None
    KeepAliveOnly = Native::ImGuiDockNodeFlags_KeepAliveOnly
    NoDockingOverCentralNode = Native::ImGuiDockNodeFlags_NoDockingOverCentralNode
    PassthruCentralNode = Native::ImGuiDockNodeFlags_PassthruCentralNode
    NoDockingSplit = Native::ImGuiDockNodeFlags_NoDockingSplit
    NoResize = Native::ImGuiDockNodeFlags_NoResize
    AutoHideTabBar = Native::ImGuiDockNodeFlags_AutoHideTabBar
    NoUndocking = Native::ImGuiDockNodeFlags_NoUndocking
  end

  module DockNodeState
    Unknown = Native::ImGuiDockNodeState_Unknown
    HostWindowHiddenBecauseSingleWindow = Native::ImGuiDockNodeState_HostWindowHiddenBecauseSingleWindow
    HostWindowHiddenBecauseWindowsAreResizing = Native::ImGuiDockNodeState_HostWindowHiddenBecauseWindowsAreResizing
    HostWindowVisible = Native::ImGuiDockNodeState_HostWindowVisible
  end

  module DragDropFlags
    None = Native::ImGuiDragDropFlags_None
    SourceNoPreviewTooltip = Native::ImGuiDragDropFlags_SourceNoPreviewTooltip
    SourceNoDisableHover = Native::ImGuiDragDropFlags_SourceNoDisableHover
    SourceNoHoldToOpenOthers = Native::ImGuiDragDropFlags_SourceNoHoldToOpenOthers
    SourceAllowNullID = Native::ImGuiDragDropFlags_SourceAllowNullID
    SourceExtern = Native::ImGuiDragDropFlags_SourceExtern
    PayloadAutoExpire = Native::ImGuiDragDropFlags_PayloadAutoExpire
    PayloadNoCrossContext = Native::ImGuiDragDropFlags_PayloadNoCrossContext
    PayloadNoCrossProcess = Native::ImGuiDragDropFlags_PayloadNoCrossProcess
    AcceptBeforeDelivery = Native::ImGuiDragDropFlags_AcceptBeforeDelivery
    AcceptNoDrawDefaultRect = Native::ImGuiDragDropFlags_AcceptNoDrawDefaultRect
    AcceptNoPreviewTooltip = Native::ImGuiDragDropFlags_AcceptNoPreviewTooltip
    AcceptPeekOnly = Native::ImGuiDragDropFlags_AcceptPeekOnly
  end

  module FocusRequestFlags
    None = Native::ImGuiFocusRequestFlags_None
    RestoreFocusedChild = Native::ImGuiFocusRequestFlags_RestoreFocusedChild
    UnlessBelowModal = Native::ImGuiFocusRequestFlags_UnlessBelowModal
  end

  module FocusedFlags
    None = Native::ImGuiFocusedFlags_None
    ChildWindows = Native::ImGuiFocusedFlags_ChildWindows
    RootWindow = Native::ImGuiFocusedFlags_RootWindow
    AnyWindow = Native::ImGuiFocusedFlags_AnyWindow
    NoPopupHierarchy = Native::ImGuiFocusedFlags_NoPopupHierarchy
    DockHierarchy = Native::ImGuiFocusedFlags_DockHierarchy
    RootAndChildWindows = Native::ImGuiFocusedFlags_RootAndChildWindows
  end

  module FreeTypeBuilderFlags
    NoHinting = Native::ImGuiFreeTypeBuilderFlags_NoHinting
    NoAutoHint = Native::ImGuiFreeTypeBuilderFlags_NoAutoHint
    ForceAutoHint = Native::ImGuiFreeTypeBuilderFlags_ForceAutoHint
    LightHinting = Native::ImGuiFreeTypeBuilderFlags_LightHinting
    MonoHinting = Native::ImGuiFreeTypeBuilderFlags_MonoHinting
    Bold = Native::ImGuiFreeTypeBuilderFlags_Bold
    Oblique = Native::ImGuiFreeTypeBuilderFlags_Oblique
    Monochrome = Native::ImGuiFreeTypeBuilderFlags_Monochrome
    LoadColor = Native::ImGuiFreeTypeBuilderFlags_LoadColor
    Bitmap = Native::ImGuiFreeTypeBuilderFlags_Bitmap
  end

  module HoveredFlagsPrivate
    ImGuiHoveredFlags_DelayMask_ = Native::ImGuiHoveredFlags_DelayMask_
    ImGuiHoveredFlags_AllowedMaskForIsWindowHovered = Native::ImGuiHoveredFlags_AllowedMaskForIsWindowHovered
    ImGuiHoveredFlags_AllowedMaskForIsItemHovered = Native::ImGuiHoveredFlags_AllowedMaskForIsItemHovered
  end

  module HoveredFlags
    None = Native::ImGuiHoveredFlags_None
    ChildWindows = Native::ImGuiHoveredFlags_ChildWindows
    RootWindow = Native::ImGuiHoveredFlags_RootWindow
    AnyWindow = Native::ImGuiHoveredFlags_AnyWindow
    NoPopupHierarchy = Native::ImGuiHoveredFlags_NoPopupHierarchy
    DockHierarchy = Native::ImGuiHoveredFlags_DockHierarchy
    AllowWhenBlockedByPopup = Native::ImGuiHoveredFlags_AllowWhenBlockedByPopup
    AllowWhenBlockedByActiveItem = Native::ImGuiHoveredFlags_AllowWhenBlockedByActiveItem
    AllowWhenOverlappedByItem = Native::ImGuiHoveredFlags_AllowWhenOverlappedByItem
    AllowWhenOverlappedByWindow = Native::ImGuiHoveredFlags_AllowWhenOverlappedByWindow
    AllowWhenDisabled = Native::ImGuiHoveredFlags_AllowWhenDisabled
    NoNavOverride = Native::ImGuiHoveredFlags_NoNavOverride
    AllowWhenOverlapped = Native::ImGuiHoveredFlags_AllowWhenOverlapped
    RectOnly = Native::ImGuiHoveredFlags_RectOnly
    RootAndChildWindows = Native::ImGuiHoveredFlags_RootAndChildWindows
    ForTooltip = Native::ImGuiHoveredFlags_ForTooltip
    Stationary = Native::ImGuiHoveredFlags_Stationary
    DelayNone = Native::ImGuiHoveredFlags_DelayNone
    DelayShort = Native::ImGuiHoveredFlags_DelayShort
    DelayNormal = Native::ImGuiHoveredFlags_DelayNormal
    NoSharedDelay = Native::ImGuiHoveredFlags_NoSharedDelay
  end

  module InputEventType
    None = Native::ImGuiInputEventType_None
    MousePos = Native::ImGuiInputEventType_MousePos
    MouseWheel = Native::ImGuiInputEventType_MouseWheel
    MouseButton = Native::ImGuiInputEventType_MouseButton
    MouseViewport = Native::ImGuiInputEventType_MouseViewport
    Key = Native::ImGuiInputEventType_Key
    Text = Native::ImGuiInputEventType_Text
    Focus = Native::ImGuiInputEventType_Focus
    COUNT = Native::ImGuiInputEventType_COUNT
  end

  module InputFlagsPrivate
    ImGuiInputFlags_RepeatRateDefault = Native::ImGuiInputFlags_RepeatRateDefault
    ImGuiInputFlags_RepeatRateNavMove = Native::ImGuiInputFlags_RepeatRateNavMove
    ImGuiInputFlags_RepeatRateNavTweak = Native::ImGuiInputFlags_RepeatRateNavTweak
    ImGuiInputFlags_RepeatUntilRelease = Native::ImGuiInputFlags_RepeatUntilRelease
    ImGuiInputFlags_RepeatUntilKeyModsChange = Native::ImGuiInputFlags_RepeatUntilKeyModsChange
    ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone = Native::ImGuiInputFlags_RepeatUntilKeyModsChangeFromNone
    ImGuiInputFlags_RepeatUntilOtherKeyPress = Native::ImGuiInputFlags_RepeatUntilOtherKeyPress
    ImGuiInputFlags_LockThisFrame = Native::ImGuiInputFlags_LockThisFrame
    ImGuiInputFlags_LockUntilRelease = Native::ImGuiInputFlags_LockUntilRelease
    ImGuiInputFlags_CondHovered = Native::ImGuiInputFlags_CondHovered
    ImGuiInputFlags_CondActive = Native::ImGuiInputFlags_CondActive
    ImGuiInputFlags_CondDefault_ = Native::ImGuiInputFlags_CondDefault_
    ImGuiInputFlags_RepeatRateMask_ = Native::ImGuiInputFlags_RepeatRateMask_
    ImGuiInputFlags_RepeatUntilMask_ = Native::ImGuiInputFlags_RepeatUntilMask_
    ImGuiInputFlags_RepeatMask_ = Native::ImGuiInputFlags_RepeatMask_
    ImGuiInputFlags_CondMask_ = Native::ImGuiInputFlags_CondMask_
    ImGuiInputFlags_RouteTypeMask_ = Native::ImGuiInputFlags_RouteTypeMask_
    ImGuiInputFlags_RouteOptionsMask_ = Native::ImGuiInputFlags_RouteOptionsMask_
    ImGuiInputFlags_SupportedByIsKeyPressed = Native::ImGuiInputFlags_SupportedByIsKeyPressed
    ImGuiInputFlags_SupportedByIsMouseClicked = Native::ImGuiInputFlags_SupportedByIsMouseClicked
    ImGuiInputFlags_SupportedByShortcut = Native::ImGuiInputFlags_SupportedByShortcut
    ImGuiInputFlags_SupportedBySetNextItemShortcut = Native::ImGuiInputFlags_SupportedBySetNextItemShortcut
    ImGuiInputFlags_SupportedBySetKeyOwner = Native::ImGuiInputFlags_SupportedBySetKeyOwner
    ImGuiInputFlags_SupportedBySetItemKeyOwner = Native::ImGuiInputFlags_SupportedBySetItemKeyOwner
  end

  module InputFlags
    None = Native::ImGuiInputFlags_None
    Repeat = Native::ImGuiInputFlags_Repeat
    RouteActive = Native::ImGuiInputFlags_RouteActive
    RouteFocused = Native::ImGuiInputFlags_RouteFocused
    RouteGlobal = Native::ImGuiInputFlags_RouteGlobal
    RouteAlways = Native::ImGuiInputFlags_RouteAlways
    RouteOverFocused = Native::ImGuiInputFlags_RouteOverFocused
    RouteOverActive = Native::ImGuiInputFlags_RouteOverActive
    RouteUnlessBgFocused = Native::ImGuiInputFlags_RouteUnlessBgFocused
    RouteFromRootWindow = Native::ImGuiInputFlags_RouteFromRootWindow
    Tooltip = Native::ImGuiInputFlags_Tooltip
  end

  module InputSource
    None = Native::ImGuiInputSource_None
    Mouse = Native::ImGuiInputSource_Mouse
    Keyboard = Native::ImGuiInputSource_Keyboard
    Gamepad = Native::ImGuiInputSource_Gamepad
    COUNT = Native::ImGuiInputSource_COUNT
  end

  module InputTextFlagsPrivate
    ImGuiInputTextFlags_Multiline = Native::ImGuiInputTextFlags_Multiline
    ImGuiInputTextFlags_MergedItem = Native::ImGuiInputTextFlags_MergedItem
    ImGuiInputTextFlags_LocalizeDecimalPoint = Native::ImGuiInputTextFlags_LocalizeDecimalPoint
  end

  module InputTextFlags
    None = Native::ImGuiInputTextFlags_None
    CharsDecimal = Native::ImGuiInputTextFlags_CharsDecimal
    CharsHexadecimal = Native::ImGuiInputTextFlags_CharsHexadecimal
    CharsScientific = Native::ImGuiInputTextFlags_CharsScientific
    CharsUppercase = Native::ImGuiInputTextFlags_CharsUppercase
    CharsNoBlank = Native::ImGuiInputTextFlags_CharsNoBlank
    AllowTabInput = Native::ImGuiInputTextFlags_AllowTabInput
    EnterReturnsTrue = Native::ImGuiInputTextFlags_EnterReturnsTrue
    EscapeClearsAll = Native::ImGuiInputTextFlags_EscapeClearsAll
    CtrlEnterForNewLine = Native::ImGuiInputTextFlags_CtrlEnterForNewLine
    ReadOnly = Native::ImGuiInputTextFlags_ReadOnly
    Password = Native::ImGuiInputTextFlags_Password
    AlwaysOverwrite = Native::ImGuiInputTextFlags_AlwaysOverwrite
    AutoSelectAll = Native::ImGuiInputTextFlags_AutoSelectAll
    ParseEmptyRefVal = Native::ImGuiInputTextFlags_ParseEmptyRefVal
    DisplayEmptyRefVal = Native::ImGuiInputTextFlags_DisplayEmptyRefVal
    NoHorizontalScroll = Native::ImGuiInputTextFlags_NoHorizontalScroll
    NoUndoRedo = Native::ImGuiInputTextFlags_NoUndoRedo
    ElideLeft = Native::ImGuiInputTextFlags_ElideLeft
    CallbackCompletion = Native::ImGuiInputTextFlags_CallbackCompletion
    CallbackHistory = Native::ImGuiInputTextFlags_CallbackHistory
    CallbackAlways = Native::ImGuiInputTextFlags_CallbackAlways
    CallbackCharFilter = Native::ImGuiInputTextFlags_CallbackCharFilter
    CallbackResize = Native::ImGuiInputTextFlags_CallbackResize
    CallbackEdit = Native::ImGuiInputTextFlags_CallbackEdit
  end

  module ItemFlagsPrivate
    ImGuiItemFlags_Disabled = Native::ImGuiItemFlags_Disabled
    ImGuiItemFlags_ReadOnly = Native::ImGuiItemFlags_ReadOnly
    ImGuiItemFlags_MixedValue = Native::ImGuiItemFlags_MixedValue
    ImGuiItemFlags_NoWindowHoverableCheck = Native::ImGuiItemFlags_NoWindowHoverableCheck
    ImGuiItemFlags_AllowOverlap = Native::ImGuiItemFlags_AllowOverlap
    ImGuiItemFlags_NoNavDisableMouseHover = Native::ImGuiItemFlags_NoNavDisableMouseHover
    ImGuiItemFlags_NoMarkEdited = Native::ImGuiItemFlags_NoMarkEdited
    ImGuiItemFlags_Inputable = Native::ImGuiItemFlags_Inputable
    ImGuiItemFlags_HasSelectionUserData = Native::ImGuiItemFlags_HasSelectionUserData
    ImGuiItemFlags_IsMultiSelect = Native::ImGuiItemFlags_IsMultiSelect
    ImGuiItemFlags_Default_ = Native::ImGuiItemFlags_Default_
  end

  module ItemFlags
    None = Native::ImGuiItemFlags_None
    NoTabStop = Native::ImGuiItemFlags_NoTabStop
    NoNav = Native::ImGuiItemFlags_NoNav
    NoNavDefaultFocus = Native::ImGuiItemFlags_NoNavDefaultFocus
    ButtonRepeat = Native::ImGuiItemFlags_ButtonRepeat
    AutoClosePopups = Native::ImGuiItemFlags_AutoClosePopups
    AllowDuplicateId = Native::ImGuiItemFlags_AllowDuplicateId
  end

  module ItemStatusFlags
    None = Native::ImGuiItemStatusFlags_None
    HoveredRect = Native::ImGuiItemStatusFlags_HoveredRect
    HasDisplayRect = Native::ImGuiItemStatusFlags_HasDisplayRect
    Edited = Native::ImGuiItemStatusFlags_Edited
    ToggledSelection = Native::ImGuiItemStatusFlags_ToggledSelection
    ToggledOpen = Native::ImGuiItemStatusFlags_ToggledOpen
    HasDeactivated = Native::ImGuiItemStatusFlags_HasDeactivated
    Deactivated = Native::ImGuiItemStatusFlags_Deactivated
    HoveredWindow = Native::ImGuiItemStatusFlags_HoveredWindow
    Visible = Native::ImGuiItemStatusFlags_Visible
    HasClipRect = Native::ImGuiItemStatusFlags_HasClipRect
    HasShortcut = Native::ImGuiItemStatusFlags_HasShortcut
  end

  module Key
    None = Native::ImGuiKey_None
    NamedKey_BEGIN = Native::ImGuiKey_NamedKey_BEGIN
    Tab = Native::ImGuiKey_Tab
    LeftArrow = Native::ImGuiKey_LeftArrow
    RightArrow = Native::ImGuiKey_RightArrow
    UpArrow = Native::ImGuiKey_UpArrow
    DownArrow = Native::ImGuiKey_DownArrow
    PageUp = Native::ImGuiKey_PageUp
    PageDown = Native::ImGuiKey_PageDown
    Home = Native::ImGuiKey_Home
    End = Native::ImGuiKey_End
    Insert = Native::ImGuiKey_Insert
    Delete = Native::ImGuiKey_Delete
    Backspace = Native::ImGuiKey_Backspace
    Space = Native::ImGuiKey_Space
    Enter = Native::ImGuiKey_Enter
    Escape = Native::ImGuiKey_Escape
    LeftCtrl = Native::ImGuiKey_LeftCtrl
    LeftShift = Native::ImGuiKey_LeftShift
    LeftAlt = Native::ImGuiKey_LeftAlt
    LeftSuper = Native::ImGuiKey_LeftSuper
    RightCtrl = Native::ImGuiKey_RightCtrl
    RightShift = Native::ImGuiKey_RightShift
    RightAlt = Native::ImGuiKey_RightAlt
    RightSuper = Native::ImGuiKey_RightSuper
    Menu = Native::ImGuiKey_Menu
    Num0 = Native::ImGuiKey_0
    Num1 = Native::ImGuiKey_1
    Num2 = Native::ImGuiKey_2
    Num3 = Native::ImGuiKey_3
    Num4 = Native::ImGuiKey_4
    Num5 = Native::ImGuiKey_5
    Num6 = Native::ImGuiKey_6
    Num7 = Native::ImGuiKey_7
    Num8 = Native::ImGuiKey_8
    Num9 = Native::ImGuiKey_9
    A = Native::ImGuiKey_A
    B = Native::ImGuiKey_B
    C = Native::ImGuiKey_C
    D = Native::ImGuiKey_D
    E = Native::ImGuiKey_E
    F = Native::ImGuiKey_F
    G = Native::ImGuiKey_G
    H = Native::ImGuiKey_H
    I = Native::ImGuiKey_I
    J = Native::ImGuiKey_J
    K = Native::ImGuiKey_K
    L = Native::ImGuiKey_L
    M = Native::ImGuiKey_M
    N = Native::ImGuiKey_N
    O = Native::ImGuiKey_O
    P = Native::ImGuiKey_P
    Q = Native::ImGuiKey_Q
    R = Native::ImGuiKey_R
    S = Native::ImGuiKey_S
    T = Native::ImGuiKey_T
    U = Native::ImGuiKey_U
    V = Native::ImGuiKey_V
    W = Native::ImGuiKey_W
    X = Native::ImGuiKey_X
    Y = Native::ImGuiKey_Y
    Z = Native::ImGuiKey_Z
    F1 = Native::ImGuiKey_F1
    F2 = Native::ImGuiKey_F2
    F3 = Native::ImGuiKey_F3
    F4 = Native::ImGuiKey_F4
    F5 = Native::ImGuiKey_F5
    F6 = Native::ImGuiKey_F6
    F7 = Native::ImGuiKey_F7
    F8 = Native::ImGuiKey_F8
    F9 = Native::ImGuiKey_F9
    F10 = Native::ImGuiKey_F10
    F11 = Native::ImGuiKey_F11
    F12 = Native::ImGuiKey_F12
    F13 = Native::ImGuiKey_F13
    F14 = Native::ImGuiKey_F14
    F15 = Native::ImGuiKey_F15
    F16 = Native::ImGuiKey_F16
    F17 = Native::ImGuiKey_F17
    F18 = Native::ImGuiKey_F18
    F19 = Native::ImGuiKey_F19
    F20 = Native::ImGuiKey_F20
    F21 = Native::ImGuiKey_F21
    F22 = Native::ImGuiKey_F22
    F23 = Native::ImGuiKey_F23
    F24 = Native::ImGuiKey_F24
    Apostrophe = Native::ImGuiKey_Apostrophe
    Comma = Native::ImGuiKey_Comma
    Minus = Native::ImGuiKey_Minus
    Period = Native::ImGuiKey_Period
    Slash = Native::ImGuiKey_Slash
    Semicolon = Native::ImGuiKey_Semicolon
    Equal = Native::ImGuiKey_Equal
    LeftBracket = Native::ImGuiKey_LeftBracket
    Backslash = Native::ImGuiKey_Backslash
    RightBracket = Native::ImGuiKey_RightBracket
    GraveAccent = Native::ImGuiKey_GraveAccent
    CapsLock = Native::ImGuiKey_CapsLock
    ScrollLock = Native::ImGuiKey_ScrollLock
    NumLock = Native::ImGuiKey_NumLock
    PrintScreen = Native::ImGuiKey_PrintScreen
    Pause = Native::ImGuiKey_Pause
    Keypad0 = Native::ImGuiKey_Keypad0
    Keypad1 = Native::ImGuiKey_Keypad1
    Keypad2 = Native::ImGuiKey_Keypad2
    Keypad3 = Native::ImGuiKey_Keypad3
    Keypad4 = Native::ImGuiKey_Keypad4
    Keypad5 = Native::ImGuiKey_Keypad5
    Keypad6 = Native::ImGuiKey_Keypad6
    Keypad7 = Native::ImGuiKey_Keypad7
    Keypad8 = Native::ImGuiKey_Keypad8
    Keypad9 = Native::ImGuiKey_Keypad9
    KeypadDecimal = Native::ImGuiKey_KeypadDecimal
    KeypadDivide = Native::ImGuiKey_KeypadDivide
    KeypadMultiply = Native::ImGuiKey_KeypadMultiply
    KeypadSubtract = Native::ImGuiKey_KeypadSubtract
    KeypadAdd = Native::ImGuiKey_KeypadAdd
    KeypadEnter = Native::ImGuiKey_KeypadEnter
    KeypadEqual = Native::ImGuiKey_KeypadEqual
    AppBack = Native::ImGuiKey_AppBack
    AppForward = Native::ImGuiKey_AppForward
    Oem102 = Native::ImGuiKey_Oem102
    GamepadStart = Native::ImGuiKey_GamepadStart
    GamepadBack = Native::ImGuiKey_GamepadBack
    GamepadFaceLeft = Native::ImGuiKey_GamepadFaceLeft
    GamepadFaceRight = Native::ImGuiKey_GamepadFaceRight
    GamepadFaceUp = Native::ImGuiKey_GamepadFaceUp
    GamepadFaceDown = Native::ImGuiKey_GamepadFaceDown
    GamepadDpadLeft = Native::ImGuiKey_GamepadDpadLeft
    GamepadDpadRight = Native::ImGuiKey_GamepadDpadRight
    GamepadDpadUp = Native::ImGuiKey_GamepadDpadUp
    GamepadDpadDown = Native::ImGuiKey_GamepadDpadDown
    GamepadL1 = Native::ImGuiKey_GamepadL1
    GamepadR1 = Native::ImGuiKey_GamepadR1
    GamepadL2 = Native::ImGuiKey_GamepadL2
    GamepadR2 = Native::ImGuiKey_GamepadR2
    GamepadL3 = Native::ImGuiKey_GamepadL3
    GamepadR3 = Native::ImGuiKey_GamepadR3
    GamepadLStickLeft = Native::ImGuiKey_GamepadLStickLeft
    GamepadLStickRight = Native::ImGuiKey_GamepadLStickRight
    GamepadLStickUp = Native::ImGuiKey_GamepadLStickUp
    GamepadLStickDown = Native::ImGuiKey_GamepadLStickDown
    GamepadRStickLeft = Native::ImGuiKey_GamepadRStickLeft
    GamepadRStickRight = Native::ImGuiKey_GamepadRStickRight
    GamepadRStickUp = Native::ImGuiKey_GamepadRStickUp
    GamepadRStickDown = Native::ImGuiKey_GamepadRStickDown
    MouseLeft = Native::ImGuiKey_MouseLeft
    MouseRight = Native::ImGuiKey_MouseRight
    MouseMiddle = Native::ImGuiKey_MouseMiddle
    MouseX1 = Native::ImGuiKey_MouseX1
    MouseX2 = Native::ImGuiKey_MouseX2
    MouseWheelX = Native::ImGuiKey_MouseWheelX
    MouseWheelY = Native::ImGuiKey_MouseWheelY
    ReservedForModCtrl = Native::ImGuiKey_ReservedForModCtrl
    ReservedForModShift = Native::ImGuiKey_ReservedForModShift
    ReservedForModAlt = Native::ImGuiKey_ReservedForModAlt
    ReservedForModSuper = Native::ImGuiKey_ReservedForModSuper
    NamedKey_END = Native::ImGuiKey_NamedKey_END
    ImGuiMod_None = Native::ImGuiMod_None
    ImGuiMod_Ctrl = Native::ImGuiMod_Ctrl
    ImGuiMod_Shift = Native::ImGuiMod_Shift
    ImGuiMod_Alt = Native::ImGuiMod_Alt
    ImGuiMod_Super = Native::ImGuiMod_Super
    ImGuiMod_Mask_ = Native::ImGuiMod_Mask_
    NamedKey_COUNT = Native::ImGuiKey_NamedKey_COUNT
  end

  module LayoutType
    Horizontal = Native::ImGuiLayoutType_Horizontal
    Vertical = Native::ImGuiLayoutType_Vertical
  end

  module LocKey
    VersionStr = Native::ImGuiLocKey_VersionStr
    TableSizeOne = Native::ImGuiLocKey_TableSizeOne
    TableSizeAllFit = Native::ImGuiLocKey_TableSizeAllFit
    TableSizeAllDefault = Native::ImGuiLocKey_TableSizeAllDefault
    TableResetOrder = Native::ImGuiLocKey_TableResetOrder
    WindowingMainMenuBar = Native::ImGuiLocKey_WindowingMainMenuBar
    WindowingPopup = Native::ImGuiLocKey_WindowingPopup
    WindowingUntitled = Native::ImGuiLocKey_WindowingUntitled
    OpenLink_s = Native::ImGuiLocKey_OpenLink_s
    CopyLink = Native::ImGuiLocKey_CopyLink
    DockingHideTabBar = Native::ImGuiLocKey_DockingHideTabBar
    DockingHoldShiftToDock = Native::ImGuiLocKey_DockingHoldShiftToDock
    DockingDragToUndockOrMoveNode = Native::ImGuiLocKey_DockingDragToUndockOrMoveNode
    COUNT = Native::ImGuiLocKey_COUNT
  end

  module LogFlags
    None = Native::ImGuiLogFlags_None
    OutputTTY = Native::ImGuiLogFlags_OutputTTY
    OutputFile = Native::ImGuiLogFlags_OutputFile
    OutputBuffer = Native::ImGuiLogFlags_OutputBuffer
    OutputClipboard = Native::ImGuiLogFlags_OutputClipboard
    OutputMask_ = Native::ImGuiLogFlags_OutputMask_
  end

  module MouseButton
    Left = Native::ImGuiMouseButton_Left
    Right = Native::ImGuiMouseButton_Right
    Middle = Native::ImGuiMouseButton_Middle
    COUNT = Native::ImGuiMouseButton_COUNT
  end

  module MouseCursor
    None = Native::ImGuiMouseCursor_None
    Arrow = Native::ImGuiMouseCursor_Arrow
    TextInput = Native::ImGuiMouseCursor_TextInput
    ResizeAll = Native::ImGuiMouseCursor_ResizeAll
    ResizeNS = Native::ImGuiMouseCursor_ResizeNS
    ResizeEW = Native::ImGuiMouseCursor_ResizeEW
    ResizeNESW = Native::ImGuiMouseCursor_ResizeNESW
    ResizeNWSE = Native::ImGuiMouseCursor_ResizeNWSE
    Hand = Native::ImGuiMouseCursor_Hand
    Wait = Native::ImGuiMouseCursor_Wait
    Progress = Native::ImGuiMouseCursor_Progress
    NotAllowed = Native::ImGuiMouseCursor_NotAllowed
    COUNT = Native::ImGuiMouseCursor_COUNT
  end

  module MouseSource
    Mouse = Native::ImGuiMouseSource_Mouse
    TouchScreen = Native::ImGuiMouseSource_TouchScreen
    Pen = Native::ImGuiMouseSource_Pen
    COUNT = Native::ImGuiMouseSource_COUNT
  end

  module MultiSelectFlags
    None = Native::ImGuiMultiSelectFlags_None
    SingleSelect = Native::ImGuiMultiSelectFlags_SingleSelect
    NoSelectAll = Native::ImGuiMultiSelectFlags_NoSelectAll
    NoRangeSelect = Native::ImGuiMultiSelectFlags_NoRangeSelect
    NoAutoSelect = Native::ImGuiMultiSelectFlags_NoAutoSelect
    NoAutoClear = Native::ImGuiMultiSelectFlags_NoAutoClear
    NoAutoClearOnReselect = Native::ImGuiMultiSelectFlags_NoAutoClearOnReselect
    BoxSelect1d = Native::ImGuiMultiSelectFlags_BoxSelect1d
    BoxSelect2d = Native::ImGuiMultiSelectFlags_BoxSelect2d
    BoxSelectNoScroll = Native::ImGuiMultiSelectFlags_BoxSelectNoScroll
    ClearOnEscape = Native::ImGuiMultiSelectFlags_ClearOnEscape
    ClearOnClickVoid = Native::ImGuiMultiSelectFlags_ClearOnClickVoid
    ScopeWindow = Native::ImGuiMultiSelectFlags_ScopeWindow
    ScopeRect = Native::ImGuiMultiSelectFlags_ScopeRect
    SelectOnClick = Native::ImGuiMultiSelectFlags_SelectOnClick
    SelectOnClickRelease = Native::ImGuiMultiSelectFlags_SelectOnClickRelease
    NavWrapX = Native::ImGuiMultiSelectFlags_NavWrapX
  end

  module NavLayer
    Main = Native::ImGuiNavLayer_Main
    Menu = Native::ImGuiNavLayer_Menu
    COUNT = Native::ImGuiNavLayer_COUNT
  end

  module NavMoveFlags
    None = Native::ImGuiNavMoveFlags_None
    LoopX = Native::ImGuiNavMoveFlags_LoopX
    LoopY = Native::ImGuiNavMoveFlags_LoopY
    WrapX = Native::ImGuiNavMoveFlags_WrapX
    WrapY = Native::ImGuiNavMoveFlags_WrapY
    WrapMask_ = Native::ImGuiNavMoveFlags_WrapMask_
    AllowCurrentNavId = Native::ImGuiNavMoveFlags_AllowCurrentNavId
    AlsoScoreVisibleSet = Native::ImGuiNavMoveFlags_AlsoScoreVisibleSet
    ScrollToEdgeY = Native::ImGuiNavMoveFlags_ScrollToEdgeY
    Forwarded = Native::ImGuiNavMoveFlags_Forwarded
    DebugNoResult = Native::ImGuiNavMoveFlags_DebugNoResult
    FocusApi = Native::ImGuiNavMoveFlags_FocusApi
    IsTabbing = Native::ImGuiNavMoveFlags_IsTabbing
    IsPageMove = Native::ImGuiNavMoveFlags_IsPageMove
    Activate = Native::ImGuiNavMoveFlags_Activate
    NoSelect = Native::ImGuiNavMoveFlags_NoSelect
    NoSetNavCursorVisible = Native::ImGuiNavMoveFlags_NoSetNavCursorVisible
    NoClearActiveId = Native::ImGuiNavMoveFlags_NoClearActiveId
  end

  module NavRenderCursorFlags
    None = Native::ImGuiNavRenderCursorFlags_None
    Compact = Native::ImGuiNavRenderCursorFlags_Compact
    AlwaysDraw = Native::ImGuiNavRenderCursorFlags_AlwaysDraw
    NoRounding = Native::ImGuiNavRenderCursorFlags_NoRounding
  end

  module NextItemDataFlags
    None = Native::ImGuiNextItemDataFlags_None
    HasWidth = Native::ImGuiNextItemDataFlags_HasWidth
    HasOpen = Native::ImGuiNextItemDataFlags_HasOpen
    HasShortcut = Native::ImGuiNextItemDataFlags_HasShortcut
    HasRefVal = Native::ImGuiNextItemDataFlags_HasRefVal
    HasStorageID = Native::ImGuiNextItemDataFlags_HasStorageID
  end

  module NextWindowDataFlags
    None = Native::ImGuiNextWindowDataFlags_None
    HasPos = Native::ImGuiNextWindowDataFlags_HasPos
    HasSize = Native::ImGuiNextWindowDataFlags_HasSize
    HasContentSize = Native::ImGuiNextWindowDataFlags_HasContentSize
    HasCollapsed = Native::ImGuiNextWindowDataFlags_HasCollapsed
    HasSizeConstraint = Native::ImGuiNextWindowDataFlags_HasSizeConstraint
    HasFocus = Native::ImGuiNextWindowDataFlags_HasFocus
    HasBgAlpha = Native::ImGuiNextWindowDataFlags_HasBgAlpha
    HasScroll = Native::ImGuiNextWindowDataFlags_HasScroll
    HasWindowFlags = Native::ImGuiNextWindowDataFlags_HasWindowFlags
    HasChildFlags = Native::ImGuiNextWindowDataFlags_HasChildFlags
    HasRefreshPolicy = Native::ImGuiNextWindowDataFlags_HasRefreshPolicy
    HasViewport = Native::ImGuiNextWindowDataFlags_HasViewport
    HasDock = Native::ImGuiNextWindowDataFlags_HasDock
    HasWindowClass = Native::ImGuiNextWindowDataFlags_HasWindowClass
  end

  module OldColumnFlags
    None = Native::ImGuiOldColumnFlags_None
    NoBorder = Native::ImGuiOldColumnFlags_NoBorder
    NoResize = Native::ImGuiOldColumnFlags_NoResize
    NoPreserveWidths = Native::ImGuiOldColumnFlags_NoPreserveWidths
    NoForceWithinWindow = Native::ImGuiOldColumnFlags_NoForceWithinWindow
    GrowParentContentsSize = Native::ImGuiOldColumnFlags_GrowParentContentsSize
  end

  module PlotType
    Lines = Native::ImGuiPlotType_Lines
    Histogram = Native::ImGuiPlotType_Histogram
  end

  module PopupFlags
    None = Native::ImGuiPopupFlags_None
    MouseButtonLeft = Native::ImGuiPopupFlags_MouseButtonLeft
    MouseButtonRight = Native::ImGuiPopupFlags_MouseButtonRight
    MouseButtonMiddle = Native::ImGuiPopupFlags_MouseButtonMiddle
    MouseButtonMask_ = Native::ImGuiPopupFlags_MouseButtonMask_
    MouseButtonDefault_ = Native::ImGuiPopupFlags_MouseButtonDefault_
    NoReopen = Native::ImGuiPopupFlags_NoReopen
    NoOpenOverExistingPopup = Native::ImGuiPopupFlags_NoOpenOverExistingPopup
    NoOpenOverItems = Native::ImGuiPopupFlags_NoOpenOverItems
    AnyPopupId = Native::ImGuiPopupFlags_AnyPopupId
    AnyPopupLevel = Native::ImGuiPopupFlags_AnyPopupLevel
    AnyPopup = Native::ImGuiPopupFlags_AnyPopup
  end

  module PopupPositionPolicy
    Default = Native::ImGuiPopupPositionPolicy_Default
    ComboBox = Native::ImGuiPopupPositionPolicy_ComboBox
    Tooltip = Native::ImGuiPopupPositionPolicy_Tooltip
  end

  module ScrollFlags
    None = Native::ImGuiScrollFlags_None
    KeepVisibleEdgeX = Native::ImGuiScrollFlags_KeepVisibleEdgeX
    KeepVisibleEdgeY = Native::ImGuiScrollFlags_KeepVisibleEdgeY
    KeepVisibleCenterX = Native::ImGuiScrollFlags_KeepVisibleCenterX
    KeepVisibleCenterY = Native::ImGuiScrollFlags_KeepVisibleCenterY
    AlwaysCenterX = Native::ImGuiScrollFlags_AlwaysCenterX
    AlwaysCenterY = Native::ImGuiScrollFlags_AlwaysCenterY
    NoScrollParent = Native::ImGuiScrollFlags_NoScrollParent
    MaskX_ = Native::ImGuiScrollFlags_MaskX_
    MaskY_ = Native::ImGuiScrollFlags_MaskY_
  end

  module SelectableFlagsPrivate
    ImGuiSelectableFlags_NoHoldingActiveID = Native::ImGuiSelectableFlags_NoHoldingActiveID
    ImGuiSelectableFlags_SelectOnNav = Native::ImGuiSelectableFlags_SelectOnNav
    ImGuiSelectableFlags_SelectOnClick = Native::ImGuiSelectableFlags_SelectOnClick
    ImGuiSelectableFlags_SelectOnRelease = Native::ImGuiSelectableFlags_SelectOnRelease
    ImGuiSelectableFlags_SpanAvailWidth = Native::ImGuiSelectableFlags_SpanAvailWidth
    ImGuiSelectableFlags_SetNavIdOnHover = Native::ImGuiSelectableFlags_SetNavIdOnHover
    ImGuiSelectableFlags_NoPadWithHalfSpacing = Native::ImGuiSelectableFlags_NoPadWithHalfSpacing
    ImGuiSelectableFlags_NoSetKeyOwner = Native::ImGuiSelectableFlags_NoSetKeyOwner
  end

  module SelectableFlags
    None = Native::ImGuiSelectableFlags_None
    NoAutoClosePopups = Native::ImGuiSelectableFlags_NoAutoClosePopups
    SpanAllColumns = Native::ImGuiSelectableFlags_SpanAllColumns
    AllowDoubleClick = Native::ImGuiSelectableFlags_AllowDoubleClick
    Disabled = Native::ImGuiSelectableFlags_Disabled
    AllowOverlap = Native::ImGuiSelectableFlags_AllowOverlap
    Highlight = Native::ImGuiSelectableFlags_Highlight
  end

  module SelectionRequestType
    None = Native::ImGuiSelectionRequestType_None
    SetAll = Native::ImGuiSelectionRequestType_SetAll
    SetRange = Native::ImGuiSelectionRequestType_SetRange
  end

  module SeparatorFlags
    None = Native::ImGuiSeparatorFlags_None
    Horizontal = Native::ImGuiSeparatorFlags_Horizontal
    Vertical = Native::ImGuiSeparatorFlags_Vertical
    SpanAllColumns = Native::ImGuiSeparatorFlags_SpanAllColumns
  end

  module SliderFlagsPrivate
    ImGuiSliderFlags_Vertical = Native::ImGuiSliderFlags_Vertical
    ImGuiSliderFlags_ReadOnly = Native::ImGuiSliderFlags_ReadOnly
  end

  module SliderFlags
    None = Native::ImGuiSliderFlags_None
    Logarithmic = Native::ImGuiSliderFlags_Logarithmic
    NoRoundToFormat = Native::ImGuiSliderFlags_NoRoundToFormat
    NoInput = Native::ImGuiSliderFlags_NoInput
    WrapAround = Native::ImGuiSliderFlags_WrapAround
    ClampOnInput = Native::ImGuiSliderFlags_ClampOnInput
    ClampZeroRange = Native::ImGuiSliderFlags_ClampZeroRange
    NoSpeedTweaks = Native::ImGuiSliderFlags_NoSpeedTweaks
    AlwaysClamp = Native::ImGuiSliderFlags_AlwaysClamp
    InvalidMask_ = Native::ImGuiSliderFlags_InvalidMask_
  end

  module SortDirection
    None = Native::ImGuiSortDirection_None
    Ascending = Native::ImGuiSortDirection_Ascending
    Descending = Native::ImGuiSortDirection_Descending
  end

  module StyleVar
    Alpha = Native::ImGuiStyleVar_Alpha
    DisabledAlpha = Native::ImGuiStyleVar_DisabledAlpha
    WindowPadding = Native::ImGuiStyleVar_WindowPadding
    WindowRounding = Native::ImGuiStyleVar_WindowRounding
    WindowBorderSize = Native::ImGuiStyleVar_WindowBorderSize
    WindowMinSize = Native::ImGuiStyleVar_WindowMinSize
    WindowTitleAlign = Native::ImGuiStyleVar_WindowTitleAlign
    ChildRounding = Native::ImGuiStyleVar_ChildRounding
    ChildBorderSize = Native::ImGuiStyleVar_ChildBorderSize
    PopupRounding = Native::ImGuiStyleVar_PopupRounding
    PopupBorderSize = Native::ImGuiStyleVar_PopupBorderSize
    FramePadding = Native::ImGuiStyleVar_FramePadding
    FrameRounding = Native::ImGuiStyleVar_FrameRounding
    FrameBorderSize = Native::ImGuiStyleVar_FrameBorderSize
    ItemSpacing = Native::ImGuiStyleVar_ItemSpacing
    ItemInnerSpacing = Native::ImGuiStyleVar_ItemInnerSpacing
    IndentSpacing = Native::ImGuiStyleVar_IndentSpacing
    CellPadding = Native::ImGuiStyleVar_CellPadding
    ScrollbarSize = Native::ImGuiStyleVar_ScrollbarSize
    ScrollbarRounding = Native::ImGuiStyleVar_ScrollbarRounding
    GrabMinSize = Native::ImGuiStyleVar_GrabMinSize
    GrabRounding = Native::ImGuiStyleVar_GrabRounding
    ImageBorderSize = Native::ImGuiStyleVar_ImageBorderSize
    TabRounding = Native::ImGuiStyleVar_TabRounding
    TabBorderSize = Native::ImGuiStyleVar_TabBorderSize
    TabBarBorderSize = Native::ImGuiStyleVar_TabBarBorderSize
    TabBarOverlineSize = Native::ImGuiStyleVar_TabBarOverlineSize
    TableAngledHeadersAngle = Native::ImGuiStyleVar_TableAngledHeadersAngle
    TableAngledHeadersTextAlign = Native::ImGuiStyleVar_TableAngledHeadersTextAlign
    ButtonTextAlign = Native::ImGuiStyleVar_ButtonTextAlign
    SelectableTextAlign = Native::ImGuiStyleVar_SelectableTextAlign
    SeparatorTextBorderSize = Native::ImGuiStyleVar_SeparatorTextBorderSize
    SeparatorTextAlign = Native::ImGuiStyleVar_SeparatorTextAlign
    SeparatorTextPadding = Native::ImGuiStyleVar_SeparatorTextPadding
    DockingSeparatorSize = Native::ImGuiStyleVar_DockingSeparatorSize
    COUNT = Native::ImGuiStyleVar_COUNT
  end

  module TabBarFlagsPrivate
    ImGuiTabBarFlags_DockNode = Native::ImGuiTabBarFlags_DockNode
    ImGuiTabBarFlags_IsFocused = Native::ImGuiTabBarFlags_IsFocused
    ImGuiTabBarFlags_SaveSettings = Native::ImGuiTabBarFlags_SaveSettings
  end

  module TabBarFlags
    None = Native::ImGuiTabBarFlags_None
    Reorderable = Native::ImGuiTabBarFlags_Reorderable
    AutoSelectNewTabs = Native::ImGuiTabBarFlags_AutoSelectNewTabs
    TabListPopupButton = Native::ImGuiTabBarFlags_TabListPopupButton
    NoCloseWithMiddleMouseButton = Native::ImGuiTabBarFlags_NoCloseWithMiddleMouseButton
    NoTabListScrollingButtons = Native::ImGuiTabBarFlags_NoTabListScrollingButtons
    NoTooltip = Native::ImGuiTabBarFlags_NoTooltip
    DrawSelectedOverline = Native::ImGuiTabBarFlags_DrawSelectedOverline
    FittingPolicyResizeDown = Native::ImGuiTabBarFlags_FittingPolicyResizeDown
    FittingPolicyScroll = Native::ImGuiTabBarFlags_FittingPolicyScroll
    FittingPolicyMask_ = Native::ImGuiTabBarFlags_FittingPolicyMask_
    FittingPolicyDefault_ = Native::ImGuiTabBarFlags_FittingPolicyDefault_
  end

  module TabItemFlagsPrivate
    ImGuiTabItemFlags_SectionMask_ = Native::ImGuiTabItemFlags_SectionMask_
    ImGuiTabItemFlags_NoCloseButton = Native::ImGuiTabItemFlags_NoCloseButton
    ImGuiTabItemFlags_Button = Native::ImGuiTabItemFlags_Button
    ImGuiTabItemFlags_Invisible = Native::ImGuiTabItemFlags_Invisible
    ImGuiTabItemFlags_Unsorted = Native::ImGuiTabItemFlags_Unsorted
  end

  module TabItemFlags
    None = Native::ImGuiTabItemFlags_None
    UnsavedDocument = Native::ImGuiTabItemFlags_UnsavedDocument
    SetSelected = Native::ImGuiTabItemFlags_SetSelected
    NoCloseWithMiddleMouseButton = Native::ImGuiTabItemFlags_NoCloseWithMiddleMouseButton
    NoPushId = Native::ImGuiTabItemFlags_NoPushId
    NoTooltip = Native::ImGuiTabItemFlags_NoTooltip
    NoReorder = Native::ImGuiTabItemFlags_NoReorder
    Leading = Native::ImGuiTabItemFlags_Leading
    Trailing = Native::ImGuiTabItemFlags_Trailing
    NoAssumedClosure = Native::ImGuiTabItemFlags_NoAssumedClosure
  end

  module TableBgTarget
    None = Native::ImGuiTableBgTarget_None
    RowBg0 = Native::ImGuiTableBgTarget_RowBg0
    RowBg1 = Native::ImGuiTableBgTarget_RowBg1
    CellBg = Native::ImGuiTableBgTarget_CellBg
  end

  module TableColumnFlags
    None = Native::ImGuiTableColumnFlags_None
    Disabled = Native::ImGuiTableColumnFlags_Disabled
    DefaultHide = Native::ImGuiTableColumnFlags_DefaultHide
    DefaultSort = Native::ImGuiTableColumnFlags_DefaultSort
    WidthStretch = Native::ImGuiTableColumnFlags_WidthStretch
    WidthFixed = Native::ImGuiTableColumnFlags_WidthFixed
    NoResize = Native::ImGuiTableColumnFlags_NoResize
    NoReorder = Native::ImGuiTableColumnFlags_NoReorder
    NoHide = Native::ImGuiTableColumnFlags_NoHide
    NoClip = Native::ImGuiTableColumnFlags_NoClip
    NoSort = Native::ImGuiTableColumnFlags_NoSort
    NoSortAscending = Native::ImGuiTableColumnFlags_NoSortAscending
    NoSortDescending = Native::ImGuiTableColumnFlags_NoSortDescending
    NoHeaderLabel = Native::ImGuiTableColumnFlags_NoHeaderLabel
    NoHeaderWidth = Native::ImGuiTableColumnFlags_NoHeaderWidth
    PreferSortAscending = Native::ImGuiTableColumnFlags_PreferSortAscending
    PreferSortDescending = Native::ImGuiTableColumnFlags_PreferSortDescending
    IndentEnable = Native::ImGuiTableColumnFlags_IndentEnable
    IndentDisable = Native::ImGuiTableColumnFlags_IndentDisable
    AngledHeader = Native::ImGuiTableColumnFlags_AngledHeader
    IsEnabled = Native::ImGuiTableColumnFlags_IsEnabled
    IsVisible = Native::ImGuiTableColumnFlags_IsVisible
    IsSorted = Native::ImGuiTableColumnFlags_IsSorted
    IsHovered = Native::ImGuiTableColumnFlags_IsHovered
    WidthMask_ = Native::ImGuiTableColumnFlags_WidthMask_
    IndentMask_ = Native::ImGuiTableColumnFlags_IndentMask_
    StatusMask_ = Native::ImGuiTableColumnFlags_StatusMask_
    NoDirectResize_ = Native::ImGuiTableColumnFlags_NoDirectResize_
  end

  module TableFlags
    None = Native::ImGuiTableFlags_None
    Resizable = Native::ImGuiTableFlags_Resizable
    Reorderable = Native::ImGuiTableFlags_Reorderable
    Hideable = Native::ImGuiTableFlags_Hideable
    Sortable = Native::ImGuiTableFlags_Sortable
    NoSavedSettings = Native::ImGuiTableFlags_NoSavedSettings
    ContextMenuInBody = Native::ImGuiTableFlags_ContextMenuInBody
    RowBg = Native::ImGuiTableFlags_RowBg
    BordersInnerH = Native::ImGuiTableFlags_BordersInnerH
    BordersOuterH = Native::ImGuiTableFlags_BordersOuterH
    BordersInnerV = Native::ImGuiTableFlags_BordersInnerV
    BordersOuterV = Native::ImGuiTableFlags_BordersOuterV
    BordersH = Native::ImGuiTableFlags_BordersH
    BordersV = Native::ImGuiTableFlags_BordersV
    BordersInner = Native::ImGuiTableFlags_BordersInner
    BordersOuter = Native::ImGuiTableFlags_BordersOuter
    Borders = Native::ImGuiTableFlags_Borders
    NoBordersInBody = Native::ImGuiTableFlags_NoBordersInBody
    NoBordersInBodyUntilResize = Native::ImGuiTableFlags_NoBordersInBodyUntilResize
    SizingFixedFit = Native::ImGuiTableFlags_SizingFixedFit
    SizingFixedSame = Native::ImGuiTableFlags_SizingFixedSame
    SizingStretchProp = Native::ImGuiTableFlags_SizingStretchProp
    SizingStretchSame = Native::ImGuiTableFlags_SizingStretchSame
    NoHostExtendX = Native::ImGuiTableFlags_NoHostExtendX
    NoHostExtendY = Native::ImGuiTableFlags_NoHostExtendY
    NoKeepColumnsVisible = Native::ImGuiTableFlags_NoKeepColumnsVisible
    PreciseWidths = Native::ImGuiTableFlags_PreciseWidths
    NoClip = Native::ImGuiTableFlags_NoClip
    PadOuterX = Native::ImGuiTableFlags_PadOuterX
    NoPadOuterX = Native::ImGuiTableFlags_NoPadOuterX
    NoPadInnerX = Native::ImGuiTableFlags_NoPadInnerX
    ScrollX = Native::ImGuiTableFlags_ScrollX
    ScrollY = Native::ImGuiTableFlags_ScrollY
    SortMulti = Native::ImGuiTableFlags_SortMulti
    SortTristate = Native::ImGuiTableFlags_SortTristate
    HighlightHoveredColumn = Native::ImGuiTableFlags_HighlightHoveredColumn
    SizingMask_ = Native::ImGuiTableFlags_SizingMask_
  end

  module TableRowFlags
    None = Native::ImGuiTableRowFlags_None
    Headers = Native::ImGuiTableRowFlags_Headers
  end

  module TextFlags
    None = Native::ImGuiTextFlags_None
    NoWidthForLargeClippedText = Native::ImGuiTextFlags_NoWidthForLargeClippedText
  end

  module TooltipFlags
    None = Native::ImGuiTooltipFlags_None
    OverridePrevious = Native::ImGuiTooltipFlags_OverridePrevious
  end

  module TreeNodeFlagsPrivate
    ImGuiTreeNodeFlags_ClipLabelForTrailingButton = Native::ImGuiTreeNodeFlags_ClipLabelForTrailingButton
    ImGuiTreeNodeFlags_UpsideDownArrow = Native::ImGuiTreeNodeFlags_UpsideDownArrow
    ImGuiTreeNodeFlags_OpenOnMask_ = Native::ImGuiTreeNodeFlags_OpenOnMask_
  end

  module TreeNodeFlags
    None = Native::ImGuiTreeNodeFlags_None
    Selected = Native::ImGuiTreeNodeFlags_Selected
    Framed = Native::ImGuiTreeNodeFlags_Framed
    AllowOverlap = Native::ImGuiTreeNodeFlags_AllowOverlap
    NoTreePushOnOpen = Native::ImGuiTreeNodeFlags_NoTreePushOnOpen
    NoAutoOpenOnLog = Native::ImGuiTreeNodeFlags_NoAutoOpenOnLog
    DefaultOpen = Native::ImGuiTreeNodeFlags_DefaultOpen
    OpenOnDoubleClick = Native::ImGuiTreeNodeFlags_OpenOnDoubleClick
    OpenOnArrow = Native::ImGuiTreeNodeFlags_OpenOnArrow
    Leaf = Native::ImGuiTreeNodeFlags_Leaf
    Bullet = Native::ImGuiTreeNodeFlags_Bullet
    FramePadding = Native::ImGuiTreeNodeFlags_FramePadding
    SpanAvailWidth = Native::ImGuiTreeNodeFlags_SpanAvailWidth
    SpanFullWidth = Native::ImGuiTreeNodeFlags_SpanFullWidth
    SpanLabelWidth = Native::ImGuiTreeNodeFlags_SpanLabelWidth
    SpanAllColumns = Native::ImGuiTreeNodeFlags_SpanAllColumns
    LabelSpanAllColumns = Native::ImGuiTreeNodeFlags_LabelSpanAllColumns
    NavLeftJumpsBackHere = Native::ImGuiTreeNodeFlags_NavLeftJumpsBackHere
    CollapsingHeader = Native::ImGuiTreeNodeFlags_CollapsingHeader
  end

  module TypingSelectFlags
    None = Native::ImGuiTypingSelectFlags_None
    AllowBackspace = Native::ImGuiTypingSelectFlags_AllowBackspace
    AllowSingleCharMode = Native::ImGuiTypingSelectFlags_AllowSingleCharMode
  end

  module ViewportFlags
    None = Native::ImGuiViewportFlags_None
    IsPlatformWindow = Native::ImGuiViewportFlags_IsPlatformWindow
    IsPlatformMonitor = Native::ImGuiViewportFlags_IsPlatformMonitor
    OwnedByApp = Native::ImGuiViewportFlags_OwnedByApp
    NoDecoration = Native::ImGuiViewportFlags_NoDecoration
    NoTaskBarIcon = Native::ImGuiViewportFlags_NoTaskBarIcon
    NoFocusOnAppearing = Native::ImGuiViewportFlags_NoFocusOnAppearing
    NoFocusOnClick = Native::ImGuiViewportFlags_NoFocusOnClick
    NoInputs = Native::ImGuiViewportFlags_NoInputs
    NoRendererClear = Native::ImGuiViewportFlags_NoRendererClear
    NoAutoMerge = Native::ImGuiViewportFlags_NoAutoMerge
    TopMost = Native::ImGuiViewportFlags_TopMost
    CanHostOtherWindows = Native::ImGuiViewportFlags_CanHostOtherWindows
    IsMinimized = Native::ImGuiViewportFlags_IsMinimized
    IsFocused = Native::ImGuiViewportFlags_IsFocused
  end

  module WindowDockStyleCol
    Text = Native::ImGuiWindowDockStyleCol_Text
    TabHovered = Native::ImGuiWindowDockStyleCol_TabHovered
    TabFocused = Native::ImGuiWindowDockStyleCol_TabFocused
    TabSelected = Native::ImGuiWindowDockStyleCol_TabSelected
    TabSelectedOverline = Native::ImGuiWindowDockStyleCol_TabSelectedOverline
    TabDimmed = Native::ImGuiWindowDockStyleCol_TabDimmed
    TabDimmedSelected = Native::ImGuiWindowDockStyleCol_TabDimmedSelected
    TabDimmedSelectedOverline = Native::ImGuiWindowDockStyleCol_TabDimmedSelectedOverline
    COUNT = Native::ImGuiWindowDockStyleCol_COUNT
  end

  module WindowFlags
    None = Native::ImGuiWindowFlags_None
    NoTitleBar = Native::ImGuiWindowFlags_NoTitleBar
    NoResize = Native::ImGuiWindowFlags_NoResize
    NoMove = Native::ImGuiWindowFlags_NoMove
    NoScrollbar = Native::ImGuiWindowFlags_NoScrollbar
    NoScrollWithMouse = Native::ImGuiWindowFlags_NoScrollWithMouse
    NoCollapse = Native::ImGuiWindowFlags_NoCollapse
    AlwaysAutoResize = Native::ImGuiWindowFlags_AlwaysAutoResize
    NoBackground = Native::ImGuiWindowFlags_NoBackground
    NoSavedSettings = Native::ImGuiWindowFlags_NoSavedSettings
    NoMouseInputs = Native::ImGuiWindowFlags_NoMouseInputs
    MenuBar = Native::ImGuiWindowFlags_MenuBar
    HorizontalScrollbar = Native::ImGuiWindowFlags_HorizontalScrollbar
    NoFocusOnAppearing = Native::ImGuiWindowFlags_NoFocusOnAppearing
    NoBringToFrontOnFocus = Native::ImGuiWindowFlags_NoBringToFrontOnFocus
    AlwaysVerticalScrollbar = Native::ImGuiWindowFlags_AlwaysVerticalScrollbar
    AlwaysHorizontalScrollbar = Native::ImGuiWindowFlags_AlwaysHorizontalScrollbar
    NoNavInputs = Native::ImGuiWindowFlags_NoNavInputs
    NoNavFocus = Native::ImGuiWindowFlags_NoNavFocus
    UnsavedDocument = Native::ImGuiWindowFlags_UnsavedDocument
    NoDocking = Native::ImGuiWindowFlags_NoDocking
    NoNav = Native::ImGuiWindowFlags_NoNav
    NoDecoration = Native::ImGuiWindowFlags_NoDecoration
    NoInputs = Native::ImGuiWindowFlags_NoInputs
    DockNodeHost = Native::ImGuiWindowFlags_DockNodeHost
    ChildWindow = Native::ImGuiWindowFlags_ChildWindow
    Tooltip = Native::ImGuiWindowFlags_Tooltip
    Popup = Native::ImGuiWindowFlags_Popup
    Modal = Native::ImGuiWindowFlags_Modal
    ChildMenu = Native::ImGuiWindowFlags_ChildMenu
  end

  module WindowRefreshFlags
    None = Native::ImGuiWindowRefreshFlags_None
    TryToAvoidRefresh = Native::ImGuiWindowRefreshFlags_TryToAvoidRefresh
    RefreshOnHover = Native::ImGuiWindowRefreshFlags_RefreshOnHover
    RefreshOnFocus = Native::ImGuiWindowRefreshFlags_RefreshOnFocus
  end
end
