# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    class ImBitVector < FFI::Struct; end
    class ImColor < FFI::Struct; end
    class ImDrawChannel < FFI::Struct; end
    class ImDrawCmd < FFI::Struct; end
    class ImDrawCmdHeader < FFI::Struct; end
    class ImDrawData < FFI::Struct; end
    class ImDrawDataBuilder < FFI::Struct; end
    class ImDrawList < FFI::Struct; end
    class ImDrawListSharedData < FFI::Struct; end
    class ImDrawListSplitter < FFI::Struct; end
    class ImDrawVert < FFI::Struct; end
    class ImFont < FFI::Struct; end
    class ImFontAtlas < FFI::Struct; end
    class ImFontAtlasCustomRect < FFI::Struct; end
    class ImFontBuilderIO < FFI::Struct; end
    class ImFontConfig < FFI::Struct; end
    class ImFontGlyph < FFI::Struct; end
    class ImFontGlyphRangesBuilder < FFI::Struct; end
    class ImGuiBoxSelectState < FFI::Struct; end
    class ImGuiColorMod < FFI::Struct; end
    class ImGuiComboPreviewData < FFI::Struct; end
    class ImGuiContext < FFI::Struct; end
    class ImGuiContextHook < FFI::Struct; end
    class ImGuiDataTypeInfo < FFI::Struct; end
    class ImGuiDataTypeStorage < FFI::Struct; end
    class ImGuiDeactivatedItemData < FFI::Struct; end
    class ImGuiDebugAllocEntry < FFI::Struct; end
    class ImGuiDebugAllocInfo < FFI::Struct; end
    class ImGuiDockContext < FFI::Struct; end
    class ImGuiDockNode < FFI::Struct; end
    class ImGuiErrorRecoveryState < FFI::Struct; end
    class ImGuiFocusScopeData < FFI::Struct; end
    class ImGuiGroupData < FFI::Struct; end
    class ImGuiIDStackTool < FFI::Struct; end
    class ImGuiIO < FFI::Struct; end
    class ImGuiInputEvent < FFI::Struct; end
    class ImGuiInputEventAppFocused < FFI::Struct; end
    class ImGuiInputEventKey < FFI::Struct; end
    class ImGuiInputEventMouseButton < FFI::Struct; end
    class ImGuiInputEventMousePos < FFI::Struct; end
    class ImGuiInputEventMouseViewport < FFI::Struct; end
    class ImGuiInputEventMouseWheel < FFI::Struct; end
    class ImGuiInputEventText < FFI::Struct; end
    class ImGuiInputTextCallbackData < FFI::Struct; end
    class ImGuiInputTextDeactivatedState < FFI::Struct; end
    class ImGuiInputTextState < FFI::Struct; end
    class ImGuiKeyData < FFI::Struct; end
    class ImGuiKeyOwnerData < FFI::Struct; end
    class ImGuiKeyRoutingData < FFI::Struct; end
    class ImGuiKeyRoutingTable < FFI::Struct; end
    class ImGuiLastItemData < FFI::Struct; end
    class ImGuiListClipper < FFI::Struct; end
    class ImGuiListClipperData < FFI::Struct; end
    class ImGuiListClipperRange < FFI::Struct; end
    class ImGuiLocEntry < FFI::Struct; end
    class ImGuiMenuColumns < FFI::Struct; end
    class ImGuiMetricsConfig < FFI::Struct; end
    class ImGuiMultiSelectIO < FFI::Struct; end
    class ImGuiMultiSelectState < FFI::Struct; end
    class ImGuiMultiSelectTempData < FFI::Struct; end
    class ImGuiNavItemData < FFI::Struct; end
    class ImGuiNextItemData < FFI::Struct; end
    class ImGuiNextWindowData < FFI::Struct; end
    class ImGuiOldColumnData < FFI::Struct; end
    class ImGuiOldColumns < FFI::Struct; end
    class ImGuiOnceUponAFrame < FFI::Struct; end
    class ImGuiPayload < FFI::Struct; end
    class ImGuiPlatformIO < FFI::Struct; end
    class ImGuiPlatformImeData < FFI::Struct; end
    class ImGuiPlatformMonitor < FFI::Struct; end
    class ImGuiPopupData < FFI::Struct; end
    class ImGuiPtrOrIndex < FFI::Struct; end
    class ImGuiSelectionBasicStorage < FFI::Struct; end
    class ImGuiSelectionExternalStorage < FFI::Struct; end
    class ImGuiSelectionRequest < FFI::Struct; end
    class ImGuiSettingsHandler < FFI::Struct; end
    class ImGuiShrinkWidthItem < FFI::Struct; end
    class ImGuiSizeCallbackData < FFI::Struct; end
    class ImGuiStackLevelInfo < FFI::Struct; end
    class ImGuiStorage < FFI::Struct; end
    class ImGuiStoragePair < FFI::Struct; end
    class ImGuiStyle < FFI::Struct; end
    class ImGuiStyleMod < FFI::Struct; end
    class ImGuiStyleVarInfo < FFI::Struct; end
    class ImGuiTabBar < FFI::Struct; end
    class ImGuiTabItem < FFI::Struct; end
    class ImGuiTable < FFI::Struct; end
    class ImGuiTableCellData < FFI::Struct; end
    class ImGuiTableColumn < FFI::Struct; end
    class ImGuiTableColumnSettings < FFI::Struct; end
    class ImGuiTableColumnSortSpecs < FFI::Struct; end
    class ImGuiTableHeaderData < FFI::Struct; end
    class ImGuiTableInstanceData < FFI::Struct; end
    class ImGuiTableSettings < FFI::Struct; end
    class ImGuiTableSortSpecs < FFI::Struct; end
    class ImGuiTableTempData < FFI::Struct; end
    class ImGuiTextBuffer < FFI::Struct; end
    class ImGuiTextFilter < FFI::Struct; end
    class ImGuiTextIndex < FFI::Struct; end
    class ImGuiTextRange < FFI::Struct; end
    class ImGuiTreeNodeStackData < FFI::Struct; end
    class ImGuiTypingSelectRequest < FFI::Struct; end
    class ImGuiTypingSelectState < FFI::Struct; end
    class ImGuiViewport < FFI::Struct; end
    class ImGuiViewportP < FFI::Struct; end
    class ImGuiWindow < FFI::Struct; end
    class ImGuiWindowClass < FFI::Struct; end
    class ImGuiWindowDockStyle < FFI::Struct; end
    class ImGuiWindowSettings < FFI::Struct; end
    class ImGuiWindowStackData < FFI::Struct; end
    class ImGuiWindowTempData < FFI::Struct; end
    class ImRect < FFI::Struct; end
    class ImVec1 < FFI::Struct; end
    class ImVec2 < FFI::Struct; end
    class ImVec2ih < FFI::Struct; end
    class ImVec4 < FFI::Struct; end
    class ImVector < FFI::Struct; end

    ImVector.layout(
        "Size", :int,
        "Capacity", :int,
        "Data", :pointer
    )
    ImBitVector.layout(
        "Storage", ImVector.by_value
    )
    ImVec4.layout(
        "x", :float,
        "y", :float,
        "z", :float,
        "w", :float
    )
    ImColor.layout(
        "Value", ImVec4.by_value
    )
    ImDrawChannel.layout(
        "_CmdBuffer", ImVector.by_value,
        "_IdxBuffer", ImVector.by_value
    )
    ImDrawCmd.layout(
        "ClipRect", ImVec4.by_value,
        "TextureId", :ulong_long,
        "VtxOffset", :uint,
        "IdxOffset", :uint,
        "ElemCount", :uint,
        "UserCallback", :ImDrawCallback,
        "UserCallbackData", :pointer,
        "UserCallbackDataSize", :int,
        "UserCallbackDataOffset", :int
    )
    ImDrawCmdHeader.layout(
        "ClipRect", ImVec4.by_value,
        "TextureId", :ulong_long,
        "VtxOffset", :uint
    )
    ImVec2.layout(
        "x", :float,
        "y", :float
    )
    ImDrawData.layout(
        "Valid", :bool,
        "CmdListsCount", :int,
        "TotalIdxCount", :int,
        "TotalVtxCount", :int,
        "CmdLists", ImVector.by_value,
        "DisplayPos", ImVec2.by_value,
        "DisplaySize", ImVec2.by_value,
        "FramebufferScale", ImVec2.by_value,
        "OwnerViewport", :pointer
    )
    ImDrawDataBuilder.layout(
        "Layers[2]", [:pointer, 2],
        "LayerData1", ImVector.by_value
    )
    ImDrawListSplitter.layout(
        "_Current", :int,
        "_Count", :int,
        "_Channels", ImVector.by_value
    )
    ImDrawList.layout(
        "CmdBuffer", ImVector.by_value,
        "IdxBuffer", ImVector.by_value,
        "VtxBuffer", ImVector.by_value,
        "Flags", :int,
        "_VtxCurrentIdx", :uint,
        "_Data", :pointer,
        "_VtxWritePtr", :pointer,
        "_IdxWritePtr", :pointer,
        "_Path", ImVector.by_value,
        "_CmdHeader", ImDrawCmdHeader.by_value,
        "_Splitter", ImDrawListSplitter.by_value,
        "_ClipRectStack", ImVector.by_value,
        "_TextureIdStack", ImVector.by_value,
        "_CallbacksDataBuf", ImVector.by_value,
        "_FringeScale", :float,
        "_OwnerName", :pointer
    )
    ImDrawListSharedData.layout(
        "TexUvWhitePixel", ImVec2.by_value,
        "TexUvLines", :pointer,
        "Font", :pointer,
        "FontSize", :float,
        "FontScale", :float,
        "CurveTessellationTol", :float,
        "CircleSegmentMaxError", :float,
        "InitialFringeScale", :float,
        "InitialFlags", :int,
        "ClipRectFullscreen", ImVec4.by_value,
        "TempBuffer", ImVector.by_value,
        "ArcFastVtx[48]", [ImVec2.by_value, 48],
        "ArcFastRadiusCutoff", :float,
        "CircleSegmentCounts[64]", [:uchar, 64]
    )
    ImDrawVert.layout(
        "pos", ImVec2.by_value,
        "uv", ImVec2.by_value,
        "col", :uint
    )
    ImFont.layout(
        "IndexAdvanceX", ImVector.by_value,
        "FallbackAdvanceX", :float,
        "FontSize", :float,
        "IndexLookup", ImVector.by_value,
        "Glyphs", ImVector.by_value,
        "FallbackGlyph", :pointer,
        "ContainerAtlas", :pointer,
        "Sources", :pointer,
        "SourcesCount", :short,
        "EllipsisCharCount", :short,
        "EllipsisChar", :ushort,
        "FallbackChar", :ushort,
        "EllipsisWidth", :float,
        "EllipsisCharStep", :float,
        "Scale", :float,
        "Ascent", :float,
        "Descent", :float,
        "MetricsTotalSurface", :int,
        "DirtyLookupTables", :bool,
        "Used8kPagesMap[(0xFFFF+1)/8192/8]", [:uchar, 1]
    )
    ImFontAtlas.layout(
        "Flags", :int,
        "TexID", :ulong_long,
        "TexDesiredWidth", :int,
        "TexGlyphPadding", :int,
        "UserData", :pointer,
        "Locked", :bool,
        "TexReady", :bool,
        "TexPixelsUseColors", :bool,
        "TexPixelsAlpha8", :pointer,
        "TexPixelsRGBA32", :pointer,
        "TexWidth", :int,
        "TexHeight", :int,
        "TexUvScale", ImVec2.by_value,
        "TexUvWhitePixel", ImVec2.by_value,
        "Fonts", ImVector.by_value,
        "CustomRects", ImVector.by_value,
        "Sources", ImVector.by_value,
        "TexUvLines[(32)+1]", [ImVec4.by_value, 33],
        "FontBuilderIO", :pointer,
        "FontBuilderFlags", :uint,
        "PackIdMouseCursors", :int,
        "PackIdLines", :int
    )
    ImFontAtlasCustomRect.layout(
        "X", :ushort,
        "Y", :ushort,
        "Width", :ushort,
        "Height", :ushort,
        "_bitfield_1", :uint,
        "GlyphAdvanceX", :float,
        "GlyphOffset", ImVec2.by_value,
        "Font", :pointer
    )
    ImFontBuilderIO.layout(
        "FontBuilder_Build", :pointer
    )
    ImFontConfig.layout(
        "FontData", :pointer,
        "FontDataSize", :int,
        "FontDataOwnedByAtlas", :bool,
        "MergeMode", :bool,
        "PixelSnapH", :bool,
        "FontNo", :int,
        "OversampleH", :int,
        "OversampleV", :int,
        "SizePixels", :float,
        "GlyphOffset", ImVec2.by_value,
        "GlyphRanges", :pointer,
        "GlyphMinAdvanceX", :float,
        "GlyphMaxAdvanceX", :float,
        "GlyphExtraAdvanceX", :float,
        "FontBuilderFlags", :uint,
        "RasterizerMultiply", :float,
        "RasterizerDensity", :float,
        "EllipsisChar", :ushort,
        "Name[40]", [:char, 40],
        "DstFont", :pointer
    )
    ImFontGlyph.layout(
        "_bitfield_1", :uint,
        "AdvanceX", :float,
        "X0", :float,
        "Y0", :float,
        "X1", :float,
        "Y1", :float,
        "U0", :float,
        "V0", :float,
        "U1", :float,
        "V1", :float
    )
    ImFontGlyphRangesBuilder.layout(
        "UsedChars", ImVector.by_value
    )
    ImRect.layout(
        "Min", ImVec2.by_value,
        "Max", ImVec2.by_value
    )
    ImGuiBoxSelectState.layout(
        "ID", :uint,
        "IsActive", :bool,
        "IsStarting", :bool,
        "IsStartedFromVoid", :bool,
        "IsStartedSetNavIdOnce", :bool,
        "RequestClear", :bool,
        "_bitfield_1", :int,
        "StartPosRel", ImVec2.by_value,
        "EndPosRel", ImVec2.by_value,
        "ScrollAccum", ImVec2.by_value,
        "Window", :pointer,
        "UnclipMode", :bool,
        "UnclipRect", ImRect.by_value,
        "BoxSelectRectPrev", ImRect.by_value,
        "BoxSelectRectCurr", ImRect.by_value
    )
    ImGuiColorMod.layout(
        "Col", :int,
        "BackupValue", ImVec4.by_value
    )
    ImGuiComboPreviewData.layout(
        "PreviewRect", ImRect.by_value,
        "BackupCursorPos", ImVec2.by_value,
        "BackupCursorMaxPos", ImVec2.by_value,
        "BackupCursorPosPrevLine", ImVec2.by_value,
        "BackupPrevLineTextBaseOffset", :float,
        "BackupLayout", :int
    )
    ImGuiKeyData.layout(
        "Down", :bool,
        "DownDuration", :float,
        "DownDurationPrev", :float,
        "AnalogValue", :float
    )
    ImGuiIO.layout(
        "ConfigFlags", :int,
        "BackendFlags", :int,
        "DisplaySize", ImVec2.by_value,
        "DeltaTime", :float,
        "IniSavingRate", :float,
        "IniFilename", :pointer,
        "LogFilename", :pointer,
        "UserData", :pointer,
        "Fonts", :pointer,
        "FontGlobalScale", :float,
        "FontAllowUserScaling", :bool,
        "FontDefault", :pointer,
        "DisplayFramebufferScale", ImVec2.by_value,
        "ConfigNavSwapGamepadButtons", :bool,
        "ConfigNavMoveSetMousePos", :bool,
        "ConfigNavCaptureKeyboard", :bool,
        "ConfigNavEscapeClearFocusItem", :bool,
        "ConfigNavEscapeClearFocusWindow", :bool,
        "ConfigNavCursorVisibleAuto", :bool,
        "ConfigNavCursorVisibleAlways", :bool,
        "ConfigDockingNoSplit", :bool,
        "ConfigDockingWithShift", :bool,
        "ConfigDockingAlwaysTabBar", :bool,
        "ConfigDockingTransparentPayload", :bool,
        "ConfigViewportsNoAutoMerge", :bool,
        "ConfigViewportsNoTaskBarIcon", :bool,
        "ConfigViewportsNoDecoration", :bool,
        "ConfigViewportsNoDefaultParent", :bool,
        "MouseDrawCursor", :bool,
        "ConfigMacOSXBehaviors", :bool,
        "ConfigInputTrickleEventQueue", :bool,
        "ConfigInputTextCursorBlink", :bool,
        "ConfigInputTextEnterKeepActive", :bool,
        "ConfigDragClickToInputText", :bool,
        "ConfigWindowsResizeFromEdges", :bool,
        "ConfigWindowsMoveFromTitleBarOnly", :bool,
        "ConfigWindowsCopyContentsWithCtrlC", :bool,
        "ConfigScrollbarScrollByPage", :bool,
        "ConfigMemoryCompactTimer", :float,
        "MouseDoubleClickTime", :float,
        "MouseDoubleClickMaxDist", :float,
        "MouseDragThreshold", :float,
        "KeyRepeatDelay", :float,
        "KeyRepeatRate", :float,
        "ConfigErrorRecovery", :bool,
        "ConfigErrorRecoveryEnableAssert", :bool,
        "ConfigErrorRecoveryEnableDebugLog", :bool,
        "ConfigErrorRecoveryEnableTooltip", :bool,
        "ConfigDebugIsDebuggerPresent", :bool,
        "ConfigDebugHighlightIdConflicts", :bool,
        "ConfigDebugHighlightIdConflictsShowItemPicker", :bool,
        "ConfigDebugBeginReturnValueOnce", :bool,
        "ConfigDebugBeginReturnValueLoop", :bool,
        "ConfigDebugIgnoreFocusLoss", :bool,
        "ConfigDebugIniSettings", :bool,
        "BackendPlatformName", :pointer,
        "BackendRendererName", :pointer,
        "BackendPlatformUserData", :pointer,
        "BackendRendererUserData", :pointer,
        "BackendLanguageUserData", :pointer,
        "WantCaptureMouse", :bool,
        "WantCaptureKeyboard", :bool,
        "WantTextInput", :bool,
        "WantSetMousePos", :bool,
        "WantSaveIniSettings", :bool,
        "NavActive", :bool,
        "NavVisible", :bool,
        "Framerate", :float,
        "MetricsRenderVertices", :int,
        "MetricsRenderIndices", :int,
        "MetricsRenderWindows", :int,
        "MetricsActiveWindows", :int,
        "MouseDelta", ImVec2.by_value,
        "Ctx", :pointer,
        "MousePos", ImVec2.by_value,
        "MouseDown[5]", [:bool, 5],
        "MouseWheel", :float,
        "MouseWheelH", :float,
        "MouseSource", :int,
        "MouseHoveredViewport", :uint,
        "KeyCtrl", :bool,
        "KeyShift", :bool,
        "KeyAlt", :bool,
        "KeySuper", :bool,
        "KeyMods", :int,
        "KeysData[ImGuiKey_NamedKey_COUNT]", [ImGuiKeyData.by_value, 155],
        "WantCaptureMouseUnlessPopupClose", :bool,
        "MousePosPrev", ImVec2.by_value,
        "MouseClickedPos[5]", [ImVec2.by_value, 5],
        "MouseClickedTime[5]", [:double, 5],
        "MouseClicked[5]", [:bool, 5],
        "MouseDoubleClicked[5]", [:bool, 5],
        "MouseClickedCount[5]", [:ushort, 5],
        "MouseClickedLastCount[5]", [:ushort, 5],
        "MouseReleased[5]", [:bool, 5],
        "MouseReleasedTime[5]", [:double, 5],
        "MouseDownOwned[5]", [:bool, 5],
        "MouseDownOwnedUnlessPopupClose[5]", [:bool, 5],
        "MouseWheelRequestAxisSwap", :bool,
        "MouseCtrlLeftAsRightClick", :bool,
        "MouseDownDuration[5]", [:float, 5],
        "MouseDownDurationPrev[5]", [:float, 5],
        "MouseDragMaxDistanceAbs[5]", [ImVec2.by_value, 5],
        "MouseDragMaxDistanceSqr[5]", [:float, 5],
        "PenPressure", :float,
        "AppFocusLost", :bool,
        "AppAcceptingEvents", :bool,
        "InputQueueSurrogate", :ushort,
        "InputQueueCharacters", ImVector.by_value
    )
    ImGuiPlatformIO.layout(
        "Platform_GetClipboardTextFn", :pointer,
        "Platform_SetClipboardTextFn", :pointer,
        "Platform_ClipboardUserData", :pointer,
        "Platform_OpenInShellFn", :pointer,
        "Platform_OpenInShellUserData", :pointer,
        "Platform_SetImeDataFn", :pointer,
        "Platform_ImeUserData", :pointer,
        "Platform_LocaleDecimalPoint", :ushort,
        "Renderer_RenderState", :pointer,
        "Platform_CreateWindow", :pointer,
        "Platform_DestroyWindow", :pointer,
        "Platform_ShowWindow", :pointer,
        "Platform_SetWindowPos", :pointer,
        "Platform_GetWindowPos", :pointer,
        "Platform_SetWindowSize", :pointer,
        "Platform_GetWindowSize", :pointer,
        "Platform_SetWindowFocus", :pointer,
        "Platform_GetWindowFocus", :pointer,
        "Platform_GetWindowMinimized", :pointer,
        "Platform_SetWindowTitle", :pointer,
        "Platform_SetWindowAlpha", :pointer,
        "Platform_UpdateWindow", :pointer,
        "Platform_RenderWindow", :pointer,
        "Platform_SwapBuffers", :pointer,
        "Platform_GetWindowDpiScale", :pointer,
        "Platform_OnChangedViewport", :pointer,
        "Platform_GetWindowWorkAreaInsets", :pointer,
        "Platform_CreateVkSurface", :pointer,
        "Renderer_CreateWindow", :pointer,
        "Renderer_DestroyWindow", :pointer,
        "Renderer_SetWindowSize", :pointer,
        "Renderer_RenderWindow", :pointer,
        "Renderer_SwapBuffers", :pointer,
        "Monitors", ImVector.by_value,
        "Viewports", ImVector.by_value
    )
    ImGuiStyle.layout(
        "Alpha", :float,
        "DisabledAlpha", :float,
        "WindowPadding", ImVec2.by_value,
        "WindowRounding", :float,
        "WindowBorderSize", :float,
        "WindowBorderHoverPadding", :float,
        "WindowMinSize", ImVec2.by_value,
        "WindowTitleAlign", ImVec2.by_value,
        "WindowMenuButtonPosition", :int,
        "ChildRounding", :float,
        "ChildBorderSize", :float,
        "PopupRounding", :float,
        "PopupBorderSize", :float,
        "FramePadding", ImVec2.by_value,
        "FrameRounding", :float,
        "FrameBorderSize", :float,
        "ItemSpacing", ImVec2.by_value,
        "ItemInnerSpacing", ImVec2.by_value,
        "CellPadding", ImVec2.by_value,
        "TouchExtraPadding", ImVec2.by_value,
        "IndentSpacing", :float,
        "ColumnsMinSpacing", :float,
        "ScrollbarSize", :float,
        "ScrollbarRounding", :float,
        "GrabMinSize", :float,
        "GrabRounding", :float,
        "LogSliderDeadzone", :float,
        "ImageBorderSize", :float,
        "TabRounding", :float,
        "TabBorderSize", :float,
        "TabCloseButtonMinWidthSelected", :float,
        "TabCloseButtonMinWidthUnselected", :float,
        "TabBarBorderSize", :float,
        "TabBarOverlineSize", :float,
        "TableAngledHeadersAngle", :float,
        "TableAngledHeadersTextAlign", ImVec2.by_value,
        "ColorButtonPosition", :int,
        "ButtonTextAlign", ImVec2.by_value,
        "SelectableTextAlign", ImVec2.by_value,
        "SeparatorTextBorderSize", :float,
        "SeparatorTextAlign", ImVec2.by_value,
        "SeparatorTextPadding", ImVec2.by_value,
        "DisplayWindowPadding", ImVec2.by_value,
        "DisplaySafeAreaPadding", ImVec2.by_value,
        "DockingSeparatorSize", :float,
        "MouseCursorScale", :float,
        "AntiAliasedLines", :bool,
        "AntiAliasedLinesUseTex", :bool,
        "AntiAliasedFill", :bool,
        "CurveTessellationTol", :float,
        "CircleTessellationMaxError", :float,
        "Colors[ImGuiCol_COUNT]", [ImVec4.by_value, 58],
        "HoverStationaryDelay", :float,
        "HoverDelayShort", :float,
        "HoverDelayNormal", :float,
        "HoverFlagsForTooltipMouse", :int,
        "HoverFlagsForTooltipNav", :int
    )
    ImGuiStorage.layout(
        "Data", ImVector.by_value
    )
    ImGuiDeactivatedItemData.layout(
        "ID", :uint,
        "ElapseFrame", :int,
        "HasBeenEditedBefore", :bool,
        "IsAlive", :bool
    )
    ImGuiDataTypeStorage.layout(
        "Data[8]", [:uchar, 8]
    )
    ImGuiKeyOwnerData.layout(
        "OwnerCurr", :uint,
        "OwnerNext", :uint,
        "LockThisFrame", :bool,
        "LockUntilRelease", :bool
    )
    ImGuiKeyRoutingTable.layout(
        "Index[ImGuiKey_NamedKey_COUNT]", [:pointer, 155],
        "Entries", ImVector.by_value,
        "EntriesNext", ImVector.by_value
    )
    ImGuiNextItemData.layout(
        "HasFlags", :int,
        "ItemFlags", :int,
        "FocusScopeId", :uint,
        "SelectionUserData", :pointer,
        "Width", :float,
        "Shortcut", :int,
        "ShortcutFlags", :int,
        "OpenVal", :bool,
        "OpenCond", :uchar,
        "RefVal", ImGuiDataTypeStorage.by_value,
        "StorageId", :uint
    )
    ImGuiLastItemData.layout(
        "ID", :uint,
        "ItemFlags", :int,
        "StatusFlags", :int,
        "Rect", ImRect.by_value,
        "NavRect", ImRect.by_value,
        "DisplayRect", ImRect.by_value,
        "ClipRect", ImRect.by_value,
        "Shortcut", :int
    )
    ImGuiWindowClass.layout(
        "ClassId", :uint,
        "ParentViewportId", :uint,
        "FocusRouteParentWindowId", :uint,
        "ViewportFlagsOverrideSet", :int,
        "ViewportFlagsOverrideClear", :int,
        "TabItemFlagsOverrideSet", :int,
        "DockNodeFlagsOverrideSet", :int,
        "DockingAlwaysTabBar", :bool,
        "DockingAllowUnclassed", :bool
    )
    ImGuiNextWindowData.layout(
        "HasFlags", :int,
        "PosCond", :int,
        "SizeCond", :int,
        "CollapsedCond", :int,
        "DockCond", :int,
        "PosVal", ImVec2.by_value,
        "PosPivotVal", ImVec2.by_value,
        "SizeVal", ImVec2.by_value,
        "ContentSizeVal", ImVec2.by_value,
        "ScrollVal", ImVec2.by_value,
        "WindowFlags", :int,
        "ChildFlags", :int,
        "PosUndock", :bool,
        "CollapsedVal", :bool,
        "SizeConstraintRect", ImRect.by_value,
        "SizeCallback", :ImGuiSizeCallback,
        "SizeCallbackUserData", :pointer,
        "BgAlphaVal", :float,
        "ViewportId", :uint,
        "DockId", :uint,
        "WindowClass", ImGuiWindowClass.by_value,
        "MenuBarOffsetMinVal", ImVec2.by_value,
        "RefreshFlagsVal", :int
    )
    ImGuiPlatformMonitor.layout(
        "MainPos", ImVec2.by_value,
        "MainSize", ImVec2.by_value,
        "WorkPos", ImVec2.by_value,
        "WorkSize", ImVec2.by_value,
        "DpiScale", :float,
        "PlatformHandle", :pointer
    )
    ImGuiNavItemData.layout(
        "Window", :pointer,
        "ID", :uint,
        "FocusScopeId", :uint,
        "RectRel", ImRect.by_value,
        "ItemFlags", :int,
        "DistBox", :float,
        "DistCenter", :float,
        "DistAxial", :float,
        "SelectionUserData", :pointer
    )
    ImGuiPayload.layout(
        "Data", :pointer,
        "DataSize", :int,
        "SourceId", :uint,
        "SourceParentId", :uint,
        "DataFrameCount", :int,
        "DataType[32+1]", [:char, 33],
        "Preview", :bool,
        "Delivery", :bool
    )
    ImGuiInputTextState.layout(
        "Ctx", :pointer,
        "Stb", :pointer,
        "Flags", :int,
        "ID", :uint,
        "TextLen", :int,
        "TextSrc", :pointer,
        "TextA", ImVector.by_value,
        "TextToRevertTo", ImVector.by_value,
        "CallbackTextBackup", ImVector.by_value,
        "BufCapacity", :int,
        "Scroll", ImVec2.by_value,
        "CursorAnim", :float,
        "CursorFollow", :bool,
        "SelectedAllMouseLock", :bool,
        "Edited", :bool,
        "WantReloadUserBuf", :bool,
        "ReloadSelectionStart", :int,
        "ReloadSelectionEnd", :int
    )
    ImGuiInputTextDeactivatedState.layout(
        "ID", :uint,
        "TextA", ImVector.by_value
    )
    ImGuiTypingSelectRequest.layout(
        "Flags", :int,
        "SearchBufferLen", :int,
        "SearchBuffer", :pointer,
        "SelectRequest", :bool,
        "SingleCharMode", :bool,
        "SingleCharSize", :char
    )
    ImGuiTypingSelectState.layout(
        "Request", ImGuiTypingSelectRequest.by_value,
        "SearchBuffer[64]", [:char, 64],
        "FocusScope", :uint,
        "LastRequestFrame", :int,
        "LastRequestTime", :float,
        "SingleCharModeLock", :bool
    )
    ImGuiPlatformImeData.layout(
        "WantVisible", :bool,
        "InputPos", ImVec2.by_value,
        "InputLineHeight", :float
    )
    ImGuiDockContext.layout(
        "Nodes", ImGuiStorage.by_value,
        "Requests", ImVector.by_value,
        "NodesSettings", ImVector.by_value,
        "WantFullRebuild", :bool
    )
    ImGuiTextBuffer.layout(
        "Buf", ImVector.by_value
    )
    ImGuiErrorRecoveryState.layout(
        "SizeOfWindowStack", :short,
        "SizeOfIDStack", :short,
        "SizeOfTreeStack", :short,
        "SizeOfColorStack", :short,
        "SizeOfStyleVarStack", :short,
        "SizeOfFontStack", :short,
        "SizeOfFocusScopeStack", :short,
        "SizeOfGroupStack", :short,
        "SizeOfItemFlagsStack", :short,
        "SizeOfBeginPopupStack", :short,
        "SizeOfDisabledStack", :short
    )
    ImGuiTextIndex.layout(
        "LineOffsets", ImVector.by_value,
        "EndOffset", :int
    )
    ImGuiMetricsConfig.layout(
        "ShowDebugLog", :bool,
        "ShowIDStackTool", :bool,
        "ShowWindowsRects", :bool,
        "ShowWindowsBeginOrder", :bool,
        "ShowTablesRects", :bool,
        "ShowDrawCmdMesh", :bool,
        "ShowDrawCmdBoundingBoxes", :bool,
        "ShowTextEncodingViewer", :bool,
        "ShowDockingNodes", :bool,
        "ShowWindowsRectsType", :int,
        "ShowTablesRectsType", :int,
        "HighlightMonitorIdx", :int,
        "HighlightViewportID", :uint
    )
    ImGuiIDStackTool.layout(
        "LastActiveFrame", :int,
        "StackLevel", :int,
        "QueryId", :uint,
        "Results", ImVector.by_value,
        "CopyToClipboardOnCtrlC", :bool,
        "CopyToClipboardLastTime", :float,
        "ResultPathBuf", ImGuiTextBuffer.by_value
    )
    ImGuiDebugAllocEntry.layout(
        "FrameCount", :int,
        "AllocCount", :pointer,
        "FreeCount", :pointer
    )
    ImGuiDebugAllocInfo.layout(
        "TotalAllocCount", :int,
        "TotalFreeCount", :int,
        "LastEntriesIdx", :pointer,
        "LastEntriesBuf[6]", [ImGuiDebugAllocEntry.by_value, 6]
    )
    ImGuiContext.layout(
        "Initialized", :bool,
        "FontAtlasOwnedByContext", :bool,
        "IO", ImGuiIO.by_value,
        "PlatformIO", ImGuiPlatformIO.by_value,
        "Style", ImGuiStyle.by_value,
        "ConfigFlagsCurrFrame", :int,
        "ConfigFlagsLastFrame", :int,
        "Font", :pointer,
        "FontSize", :float,
        "FontBaseSize", :float,
        "FontScale", :float,
        "CurrentDpiScale", :float,
        "DrawListSharedData", ImDrawListSharedData.by_value,
        "Time", :double,
        "FrameCount", :int,
        "FrameCountEnded", :int,
        "FrameCountPlatformEnded", :int,
        "FrameCountRendered", :int,
        "WithinEndChildID", :uint,
        "WithinFrameScope", :bool,
        "WithinFrameScopeWithImplicitWindow", :bool,
        "GcCompactAll", :bool,
        "TestEngineHookItems", :bool,
        "TestEngine", :pointer,
        "ContextName[16]", [:char, 16],
        "InputEventsQueue", ImVector.by_value,
        "InputEventsTrail", ImVector.by_value,
        "InputEventsNextMouseSource", :int,
        "InputEventsNextEventId", :uint,
        "Windows", ImVector.by_value,
        "WindowsFocusOrder", ImVector.by_value,
        "WindowsTempSortBuffer", ImVector.by_value,
        "CurrentWindowStack", ImVector.by_value,
        "WindowsById", ImGuiStorage.by_value,
        "WindowsActiveCount", :int,
        "WindowsBorderHoverPadding", :float,
        "DebugBreakInWindow", :uint,
        "CurrentWindow", :pointer,
        "HoveredWindow", :pointer,
        "HoveredWindowUnderMovingWindow", :pointer,
        "HoveredWindowBeforeClear", :pointer,
        "MovingWindow", :pointer,
        "WheelingWindow", :pointer,
        "WheelingWindowRefMousePos", ImVec2.by_value,
        "WheelingWindowStartFrame", :int,
        "WheelingWindowScrolledFrame", :int,
        "WheelingWindowReleaseTimer", :float,
        "WheelingWindowWheelRemainder", ImVec2.by_value,
        "WheelingAxisAvg", ImVec2.by_value,
        "DebugDrawIdConflicts", :uint,
        "DebugHookIdInfo", :uint,
        "HoveredId", :uint,
        "HoveredIdPreviousFrame", :uint,
        "HoveredIdPreviousFrameItemCount", :int,
        "HoveredIdTimer", :float,
        "HoveredIdNotActiveTimer", :float,
        "HoveredIdAllowOverlap", :bool,
        "HoveredIdIsDisabled", :bool,
        "ItemUnclipByLog", :bool,
        "ActiveId", :uint,
        "ActiveIdIsAlive", :uint,
        "ActiveIdTimer", :float,
        "ActiveIdIsJustActivated", :bool,
        "ActiveIdAllowOverlap", :bool,
        "ActiveIdNoClearOnFocusLoss", :bool,
        "ActiveIdHasBeenPressedBefore", :bool,
        "ActiveIdHasBeenEditedBefore", :bool,
        "ActiveIdHasBeenEditedThisFrame", :bool,
        "ActiveIdFromShortcut", :bool,
        "_bitfield_1", :int,
        "ActiveIdClickOffset", ImVec2.by_value,
        "ActiveIdWindow", :pointer,
        "ActiveIdSource", :int,
        "ActiveIdPreviousFrame", :uint,
        "DeactivatedItemData", ImGuiDeactivatedItemData.by_value,
        "ActiveIdValueOnActivation", ImGuiDataTypeStorage.by_value,
        "LastActiveId", :uint,
        "LastActiveIdTimer", :float,
        "LastKeyModsChangeTime", :double,
        "LastKeyModsChangeFromNoneTime", :double,
        "LastKeyboardKeyPressTime", :double,
        "KeysMayBeCharInput", :pointer,
        "KeysOwnerData[ImGuiKey_NamedKey_COUNT]", [ImGuiKeyOwnerData.by_value, 155],
        "KeysRoutingTable", ImGuiKeyRoutingTable.by_value,
        "ActiveIdUsingNavDirMask", :uint,
        "ActiveIdUsingAllKeyboardKeys", :bool,
        "DebugBreakInShortcutRouting", :int,
        "CurrentFocusScopeId", :uint,
        "CurrentItemFlags", :int,
        "DebugLocateId", :uint,
        "NextItemData", ImGuiNextItemData.by_value,
        "LastItemData", ImGuiLastItemData.by_value,
        "NextWindowData", ImGuiNextWindowData.by_value,
        "DebugShowGroupRects", :bool,
        "DebugFlashStyleColorIdx", :int,
        "ColorStack", ImVector.by_value,
        "StyleVarStack", ImVector.by_value,
        "FontStack", ImVector.by_value,
        "FocusScopeStack", ImVector.by_value,
        "ItemFlagsStack", ImVector.by_value,
        "GroupStack", ImVector.by_value,
        "OpenPopupStack", ImVector.by_value,
        "BeginPopupStack", ImVector.by_value,
        "TreeNodeStack", ImVector.by_value,
        "Viewports", ImVector.by_value,
        "CurrentViewport", :pointer,
        "MouseViewport", :pointer,
        "MouseLastHoveredViewport", :pointer,
        "PlatformLastFocusedViewportId", :uint,
        "FallbackMonitor", ImGuiPlatformMonitor.by_value,
        "PlatformMonitorsFullWorkRect", ImRect.by_value,
        "ViewportCreatedCount", :int,
        "PlatformWindowsCreatedCount", :int,
        "ViewportFocusedStampCount", :int,
        "NavCursorVisible", :bool,
        "NavHighlightItemUnderNav", :bool,
        "NavMousePosDirty", :bool,
        "NavIdIsAlive", :bool,
        "NavId", :uint,
        "NavWindow", :pointer,
        "NavFocusScopeId", :uint,
        "NavLayer", :int,
        "NavActivateId", :uint,
        "NavActivateDownId", :uint,
        "NavActivatePressedId", :uint,
        "NavActivateFlags", :int,
        "NavFocusRoute", ImVector.by_value,
        "NavHighlightActivatedId", :uint,
        "NavHighlightActivatedTimer", :float,
        "NavNextActivateId", :uint,
        "NavNextActivateFlags", :int,
        "NavInputSource", :int,
        "NavLastValidSelectionUserData", :pointer,
        "NavCursorHideFrames", :char,
        "NavAnyRequest", :bool,
        "NavInitRequest", :bool,
        "NavInitRequestFromMove", :bool,
        "NavInitResult", ImGuiNavItemData.by_value,
        "NavMoveSubmitted", :bool,
        "NavMoveScoringItems", :bool,
        "NavMoveForwardToNextFrame", :bool,
        "NavMoveFlags", :int,
        "NavMoveScrollFlags", :int,
        "NavMoveKeyMods", :int,
        "NavMoveDir", :int,
        "NavMoveDirForDebug", :int,
        "NavMoveClipDir", :int,
        "NavScoringRect", ImRect.by_value,
        "NavScoringNoClipRect", ImRect.by_value,
        "NavScoringDebugCount", :int,
        "NavTabbingDir", :int,
        "NavTabbingCounter", :int,
        "NavMoveResultLocal", ImGuiNavItemData.by_value,
        "NavMoveResultLocalVisible", ImGuiNavItemData.by_value,
        "NavMoveResultOther", ImGuiNavItemData.by_value,
        "NavTabbingResultFirst", ImGuiNavItemData.by_value,
        "NavJustMovedFromFocusScopeId", :uint,
        "NavJustMovedToId", :uint,
        "NavJustMovedToFocusScopeId", :uint,
        "NavJustMovedToKeyMods", :int,
        "NavJustMovedToIsTabbing", :bool,
        "NavJustMovedToHasSelectionData", :bool,
        "ConfigNavWindowingKeyNext", :int,
        "ConfigNavWindowingKeyPrev", :int,
        "NavWindowingTarget", :pointer,
        "NavWindowingTargetAnim", :pointer,
        "NavWindowingListWindow", :pointer,
        "NavWindowingTimer", :float,
        "NavWindowingHighlightAlpha", :float,
        "NavWindowingToggleLayer", :bool,
        "NavWindowingToggleKey", :int,
        "NavWindowingAccumDeltaPos", ImVec2.by_value,
        "NavWindowingAccumDeltaSize", ImVec2.by_value,
        "DimBgRatio", :float,
        "DragDropActive", :bool,
        "DragDropWithinSource", :bool,
        "DragDropWithinTarget", :bool,
        "DragDropSourceFlags", :int,
        "DragDropSourceFrameCount", :int,
        "DragDropMouseButton", :int,
        "DragDropPayload", ImGuiPayload.by_value,
        "DragDropTargetRect", ImRect.by_value,
        "DragDropTargetClipRect", ImRect.by_value,
        "DragDropTargetId", :uint,
        "DragDropAcceptFlags", :int,
        "DragDropAcceptIdCurrRectSurface", :float,
        "DragDropAcceptIdCurr", :uint,
        "DragDropAcceptIdPrev", :uint,
        "DragDropAcceptFrameCount", :int,
        "DragDropHoldJustPressedId", :uint,
        "DragDropPayloadBufHeap", ImVector.by_value,
        "DragDropPayloadBufLocal[16]", [:uchar, 16],
        "ClipperTempDataStacked", :int,
        "ClipperTempData", ImVector.by_value,
        "CurrentTable", :pointer,
        "DebugBreakInTable", :uint,
        "TablesTempDataStacked", :int,
        "TablesTempData", ImVector.by_value,
        "Tables", :pointer,
        "TablesLastTimeActive", ImVector.by_value,
        "DrawChannelsTempMergeBuffer", ImVector.by_value,
        "CurrentTabBar", :pointer,
        "TabBars", :pointer,
        "CurrentTabBarStack", ImVector.by_value,
        "ShrinkWidthBuffer", ImVector.by_value,
        "BoxSelectState", ImGuiBoxSelectState.by_value,
        "CurrentMultiSelect", :pointer,
        "MultiSelectTempDataStacked", :int,
        "MultiSelectTempData", ImVector.by_value,
        "MultiSelectStorage", :pointer,
        "HoverItemDelayId", :uint,
        "HoverItemDelayIdPreviousFrame", :uint,
        "HoverItemDelayTimer", :float,
        "HoverItemDelayClearTimer", :float,
        "HoverItemUnlockedStationaryId", :uint,
        "HoverWindowUnlockedStationaryId", :uint,
        "MouseCursor", :int,
        "MouseStationaryTimer", :float,
        "MouseLastValidPos", ImVec2.by_value,
        "InputTextState", ImGuiInputTextState.by_value,
        "InputTextDeactivatedState", ImGuiInputTextDeactivatedState.by_value,
        "InputTextPasswordFont", ImFont.by_value,
        "TempInputId", :uint,
        "DataTypeZeroValue", ImGuiDataTypeStorage.by_value,
        "BeginMenuDepth", :int,
        "BeginComboDepth", :int,
        "ColorEditOptions", :int,
        "ColorEditCurrentID", :uint,
        "ColorEditSavedID", :uint,
        "ColorEditSavedHue", :float,
        "ColorEditSavedSat", :float,
        "ColorEditSavedColor", :uint,
        "ColorPickerRef", ImVec4.by_value,
        "ComboPreviewData", ImGuiComboPreviewData.by_value,
        "WindowResizeBorderExpectedRect", ImRect.by_value,
        "WindowResizeRelativeMode", :bool,
        "ScrollbarSeekMode", :short,
        "ScrollbarClickDeltaToGrabCenter", :float,
        "SliderGrabClickOffset", :float,
        "SliderCurrentAccum", :float,
        "SliderCurrentAccumDirty", :bool,
        "DragCurrentAccumDirty", :bool,
        "DragCurrentAccum", :float,
        "DragSpeedDefaultRatio", :float,
        "DisabledAlphaBackup", :float,
        "DisabledStackSize", :short,
        "TooltipOverrideCount", :short,
        "TooltipPreviousWindow", :pointer,
        "ClipboardHandlerData", ImVector.by_value,
        "MenusIdSubmittedThisFrame", ImVector.by_value,
        "TypingSelectState", ImGuiTypingSelectState.by_value,
        "PlatformImeData", ImGuiPlatformImeData.by_value,
        "PlatformImeDataPrev", ImGuiPlatformImeData.by_value,
        "PlatformImeViewport", :uint,
        "DockContext", ImGuiDockContext.by_value,
        "DockNodeWindowMenuHandler", :pointer,
        "SettingsLoaded", :bool,
        "SettingsDirtyTimer", :float,
        "SettingsIniData", ImGuiTextBuffer.by_value,
        "SettingsHandlers", ImVector.by_value,
        "SettingsWindows", :pointer,
        "SettingsTables", :pointer,
        "Hooks", ImVector.by_value,
        "HookIdNext", :uint,
        "LocalizationTable[ImGuiLocKey_COUNT]", [:pointer, 13],
        "LogEnabled", :bool,
        "LogFlags", :int,
        "LogWindow", :pointer,
        "LogFile", :pointer,
        "LogBuffer", ImGuiTextBuffer.by_value,
        "LogNextPrefix", :pointer,
        "LogNextSuffix", :pointer,
        "LogLinePosY", :float,
        "LogLineFirstItem", :bool,
        "LogDepthRef", :int,
        "LogDepthToExpand", :int,
        "LogDepthToExpandDefault", :int,
        "ErrorCallback", :ImGuiErrorCallback,
        "ErrorCallbackUserData", :pointer,
        "ErrorTooltipLockedPos", ImVec2.by_value,
        "ErrorFirst", :bool,
        "ErrorCountCurrentFrame", :int,
        "StackSizesInNewFrame", ImGuiErrorRecoveryState.by_value,
        "StackSizesInBeginForCurrentWindow", :pointer,
        "DebugDrawIdConflictsCount", :int,
        "DebugLogFlags", :int,
        "DebugLogBuf", ImGuiTextBuffer.by_value,
        "DebugLogIndex", ImGuiTextIndex.by_value,
        "DebugLogSkippedErrors", :int,
        "DebugLogAutoDisableFlags", :int,
        "DebugLogAutoDisableFrames", :uchar,
        "DebugLocateFrames", :uchar,
        "DebugBreakInLocateId", :bool,
        "DebugBreakKeyChord", :int,
        "DebugBeginReturnValueCullDepth", :char,
        "DebugItemPickerActive", :bool,
        "DebugItemPickerMouseButton", :uchar,
        "DebugItemPickerBreakId", :uint,
        "DebugFlashStyleColorTime", :float,
        "DebugFlashStyleColorBackup", ImVec4.by_value,
        "DebugMetricsConfig", ImGuiMetricsConfig.by_value,
        "DebugIDStackTool", ImGuiIDStackTool.by_value,
        "DebugAllocInfo", ImGuiDebugAllocInfo.by_value,
        "DebugHoveredDockNode", :pointer,
        "FramerateSecPerFrame[60]", [:float, 60],
        "FramerateSecPerFrameIdx", :int,
        "FramerateSecPerFrameCount", :int,
        "FramerateSecPerFrameAccum", :float,
        "WantCaptureMouseNextFrame", :int,
        "WantCaptureKeyboardNextFrame", :int,
        "WantTextInputNextFrame", :int,
        "TempBuffer", ImVector.by_value,
        "TempKeychordName[64]", [:char, 64]
    )
    ImGuiContextHook.layout(
        "HookId", :uint,
        "Type", :int,
        "Owner", :uint,
        "Callback", :ImGuiContextHookCallback,
        "UserData", :pointer
    )
    ImGuiDataTypeInfo.layout(
        "Size", :size_t,
        "Name", :pointer,
        "PrintFmt", :pointer,
        "ScanFmt", :pointer
    )
    ImGuiDockNode.layout(
        "ID", :uint,
        "SharedFlags", :int,
        "LocalFlags", :int,
        "LocalFlagsInWindows", :int,
        "MergedFlags", :int,
        "State", :int,
        "ParentNode", :pointer,
        "ChildNodes[2]", [:pointer, 2],
        "Windows", ImVector.by_value,
        "TabBar", :pointer,
        "Pos", ImVec2.by_value,
        "Size", ImVec2.by_value,
        "SizeRef", ImVec2.by_value,
        "SplitAxis", :int,
        "WindowClass", ImGuiWindowClass.by_value,
        "LastBgColor", :uint,
        "HostWindow", :pointer,
        "VisibleWindow", :pointer,
        "CentralNode", :pointer,
        "OnlyNodeWithWindows", :pointer,
        "CountNodeWithWindows", :int,
        "LastFrameAlive", :int,
        "LastFrameActive", :int,
        "LastFrameFocused", :int,
        "LastFocusedNodeId", :uint,
        "SelectedTabId", :uint,
        "WantCloseTabId", :uint,
        "RefViewportId", :uint,
        "_bitfield_1", :int,
        "_bitfield_2", :bool
    )
    ImGuiFocusScopeData.layout(
        "ID", :uint,
        "WindowID", :uint
    )
    ImVec1.layout(
        "x", :float
    )
    ImGuiGroupData.layout(
        "WindowID", :uint,
        "BackupCursorPos", ImVec2.by_value,
        "BackupCursorMaxPos", ImVec2.by_value,
        "BackupCursorPosPrevLine", ImVec2.by_value,
        "BackupIndent", ImVec1.by_value,
        "BackupGroupOffset", ImVec1.by_value,
        "BackupCurrLineSize", ImVec2.by_value,
        "BackupCurrLineTextBaseOffset", :float,
        "BackupActiveIdIsAlive", :uint,
        "BackupDeactivatedIdIsAlive", :bool,
        "BackupHoveredIdIsAlive", :bool,
        "BackupIsSameLine", :bool,
        "EmitItem", :bool
    )
    ImGuiInputEvent.layout(
        "Type", :int,
        "Source", :int,
        "EventId", :uint,
        "_anonymous_1", :pointer,
        "AddedByTestEngine", :bool
    )
    ImGuiInputEventAppFocused.layout(
        "Focused", :bool
    )
    ImGuiInputEventKey.layout(
        "Key", :int,
        "Down", :bool,
        "AnalogValue", :float
    )
    ImGuiInputEventMouseButton.layout(
        "Button", :int,
        "Down", :bool,
        "MouseSource", :int
    )
    ImGuiInputEventMousePos.layout(
        "PosX", :float,
        "PosY", :float,
        "MouseSource", :int
    )
    ImGuiInputEventMouseViewport.layout(
        "HoveredViewportID", :uint
    )
    ImGuiInputEventMouseWheel.layout(
        "WheelX", :float,
        "WheelY", :float,
        "MouseSource", :int
    )
    ImGuiInputEventText.layout(
        "Char", :uint
    )
    ImGuiInputTextCallbackData.layout(
        "Ctx", :pointer,
        "EventFlag", :int,
        "Flags", :int,
        "UserData", :pointer,
        "EventChar", :ushort,
        "EventKey", :int,
        "Buf", :pointer,
        "BufTextLen", :int,
        "BufSize", :int,
        "BufDirty", :bool,
        "CursorPos", :int,
        "SelectionStart", :int,
        "SelectionEnd", :int
    )
    ImGuiKeyRoutingData.layout(
        "NextEntryIndex", :pointer,
        "Mods", :ushort,
        "RoutingCurrScore", :uchar,
        "RoutingNextScore", :uchar,
        "RoutingCurr", :uint,
        "RoutingNext", :uint
    )
    ImGuiListClipper.layout(
        "Ctx", :pointer,
        "DisplayStart", :int,
        "DisplayEnd", :int,
        "ItemsCount", :int,
        "ItemsHeight", :float,
        "StartPosY", :float,
        "StartSeekOffsetY", :double,
        "TempData", :pointer
    )
    ImGuiListClipperData.layout(
        "ListClipper", :pointer,
        "LossynessOffset", :float,
        "StepNo", :int,
        "ItemsFrozen", :int,
        "Ranges", ImVector.by_value
    )
    ImGuiListClipperRange.layout(
        "Min", :int,
        "Max", :int,
        "PosToIndexConvert", :bool,
        "PosToIndexOffsetMin", :char,
        "PosToIndexOffsetMax", :char
    )
    ImGuiLocEntry.layout(
        "Key", :int,
        "Text", :pointer
    )
    ImGuiMenuColumns.layout(
        "TotalWidth", :uint,
        "NextTotalWidth", :uint,
        "Spacing", :ushort,
        "OffsetIcon", :ushort,
        "OffsetLabel", :ushort,
        "OffsetShortcut", :ushort,
        "OffsetMark", :ushort,
        "Widths[4]", [:ushort, 4]
    )
    ImGuiMultiSelectIO.layout(
        "Requests", ImVector.by_value,
        "RangeSrcItem", :pointer,
        "NavIdItem", :pointer,
        "NavIdSelected", :bool,
        "RangeSrcReset", :bool,
        "ItemsCount", :int
    )
    ImGuiMultiSelectState.layout(
        "Window", :pointer,
        "ID", :uint,
        "LastFrameActive", :int,
        "LastSelectionSize", :int,
        "RangeSelected", :char,
        "NavIdSelected", :char,
        "RangeSrcItem", :pointer,
        "NavIdItem", :pointer
    )
    ImGuiMultiSelectTempData.layout(
        "IO", ImGuiMultiSelectIO.by_value,
        "Storage", :pointer,
        "FocusScopeId", :uint,
        "Flags", :int,
        "ScopeRectMin", ImVec2.by_value,
        "BackupCursorMaxPos", ImVec2.by_value,
        "LastSubmittedItem", :pointer,
        "BoxSelectId", :uint,
        "KeyMods", :int,
        "LoopRequestSetAll", :char,
        "IsEndIO", :bool,
        "IsFocused", :bool,
        "IsKeyboardSetRange", :bool,
        "NavIdPassedBy", :bool,
        "RangeSrcPassedBy", :bool,
        "RangeDstPassedBy", :bool
    )
    ImGuiOldColumnData.layout(
        "OffsetNorm", :float,
        "OffsetNormBeforeResize", :float,
        "Flags", :int,
        "ClipRect", ImRect.by_value
    )
    ImGuiOldColumns.layout(
        "ID", :uint,
        "Flags", :int,
        "IsFirstFrame", :bool,
        "IsBeingResized", :bool,
        "Current", :int,
        "Count", :int,
        "OffMinX", :float,
        "OffMaxX", :float,
        "LineMinY", :float,
        "LineMaxY", :float,
        "HostCursorPosY", :float,
        "HostCursorMaxPosX", :float,
        "HostInitialClipRect", ImRect.by_value,
        "HostBackupClipRect", ImRect.by_value,
        "HostBackupParentWorkRect", ImRect.by_value,
        "Columns", ImVector.by_value,
        "Splitter", ImDrawListSplitter.by_value
    )
    ImGuiOnceUponAFrame.layout(
        "RefFrame", :int
    )
    ImGuiPopupData.layout(
        "PopupId", :uint,
        "Window", :pointer,
        "RestoreNavWindow", :pointer,
        "ParentNavLayer", :int,
        "OpenFrameCount", :int,
        "OpenParentId", :uint,
        "OpenPopupPos", ImVec2.by_value,
        "OpenMousePos", ImVec2.by_value
    )
    ImGuiPtrOrIndex.layout(
        "Ptr", :pointer,
        "Index", :int
    )
    ImGuiSelectionBasicStorage.layout(
        "Size", :int,
        "PreserveOrder", :bool,
        "UserData", :pointer,
        "AdapterIndexToStorageId", :pointer,
        "_SelectionOrder", :int,
        "_Storage", ImGuiStorage.by_value
    )
    ImGuiSelectionExternalStorage.layout(
        "UserData", :pointer,
        "AdapterSetItemSelected", :pointer
    )
    ImGuiSelectionRequest.layout(
        "Type", :int,
        "Selected", :bool,
        "RangeDirection", :char,
        "RangeFirstItem", :pointer,
        "RangeLastItem", :pointer
    )
    ImGuiSettingsHandler.layout(
        "TypeName", :pointer,
        "TypeHash", :uint,
        "ClearAllFn", :pointer,
        "ReadInitFn", :pointer,
        "ReadOpenFn", :pointer,
        "ReadLineFn", :pointer,
        "ApplyAllFn", :pointer,
        "WriteAllFn", :pointer,
        "UserData", :pointer
    )
    ImGuiShrinkWidthItem.layout(
        "Index", :int,
        "Width", :float,
        "InitialWidth", :float
    )
    ImGuiSizeCallbackData.layout(
        "UserData", :pointer,
        "Pos", ImVec2.by_value,
        "CurrentSize", ImVec2.by_value,
        "DesiredSize", ImVec2.by_value
    )
    ImGuiStackLevelInfo.layout(
        "ID", :uint,
        "QueryFrameCount", :char,
        "QuerySuccess", :bool,
        "_bitfield_1", :int,
        "Desc[57]", [:char, 57]
    )
    ImGuiStoragePair.layout(
        "key", :uint,
        "_anonymous_1", :pointer
    )
    ImGuiStyleMod.layout(
        "VarIdx", :int,
        "_anonymous_1", :pointer
    )
    ImGuiStyleVarInfo.layout(
        "_bitfield_1", :uint,
        "_bitfield_2", :int,
        "_bitfield_3", :uint
    )
    ImGuiTabBar.layout(
        "Window", :pointer,
        "Tabs", ImVector.by_value,
        "Flags", :int,
        "ID", :uint,
        "SelectedTabId", :uint,
        "NextSelectedTabId", :uint,
        "VisibleTabId", :uint,
        "CurrFrameVisible", :int,
        "PrevFrameVisible", :int,
        "BarRect", ImRect.by_value,
        "CurrTabsContentsHeight", :float,
        "PrevTabsContentsHeight", :float,
        "WidthAllTabs", :float,
        "WidthAllTabsIdeal", :float,
        "ScrollingAnim", :float,
        "ScrollingTarget", :float,
        "ScrollingTargetDistToVisibility", :float,
        "ScrollingSpeed", :float,
        "ScrollingRectMinX", :float,
        "ScrollingRectMaxX", :float,
        "SeparatorMinX", :float,
        "SeparatorMaxX", :float,
        "ReorderRequestTabId", :uint,
        "ReorderRequestOffset", :pointer,
        "BeginCount", :char,
        "WantLayout", :bool,
        "VisibleTabWasSubmitted", :bool,
        "TabsAddedNew", :bool,
        "TabsActiveCount", :pointer,
        "LastTabItemIdx", :pointer,
        "ItemSpacingY", :float,
        "FramePadding", ImVec2.by_value,
        "BackupCursorPos", ImVec2.by_value,
        "TabsNames", ImGuiTextBuffer.by_value
    )
    ImGuiTabItem.layout(
        "ID", :uint,
        "Flags", :int,
        "Window", :pointer,
        "LastFrameVisible", :int,
        "LastFrameSelected", :int,
        "Offset", :float,
        "Width", :float,
        "ContentWidth", :float,
        "RequestedWidth", :float,
        "NameOffset", :pointer,
        "BeginOrder", :pointer,
        "IndexDuringLayout", :pointer,
        "WantClose", :bool
    )
    ImGuiTableInstanceData.layout(
        "TableInstanceID", :uint,
        "LastOuterHeight", :float,
        "LastTopHeadersRowHeight", :float,
        "LastFrozenHeight", :float,
        "HoveredRowLast", :int,
        "HoveredRowNext", :int
    )
    ImGuiTableColumnSortSpecs.layout(
        "ColumnUserID", :uint,
        "ColumnIndex", :pointer,
        "SortOrder", :pointer,
        "SortDirection", :int
    )
    ImGuiTableSortSpecs.layout(
        "Specs", :pointer,
        "SpecsCount", :int,
        "SpecsDirty", :bool
    )
    ImGuiTable.layout(
        "ID", :uint,
        "Flags", :int,
        "RawData", :pointer,
        "TempData", :pointer,
        "Columns", :pointer,
        "DisplayOrderToIndex", :pointer,
        "RowCellData", :pointer,
        "EnabledMaskByDisplayOrder", :pointer,
        "EnabledMaskByIndex", :pointer,
        "VisibleMaskByIndex", :pointer,
        "SettingsLoadedFlags", :int,
        "SettingsOffset", :int,
        "LastFrameActive", :int,
        "ColumnsCount", :int,
        "CurrentRow", :int,
        "CurrentColumn", :int,
        "InstanceCurrent", :pointer,
        "InstanceInteracted", :pointer,
        "RowPosY1", :float,
        "RowPosY2", :float,
        "RowMinHeight", :float,
        "RowCellPaddingY", :float,
        "RowTextBaseline", :float,
        "RowIndentOffsetX", :float,
        "_bitfield_1", :int,
        "RowBgColorCounter", :int,
        "RowBgColor[2]", [:uint, 2],
        "BorderColorStrong", :uint,
        "BorderColorLight", :uint,
        "BorderX1", :float,
        "BorderX2", :float,
        "HostIndentX", :float,
        "MinColumnWidth", :float,
        "OuterPaddingX", :float,
        "CellPaddingX", :float,
        "CellSpacingX1", :float,
        "CellSpacingX2", :float,
        "InnerWidth", :float,
        "ColumnsGivenWidth", :float,
        "ColumnsAutoFitWidth", :float,
        "ColumnsStretchSumWeights", :float,
        "ResizedColumnNextWidth", :float,
        "ResizeLockMinContentsX2", :float,
        "RefScale", :float,
        "AngledHeadersHeight", :float,
        "AngledHeadersSlope", :float,
        "OuterRect", ImRect.by_value,
        "InnerRect", ImRect.by_value,
        "WorkRect", ImRect.by_value,
        "InnerClipRect", ImRect.by_value,
        "BgClipRect", ImRect.by_value,
        "Bg0ClipRectForDrawCmd", ImRect.by_value,
        "Bg2ClipRectForDrawCmd", ImRect.by_value,
        "HostClipRect", ImRect.by_value,
        "HostBackupInnerClipRect", ImRect.by_value,
        "OuterWindow", :pointer,
        "InnerWindow", :pointer,
        "ColumnsNames", ImGuiTextBuffer.by_value,
        "DrawSplitter", :pointer,
        "InstanceDataFirst", ImGuiTableInstanceData.by_value,
        "InstanceDataExtra", ImVector.by_value,
        "SortSpecsSingle", ImGuiTableColumnSortSpecs.by_value,
        "SortSpecsMulti", ImVector.by_value,
        "SortSpecs", ImGuiTableSortSpecs.by_value,
        "SortSpecsCount", :pointer,
        "ColumnsEnabledCount", :pointer,
        "ColumnsEnabledFixedCount", :pointer,
        "DeclColumnsCount", :pointer,
        "AngledHeadersCount", :pointer,
        "HoveredColumnBody", :pointer,
        "HoveredColumnBorder", :pointer,
        "HighlightColumnHeader", :pointer,
        "AutoFitSingleColumn", :pointer,
        "ResizedColumn", :pointer,
        "LastResizedColumn", :pointer,
        "HeldHeaderColumn", :pointer,
        "ReorderColumn", :pointer,
        "ReorderColumnDir", :pointer,
        "LeftMostEnabledColumn", :pointer,
        "RightMostEnabledColumn", :pointer,
        "LeftMostStretchedColumn", :pointer,
        "RightMostStretchedColumn", :pointer,
        "ContextPopupColumn", :pointer,
        "FreezeRowsRequest", :pointer,
        "FreezeRowsCount", :pointer,
        "FreezeColumnsRequest", :pointer,
        "FreezeColumnsCount", :pointer,
        "RowCellDataCurrent", :pointer,
        "DummyDrawChannel", :ushort,
        "Bg2DrawChannelCurrent", :ushort,
        "Bg2DrawChannelUnfrozen", :ushort,
        "NavLayer", :char,
        "IsLayoutLocked", :bool,
        "IsInsideRow", :bool,
        "IsInitializing", :bool,
        "IsSortSpecsDirty", :bool,
        "IsUsingHeaders", :bool,
        "IsContextPopupOpen", :bool,
        "DisableDefaultContextMenu", :bool,
        "IsSettingsRequestLoad", :bool,
        "IsSettingsDirty", :bool,
        "IsDefaultDisplayOrder", :bool,
        "IsResetAllRequest", :bool,
        "IsResetDisplayOrderRequest", :bool,
        "IsUnfrozenRows", :bool,
        "IsDefaultSizingPolicy", :bool,
        "IsActiveIdAliveBeforeTable", :bool,
        "IsActiveIdInTable", :bool,
        "HasScrollbarYCurr", :bool,
        "HasScrollbarYPrev", :bool,
        "MemoryCompacted", :bool,
        "HostSkipItems", :bool
    )
    ImGuiTableCellData.layout(
        "BgColor", :uint,
        "Column", :pointer
    )
    ImGuiTableColumn.layout(
        "Flags", :int,
        "WidthGiven", :float,
        "MinX", :float,
        "MaxX", :float,
        "WidthRequest", :float,
        "WidthAuto", :float,
        "WidthMax", :float,
        "StretchWeight", :float,
        "InitStretchWeightOrWidth", :float,
        "ClipRect", ImRect.by_value,
        "UserID", :uint,
        "WorkMinX", :float,
        "WorkMaxX", :float,
        "ItemWidth", :float,
        "ContentMaxXFrozen", :float,
        "ContentMaxXUnfrozen", :float,
        "ContentMaxXHeadersUsed", :float,
        "ContentMaxXHeadersIdeal", :float,
        "NameOffset", :pointer,
        "DisplayOrder", :pointer,
        "IndexWithinEnabledSet", :pointer,
        "PrevEnabledColumn", :pointer,
        "NextEnabledColumn", :pointer,
        "SortOrder", :pointer,
        "DrawChannelCurrent", :ushort,
        "DrawChannelFrozen", :ushort,
        "DrawChannelUnfrozen", :ushort,
        "IsEnabled", :bool,
        "IsUserEnabled", :bool,
        "IsUserEnabledNextFrame", :bool,
        "IsVisibleX", :bool,
        "IsVisibleY", :bool,
        "IsRequestOutput", :bool,
        "IsSkipItems", :bool,
        "IsPreserveWidthAuto", :bool,
        "NavLayerCurrent", :char,
        "AutoFitQueue", :uchar,
        "CannotSkipItemsQueue", :uchar,
        "_bitfield_1", :uchar,
        "SortDirectionsAvailList", :uchar
    )
    ImGuiTableColumnSettings.layout(
        "WidthOrWeight", :float,
        "UserID", :uint,
        "Index", :pointer,
        "DisplayOrder", :pointer,
        "SortOrder", :pointer,
        "_bitfield_1", :uchar,
        "_bitfield_2", :char,
        "_bitfield_3", :uchar
    )
    ImGuiTableHeaderData.layout(
        "Index", :pointer,
        "TextColor", :uint,
        "BgColor0", :uint,
        "BgColor1", :uint
    )
    ImGuiTableSettings.layout(
        "ID", :uint,
        "SaveFlags", :int,
        "RefScale", :float,
        "ColumnsCount", :pointer,
        "ColumnsCountMax", :pointer,
        "WantApply", :bool
    )
    ImGuiTableTempData.layout(
        "TableIndex", :int,
        "LastTimeActive", :float,
        "AngledHeadersExtraWidth", :float,
        "AngledHeadersRequests", ImVector.by_value,
        "UserOuterSize", ImVec2.by_value,
        "DrawSplitter", ImDrawListSplitter.by_value,
        "HostBackupWorkRect", ImRect.by_value,
        "HostBackupParentWorkRect", ImRect.by_value,
        "HostBackupPrevLineSize", ImVec2.by_value,
        "HostBackupCurrLineSize", ImVec2.by_value,
        "HostBackupCursorMaxPos", ImVec2.by_value,
        "HostBackupColumnsOffset", ImVec1.by_value,
        "HostBackupItemWidth", :float,
        "HostBackupItemWidthStackSize", :int
    )
    ImGuiTextFilter.layout(
        "InputBuf[256]", [:char, 256],
        "Filters", ImVector.by_value,
        "CountGrep", :int
    )
    ImGuiTextRange.layout(
        "b", :pointer,
        "e", :pointer
    )
    ImGuiTreeNodeStackData.layout(
        "ID", :uint,
        "TreeFlags", :int,
        "ItemFlags", :int,
        "NavRect", ImRect.by_value
    )
    ImGuiViewport.layout(
        "ID", :uint,
        "Flags", :int,
        "Pos", ImVec2.by_value,
        "Size", ImVec2.by_value,
        "WorkPos", ImVec2.by_value,
        "WorkSize", ImVec2.by_value,
        "DpiScale", :float,
        "ParentViewportId", :uint,
        "DrawData", :pointer,
        "RendererUserData", :pointer,
        "PlatformUserData", :pointer,
        "PlatformHandle", :pointer,
        "PlatformHandleRaw", :pointer,
        "PlatformWindowCreated", :bool,
        "PlatformRequestMove", :bool,
        "PlatformRequestResize", :bool,
        "PlatformRequestClose", :bool
    )
    ImGuiViewportP.layout(
        "_ImGuiViewport", ImGuiViewport.by_value,
        "Window", :pointer,
        "Idx", :int,
        "LastFrameActive", :int,
        "LastFocusedStampCount", :int,
        "LastNameHash", :uint,
        "LastPos", ImVec2.by_value,
        "LastSize", ImVec2.by_value,
        "Alpha", :float,
        "LastAlpha", :float,
        "LastFocusedHadNavWindow", :bool,
        "PlatformMonitor", :short,
        "BgFgDrawListsLastFrame[2]", [:int, 2],
        "BgFgDrawLists[2]", [:pointer, 2],
        "DrawDataP", ImDrawData.by_value,
        "DrawDataBuilder", ImDrawDataBuilder.by_value,
        "LastPlatformPos", ImVec2.by_value,
        "LastPlatformSize", ImVec2.by_value,
        "LastRendererSize", ImVec2.by_value,
        "WorkInsetMin", ImVec2.by_value,
        "WorkInsetMax", ImVec2.by_value,
        "BuildWorkInsetMin", ImVec2.by_value,
        "BuildWorkInsetMax", ImVec2.by_value
    )
    ImGuiWindowTempData.layout(
        "CursorPos", ImVec2.by_value,
        "CursorPosPrevLine", ImVec2.by_value,
        "CursorStartPos", ImVec2.by_value,
        "CursorMaxPos", ImVec2.by_value,
        "IdealMaxPos", ImVec2.by_value,
        "CurrLineSize", ImVec2.by_value,
        "PrevLineSize", ImVec2.by_value,
        "CurrLineTextBaseOffset", :float,
        "PrevLineTextBaseOffset", :float,
        "IsSameLine", :bool,
        "IsSetPos", :bool,
        "Indent", ImVec1.by_value,
        "ColumnsOffset", ImVec1.by_value,
        "GroupOffset", ImVec1.by_value,
        "CursorStartPosLossyness", ImVec2.by_value,
        "NavLayerCurrent", :int,
        "NavLayersActiveMask", :short,
        "NavLayersActiveMaskNext", :short,
        "NavIsScrollPushableX", :bool,
        "NavHideHighlightOneFrame", :bool,
        "NavWindowHasScrollY", :bool,
        "MenuBarAppending", :bool,
        "MenuBarOffset", ImVec2.by_value,
        "MenuColumns", ImGuiMenuColumns.by_value,
        "TreeDepth", :int,
        "TreeHasStackDataDepthMask", :uint,
        "ChildWindows", ImVector.by_value,
        "StateStorage", :pointer,
        "CurrentColumns", :pointer,
        "CurrentTableIdx", :int,
        "LayoutType", :int,
        "ParentLayoutType", :int,
        "ModalDimBgColor", :uint,
        "WindowItemStatusFlags", :int,
        "ChildItemStatusFlags", :int,
        "DockTabItemStatusFlags", :int,
        "DockTabItemRect", ImRect.by_value,
        "ItemWidth", :float,
        "TextWrapPos", :float,
        "ItemWidthStack", ImVector.by_value,
        "TextWrapPosStack", ImVector.by_value
    )
    ImVec2ih.layout(
        "x", :short,
        "y", :short
    )
    ImGuiWindowDockStyle.layout(
        "Colors[ImGuiWindowDockStyleCol_COUNT]", [:uint, 8]
    )
    ImGuiWindow.layout(
        "Ctx", :pointer,
        "Name", :pointer,
        "ID", :uint,
        "Flags", :int,
        "FlagsPreviousFrame", :int,
        "ChildFlags", :int,
        "WindowClass", ImGuiWindowClass.by_value,
        "Viewport", :pointer,
        "ViewportId", :uint,
        "ViewportPos", ImVec2.by_value,
        "ViewportAllowPlatformMonitorExtend", :int,
        "Pos", ImVec2.by_value,
        "Size", ImVec2.by_value,
        "SizeFull", ImVec2.by_value,
        "ContentSize", ImVec2.by_value,
        "ContentSizeIdeal", ImVec2.by_value,
        "ContentSizeExplicit", ImVec2.by_value,
        "WindowPadding", ImVec2.by_value,
        "WindowRounding", :float,
        "WindowBorderSize", :float,
        "TitleBarHeight", :float,
        "MenuBarHeight", :float,
        "DecoOuterSizeX1", :float,
        "DecoOuterSizeY1", :float,
        "DecoOuterSizeX2", :float,
        "DecoOuterSizeY2", :float,
        "DecoInnerSizeX1", :float,
        "DecoInnerSizeY1", :float,
        "NameBufLen", :int,
        "MoveId", :uint,
        "TabId", :uint,
        "ChildId", :uint,
        "PopupId", :uint,
        "Scroll", ImVec2.by_value,
        "ScrollMax", ImVec2.by_value,
        "ScrollTarget", ImVec2.by_value,
        "ScrollTargetCenterRatio", ImVec2.by_value,
        "ScrollTargetEdgeSnapDist", ImVec2.by_value,
        "ScrollbarSizes", ImVec2.by_value,
        "ScrollbarX", :bool,
        "ScrollbarY", :bool,
        "ScrollbarXStabilizeEnabled", :bool,
        "ScrollbarXStabilizeToggledHistory", :uchar,
        "ViewportOwned", :bool,
        "Active", :bool,
        "WasActive", :bool,
        "WriteAccessed", :bool,
        "Collapsed", :bool,
        "WantCollapseToggle", :bool,
        "SkipItems", :bool,
        "SkipRefresh", :bool,
        "Appearing", :bool,
        "Hidden", :bool,
        "IsFallbackWindow", :bool,
        "IsExplicitChild", :bool,
        "HasCloseButton", :bool,
        "ResizeBorderHovered", :char,
        "ResizeBorderHeld", :char,
        "BeginCount", :short,
        "BeginCountPreviousFrame", :short,
        "BeginOrderWithinParent", :short,
        "BeginOrderWithinContext", :short,
        "FocusOrder", :short,
        "AutoFitFramesX", :char,
        "AutoFitFramesY", :char,
        "AutoFitOnlyGrows", :bool,
        "AutoPosLastDirection", :int,
        "HiddenFramesCanSkipItems", :char,
        "HiddenFramesCannotSkipItems", :char,
        "HiddenFramesForRenderOnly", :char,
        "DisableInputsFrames", :char,
        "_bitfield_1", :int,
        "SetWindowPosVal", ImVec2.by_value,
        "SetWindowPosPivot", ImVec2.by_value,
        "IDStack", ImVector.by_value,
        "DC", ImGuiWindowTempData.by_value,
        "OuterRectClipped", ImRect.by_value,
        "InnerRect", ImRect.by_value,
        "InnerClipRect", ImRect.by_value,
        "WorkRect", ImRect.by_value,
        "ParentWorkRect", ImRect.by_value,
        "ClipRect", ImRect.by_value,
        "ContentRegionRect", ImRect.by_value,
        "HitTestHoleSize", ImVec2ih.by_value,
        "HitTestHoleOffset", ImVec2ih.by_value,
        "LastFrameActive", :int,
        "LastFrameJustFocused", :int,
        "LastTimeActive", :float,
        "ItemWidthDefault", :float,
        "StateStorage", ImGuiStorage.by_value,
        "ColumnsStorage", ImVector.by_value,
        "FontWindowScale", :float,
        "FontWindowScaleParents", :float,
        "FontDpiScale", :float,
        "FontRefSize", :float,
        "SettingsOffset", :int,
        "DrawList", :pointer,
        "DrawListInst", ImDrawList.by_value,
        "ParentWindow", :pointer,
        "ParentWindowInBeginStack", :pointer,
        "RootWindow", :pointer,
        "RootWindowPopupTree", :pointer,
        "RootWindowDockTree", :pointer,
        "RootWindowForTitleBarHighlight", :pointer,
        "RootWindowForNav", :pointer,
        "ParentWindowForFocusRoute", :pointer,
        "NavLastChildNavWindow", :pointer,
        "NavLastIds[ImGuiNavLayer_COUNT]", [:uint, 2],
        "NavRectRel[ImGuiNavLayer_COUNT]", [ImRect.by_value, 2],
        "NavPreferredScoringPosRel[ImGuiNavLayer_COUNT]", [ImVec2.by_value, 2],
        "NavRootFocusScopeId", :uint,
        "MemoryDrawListIdxCapacity", :int,
        "MemoryDrawListVtxCapacity", :int,
        "MemoryCompacted", :bool,
        "_bitfield_2", :bool,
        "DockOrder", :short,
        "DockStyle", ImGuiWindowDockStyle.by_value,
        "DockNode", :pointer,
        "DockNodeAsHost", :pointer,
        "DockId", :uint
    )
    ImGuiWindowSettings.layout(
        "ID", :uint,
        "Pos", ImVec2ih.by_value,
        "Size", ImVec2ih.by_value,
        "ViewportPos", ImVec2ih.by_value,
        "ViewportId", :uint,
        "DockId", :uint,
        "ClassId", :uint,
        "DockOrder", :short,
        "Collapsed", :bool,
        "IsChild", :bool,
        "WantApply", :bool,
        "WantDelete", :bool
    )
    ImGuiWindowStackData.layout(
        "Window", :pointer,
        "ParentLastItemDataBackup", ImGuiLastItemData.by_value,
        "StackSizesInBegin", ImGuiErrorRecoveryState.by_value,
        "DisabledOverrideReenable", :bool,
        "DisabledOverrideReenableAlphaBackup", :float
    )
  end
end
