# frozen_string_literal: true

# This file is generated by `rake generate`. Do not edit it manually.


module ImGui
  module Native
    typedef :pointer, :ImBitArrayForNamedKeys
    typedef :pointer, :ImBitArrayPtr
    callback :ImDrawCallback, [:pointer, :pointer], :void
    typedef :int, :ImDrawFlags
    typedef :ushort, :ImDrawIdx
    typedef :int, :ImDrawListFlags
    typedef :pointer, :ImFileHandle
    typedef :int, :ImFontAtlasFlags
    typedef :int, :ImGuiActivateFlags
    typedef :int, :ImGuiBackendFlags
    typedef :int, :ImGuiButtonFlags
    typedef :int, :ImGuiChildFlags
    typedef :int, :ImGuiCol
    typedef :int, :ImGuiColorEditFlags
    typedef :int, :ImGuiComboFlags
    typedef :int, :ImGuiCond
    typedef :int, :ImGuiConfigFlags
    callback :ImGuiContextHookCallback, [:pointer, :pointer], :void
    typedef :int, :ImGuiDataAuthority
    typedef :int, :ImGuiDataType
    typedef :int, :ImGuiDebugLogFlags
    typedef :int, :ImGuiDockNodeFlags
    typedef :int, :ImGuiDragDropFlags
    callback :ImGuiErrorCallback, [:pointer, :pointer, :string], :void
    typedef :int, :ImGuiFocusRequestFlags
    typedef :int, :ImGuiFocusedFlags
    typedef :int, :ImGuiHoveredFlags
    typedef :uint, :ImGuiID
    typedef :int, :ImGuiInputFlags
    callback :ImGuiInputTextCallback, [:pointer], :int
    typedef :int, :ImGuiInputTextFlags
    typedef :int, :ImGuiItemFlags
    typedef :int, :ImGuiItemStatusFlags
    typedef :int, :ImGuiKeyChord
    typedef :pointer, :ImGuiKeyRoutingIndex
    typedef :int, :ImGuiLayoutType
    typedef :int, :ImGuiLogFlags
    callback :ImGuiMemAllocFunc, [:size_t, :pointer], :pointer
    callback :ImGuiMemFreeFunc, [:pointer, :pointer], :void
    typedef :int, :ImGuiMouseButton
    typedef :int, :ImGuiMouseCursor
    typedef :int, :ImGuiMultiSelectFlags
    typedef :int, :ImGuiNavMoveFlags
    typedef :int, :ImGuiNavRenderCursorFlags
    typedef :int, :ImGuiNextItemDataFlags
    typedef :int, :ImGuiNextWindowDataFlags
    typedef :int, :ImGuiOldColumnFlags
    typedef :int, :ImGuiPopupFlags
    typedef :int, :ImGuiScrollFlags
    typedef :int, :ImGuiSelectableFlags
    typedef :pointer, :ImGuiSelectionUserData
    typedef :int, :ImGuiSeparatorFlags
    callback :ImGuiSizeCallback, [:pointer], :void
    typedef :int, :ImGuiSliderFlags
    typedef :int, :ImGuiStyleVar
    typedef :int, :ImGuiTabBarFlags
    typedef :int, :ImGuiTabItemFlags
    typedef :int, :ImGuiTableBgTarget
    typedef :int, :ImGuiTableColumnFlags
    typedef :pointer, :ImGuiTableColumnIdx
    typedef :ushort, :ImGuiTableDrawChannelIdx
    typedef :int, :ImGuiTableFlags
    typedef :int, :ImGuiTableRowFlags
    typedef :int, :ImGuiTextFlags
    typedef :int, :ImGuiTooltipFlags
    typedef :int, :ImGuiTreeNodeFlags
    typedef :int, :ImGuiTypingSelectFlags
    typedef :int, :ImGuiViewportFlags
    typedef :int, :ImGuiWindowFlags
    typedef :int, :ImGuiWindowRefreshFlags
    typedef :int, :ImPoolIdx
    typedef :pointer, :ImS16
    typedef :pointer, :ImS32
    typedef :pointer, :ImS64
    typedef :char, :ImS8
    typedef :pointer, :ImStbTexteditState
    typedef :ulong_long, :ImTextureID
    typedef :ushort, :ImU16
    typedef :uint, :ImU32
    typedef :ulong_long, :ImU64
    typedef :uchar, :ImU8
    typedef :ushort, :ImWchar
    typedef :ushort, :ImWchar16
    typedef :uint, :ImWchar32
  end
end
