# frozen_string_literal: true

require "tmpdir"
require_relative "../generator/emitter"
require_relative "../generator/api_emitter"

RSpec.describe ImGuiRuby::Generator::Emitter do
  let(:fixture_root) { File.expand_path("fixtures/generator", __dir__) }

  it "generates deterministic lazy FFI declarations from cimgui metadata" do
    Dir.mktmpdir("imgui-generator") do |output|
      described_class.new(
        metadata_dir: File.join(fixture_root, "metadata"),
        output_dir: output,
        overrides_path: File.join(fixture_root, "overrides.yml")
      ).generate!

      generated = File.read(File.join(output, "functions.rb"))
      golden = File.read(File.join(fixture_root, "functions.rb.golden"))
      expect(generated).to eq(golden)
    end
  end

  it "maps enums, arrays, structs, and typedefs to FFI types" do
    Dir.mktmpdir("imgui-generator") do |output|
      described_class.new(
        metadata_dir: File.join(fixture_root, "metadata"),
        output_dir: output,
        overrides_path: File.join(fixture_root, "overrides.yml")
      ).generate!

      expect(File.read(File.join(output, "enums.rb"))).to include("DockingEnable = Native::ImGuiConfigFlags_DockingEnable")
      expect(File.read(File.join(output, "structs.rb"))).to include('"values[2]", [:float, 2]')
      expect(File.read(File.join(output, "typedefs.rb"))).to include("typedef :uint, :ImGuiID")
      expect(File.read(File.join(output, "typedefs.rb"))).to include(
        "callback :ImGuiInputTextCallback, [:pointer], :int"
      )
    end
  end
end

RSpec.describe ImGuiRuby::Generator::ApiEmitter do
  let(:fixture_root) { File.expand_path("fixtures/generator", __dir__) }

  it "renders generated literals without relying on Hash#inspect formatting" do
    emitter = described_class.allocate
    value = {
      "flags" => 0,
      "label" => "demo",
      "size" => [1.0, 2.0],
      "enabled" => true,
      "callback" => nil
    }

    expect(emitter.__send__(:ruby_literal, value)).to eq(
      '{"flags" => 0, "label" => "demo", "size" => [1.0, 2.0], ' \
      '"enabled" => true, "callback" => nil}'
    )
  end

  it "omits lifecycle and varargs functions from the generated Ruby API" do
    Dir.mktmpdir("imgui-api-generator") do |output|
      output_path = File.join(output, "api_generated.rb")
      described_class.new(
        metadata_dir: File.join(fixture_root, "metadata"),
        output_path: output_path,
        overrides_path: File.join(fixture_root, "overrides.yml")
      ).generate!

      expect(File.read(output_path)).to eq(<<~RUBY)
        # frozen_string_literal: true

        # This file is generated by `rake generate`. Do not edit it manually.


        module ImGui

        end
      RUBY
    end
  end
end
