#include <SDL3/SDL.h>
#include <SDL3/SDL_vulkan.h>

#include "backend_function_bridge.h"

#define IMGUI_RUBY_SDL3(function_name, ...)                                                       \
    IMGUI_RUBY_BACKEND_CALL("SDL3", function_name, __VA_ARGS__)

#undef SDL_free
#undef SDL_strdup

#define SDL_CaptureMouse(...) IMGUI_RUBY_SDL3(SDL_CaptureMouse, __VA_ARGS__)
#define SDL_CloseGamepad(...) IMGUI_RUBY_SDL3(SDL_CloseGamepad, __VA_ARGS__)
#define SDL_CreateSystemCursor(...) IMGUI_RUBY_SDL3(SDL_CreateSystemCursor, __VA_ARGS__)
#define SDL_CreateWindow(...) IMGUI_RUBY_SDL3(SDL_CreateWindow, __VA_ARGS__)
#define SDL_DestroyCursor(...) IMGUI_RUBY_SDL3(SDL_DestroyCursor, __VA_ARGS__)
#define SDL_DestroyWindow(...) IMGUI_RUBY_SDL3(SDL_DestroyWindow, __VA_ARGS__)
#define SDL_GL_CreateContext(...) IMGUI_RUBY_SDL3(SDL_GL_CreateContext, __VA_ARGS__)
#define SDL_GL_DestroyContext(...) IMGUI_RUBY_SDL3(SDL_GL_DestroyContext, __VA_ARGS__)
#define SDL_GL_GetCurrentContext(...) IMGUI_RUBY_SDL3(SDL_GL_GetCurrentContext, __VA_ARGS__)
#define SDL_GL_MakeCurrent(...) IMGUI_RUBY_SDL3(SDL_GL_MakeCurrent, __VA_ARGS__)
#define SDL_GL_SetAttribute(...) IMGUI_RUBY_SDL3(SDL_GL_SetAttribute, __VA_ARGS__)
#define SDL_GL_SetSwapInterval(...) IMGUI_RUBY_SDL3(SDL_GL_SetSwapInterval, __VA_ARGS__)
#define SDL_GL_SwapWindow(...) IMGUI_RUBY_SDL3(SDL_GL_SwapWindow, __VA_ARGS__)
#define SDL_GetClipboardText(...) IMGUI_RUBY_SDL3(SDL_GetClipboardText, __VA_ARGS__)
#define SDL_GetCurrentVideoDriver(...) IMGUI_RUBY_SDL3(SDL_GetCurrentVideoDriver, __VA_ARGS__)
#define SDL_GetDisplayBounds(...) IMGUI_RUBY_SDL3(SDL_GetDisplayBounds, __VA_ARGS__)
#define SDL_GetDisplayContentScale(...) IMGUI_RUBY_SDL3(SDL_GetDisplayContentScale, __VA_ARGS__)
#define SDL_GetDisplayUsableBounds(...) IMGUI_RUBY_SDL3(SDL_GetDisplayUsableBounds, __VA_ARGS__)
#define SDL_GetDisplays(...) IMGUI_RUBY_SDL3(SDL_GetDisplays, __VA_ARGS__)
#define SDL_GetGamepadAxis(...) IMGUI_RUBY_SDL3(SDL_GetGamepadAxis, __VA_ARGS__)
#define SDL_GetGamepadButton(...) IMGUI_RUBY_SDL3(SDL_GetGamepadButton, __VA_ARGS__)
#define SDL_GetGamepads(...) IMGUI_RUBY_SDL3(SDL_GetGamepads, __VA_ARGS__)
#define SDL_GetGlobalMouseState(...) IMGUI_RUBY_SDL3(SDL_GetGlobalMouseState, __VA_ARGS__)
#define SDL_GetKeyboardFocus(...) IMGUI_RUBY_SDL3(SDL_GetKeyboardFocus, __VA_ARGS__)
#define SDL_GetPerformanceCounter(...) IMGUI_RUBY_SDL3(SDL_GetPerformanceCounter, __VA_ARGS__)
#define SDL_GetPerformanceFrequency(...) IMGUI_RUBY_SDL3(SDL_GetPerformanceFrequency, __VA_ARGS__)
#define SDL_GetPointerProperty(...) IMGUI_RUBY_SDL3(SDL_GetPointerProperty, __VA_ARGS__)
#define SDL_GetWindowFlags(...) IMGUI_RUBY_SDL3(SDL_GetWindowFlags, __VA_ARGS__)
#define SDL_GetWindowFromID(...) IMGUI_RUBY_SDL3(SDL_GetWindowFromID, __VA_ARGS__)
#define SDL_GetWindowID(...) IMGUI_RUBY_SDL3(SDL_GetWindowID, __VA_ARGS__)
#define SDL_GetWindowPosition(...) IMGUI_RUBY_SDL3(SDL_GetWindowPosition, __VA_ARGS__)
#define SDL_GetWindowProperties(...) IMGUI_RUBY_SDL3(SDL_GetWindowProperties, __VA_ARGS__)
#define SDL_GetWindowRelativeMouseMode(...) IMGUI_RUBY_SDL3(SDL_GetWindowRelativeMouseMode, __VA_ARGS__)
#define SDL_GetWindowSize(...) IMGUI_RUBY_SDL3(SDL_GetWindowSize, __VA_ARGS__)
#define SDL_GetWindowSizeInPixels(...) IMGUI_RUBY_SDL3(SDL_GetWindowSizeInPixels, __VA_ARGS__)
#define SDL_HideCursor(...) IMGUI_RUBY_SDL3(SDL_HideCursor, __VA_ARGS__)
#define SDL_OpenGamepad(...) IMGUI_RUBY_SDL3(SDL_OpenGamepad, __VA_ARGS__)
#define SDL_OpenURL(...) IMGUI_RUBY_SDL3(SDL_OpenURL, __VA_ARGS__)
#define SDL_RaiseWindow(...) IMGUI_RUBY_SDL3(SDL_RaiseWindow, __VA_ARGS__)
#define SDL_SetClipboardText(...) IMGUI_RUBY_SDL3(SDL_SetClipboardText, __VA_ARGS__)
#define SDL_SetCursor(...) IMGUI_RUBY_SDL3(SDL_SetCursor, __VA_ARGS__)
#define SDL_SetHint(...) IMGUI_RUBY_SDL3(SDL_SetHint, __VA_ARGS__)
#define SDL_SetTextInputArea(...) IMGUI_RUBY_SDL3(SDL_SetTextInputArea, __VA_ARGS__)
#define SDL_SetWindowOpacity(...) IMGUI_RUBY_SDL3(SDL_SetWindowOpacity, __VA_ARGS__)
#define SDL_SetWindowParent(...) IMGUI_RUBY_SDL3(SDL_SetWindowParent, __VA_ARGS__)
#define SDL_SetWindowPosition(...) IMGUI_RUBY_SDL3(SDL_SetWindowPosition, __VA_ARGS__)
#define SDL_SetWindowSize(...) IMGUI_RUBY_SDL3(SDL_SetWindowSize, __VA_ARGS__)
#define SDL_SetWindowTitle(...) IMGUI_RUBY_SDL3(SDL_SetWindowTitle, __VA_ARGS__)
#define SDL_ShowCursor(...) IMGUI_RUBY_SDL3(SDL_ShowCursor, __VA_ARGS__)
#define SDL_ShowWindow(...) IMGUI_RUBY_SDL3(SDL_ShowWindow, __VA_ARGS__)
#define SDL_StartTextInput(...) IMGUI_RUBY_SDL3(SDL_StartTextInput, __VA_ARGS__)
#define SDL_StopTextInput(...) IMGUI_RUBY_SDL3(SDL_StopTextInput, __VA_ARGS__)
#define SDL_Vulkan_CreateSurface(...) IMGUI_RUBY_SDL3(SDL_Vulkan_CreateSurface, __VA_ARGS__)
#define SDL_WarpMouseGlobal(...) IMGUI_RUBY_SDL3(SDL_WarpMouseGlobal, __VA_ARGS__)
#define SDL_WarpMouseInWindow(...) IMGUI_RUBY_SDL3(SDL_WarpMouseInWindow, __VA_ARGS__)
#define SDL_free(...) IMGUI_RUBY_SDL3(SDL_free, __VA_ARGS__)
#define SDL_strdup(...) IMGUI_RUBY_SDL3(SDL_strdup, __VA_ARGS__)

#include "imgui_impl_sdl3.cpp"
